<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
*/

?>

<head>
    <title>Reportes </title>
    <script language="JavaScript" type="text/javascript" src="//localhost/pruebas/js/ajax.js"></script>
</head>

<table style="height: 100%; width: 100%; background-color: #E5F1F4"  align="center">
    <tr><th colspan="2"> <div id="div_TituloPreguntas" style="height: 100%; width: 100%"></div>
        </th>
    </tr>
    <tr><td colspan="2">
            <div>
                <fieldset class="ui-corner-all ui-widget-content">
                    <legend><b>Preguntas</b></legend>
                    <input id="chk_all_preguntas" type="checkbox"/><label style="color:#3366FF; font-size:12px; font-weight:bold">Marcar/desmarcar todos</label><br/>
                    <?php
                    echo "<table>";
                    foreach($lista_preguntas_calif as $key=> $val) {
                        echo "<tr><td>";
                        echo Tag::checkboxField("chkpreguntas[]", "value: $key","checked: ").$val."&nbsp;&nbsp;";
                        echo "</tr></td>";
                    }
                    echo "<tr><td><input type='button' value='Aceptar' id='btnAceptar' /></td></tr>";
                    echo "</table>";
                    ?>
                </fieldset>
            </div>
        </td></tr>
    <tr><td width="80px">            
            <div id="div_grafica"  align="left"style="width: 100%; height: 100% ">
                <table align="left">
                    <tr>
                        <td>
                            <input id="chk_barrasPreguntasCalificada" type="checkbox"/><label style="color:#3366FF; font-size:12px; font-weight:bold">BARRAS</label>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input id="chk_pastelPreguntasCalificadas" type="checkbox"/><label style="color:#3366FF; font-size:12px; font-weight:bold">PASTEL</label>
                        <td>

                        </td>
                    </tr>
                </table>
            </div>
        </td>
        <td>
            <table style="height: 100%;width: 100%" align="center">


                <td>
                    <div id="div_barraPreguntasCalificada" style="width: 100%; height: 100%" align="center">
                    </div>

                </td>
                <td>
                    <div id="div_pastelPreguntasCalificada" style="width: 100%; height: 100%" align="center"></div>

                </td>
                <tr><td colspan="2"><div id="div_TablaPreguntasCalificadas"  style="width:100%"></div></td></tr>
                <tr>  <td colspan="3">
                        <div id="Div_Todo" style="width: 100%; height: 100%" align="center">
                        </div>

                    </td></tr>
                <tr>
            </table>

        </td>
    </tr>
</table>
<script>
    var arreglopreguntas=new Array();

    $("#chk_all_preguntas").click(function(){
        var chks=$("input:checkbox[name^='chkpre']");
        chks.attr("checked",$(this).is(":checked"));
        arreglopreguntas=[];
        for (var x=0; x < chks.length; x++) {
            if (chks[x].checked) {
               // alert("hola"+x);
                arreglopreguntas[x]=chks[x].value;
            }
        }

//        VerCuadroPreguntasCalificadas();

    })
    $("#btnAceptar").click(function(){
        chekpregunta();
        VerCuadroPreguntasCalificadas();
    })

    function chekpregunta(){
        var chkp=$("input:checkbox[name^='chkpre']");
        var ids="";
        arreglopreguntas=[];
        var con=0;
        //   alert(chkmodulos.length);
        for (var x=0; x < chkp.length; x++) {
            if (chkp[x].checked) {
                ids=ids+chkp[x].value+",";
                arreglopreguntas[con]= chkp[x].value;
                con++;
            }

        }
    }
</script>