<div id="div_menu" class="ocultar">
    <div style="height: 100%; width:100%; text-align:center; font-size:14px" class="ui-dialog ui-dialog-titlebar ui-widget-header ui-widget-header  ui-corner-all ui-helper-clearfix">Menú</div>
    <div align="top" style="height: 90%;width: 100%">
        <fieldset class='ui-corner-all ui-widget-content' style="height: 100%">
            <table  id="tbl_menu" border="0" width="100%">
                <tr>
                    <td width="200px" height="500px"  style="vertical-align:top">
                        <table border="0" style="vertical-align: top; width: 100%;height: 100%">
                            <tr>
                                <td>

                                    <table width="100%" >
                                        <tr>
                                            <td class="empty">
                                                <fieldset class='ui-corner-all ui-widget-content'>
                                                    <p><label class='labelform' ><span for='desde'>Desde:</span></label><?php echo Tag::textField("desde", "size: 12", "maxlength: 12","class:  dateISO") ?></p>
                                                </fieldset>
                                        </tr>
                                        <tr>

                                            <td class="empty">
                                                <fieldset class='ui-corner-all ui-widget-content'>
                                                    <p><label class='labelform' ><span for='hasta'>Hasta:</span></label><?php echo Tag::textField("hasta", "size: 12", "maxlength: 12","class:  dateISO") ?></p>
                                                </fieldset>
                                            </td>

                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td>

                                    <table width="100%" >
                                        <tr>
                                            <td class="empty">
                                                <fieldset class='ui-corner-all ui-widget-content'>
                                                    <legend><b>Duración</b></legend>
                                                    <p><label class='labelform' ><span for='horas'>Tomar turnos con duración a partir de:</span></label><?php echo Tag::textField("horas", "size: 2", "maxlength: 2","class: ","value: 00").":";
                                                        echo Tag::textField("minutos", "size: 2", "maxlength: 2","class: ","value: 00").":";
                                                        echo Tag::textField("segundos", "size: 2", "maxlength: 2","class: ","value: 00");?></p>
                                                </fieldset>
                                            </td>

                                        </tr>
                                    </table>


                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <fieldset class="ui-corner-all ui-widget-content">
                                        <legend><b>Areas</b></legend>
                                        <input id="chk_all_areas" type="checkbox" /><label style="color:#3366FF; font-size:12px; font-weight:bold">Marcar/desmarcar todos</label><br/>
                                        <?php
                                        $db = DbBase::rawConnect();
                                        $areas=array();
                                        $nombres=array();
                                        $i=0;
                                        $array_valores=array();
                                        $result = $db->query("SELECT id as clave, nombre_ubicacion as nombre  FROM ubicacion ");
                                        while($row = $db->fetchArray($result)) {
                                            //  $areas[$i]= array('Id'=>$row[0],'nombre'=>$row[1]);
                                            $nombres[$i]=$row[1];

                                            $array_valores[]=Tag::checkboxField("chkareas[]", "value: $row[0]","checked: ","onclick: chekArea()").$row[1]."&nbsp;&nbsp;";
                                            $i++;

                                        }
                                        $opcion= $nombres;
                                        echo "<table>";
                                        $cont_mod=count($array_valores);
                                        $cont_filas=ceil($cont_mod/3);
                                        $x=$cont_filas*3;
                                        $y=$x-$cont_mod;
                                        for ($z=1;$z<=$y;$z++)
                                            $array_valores[]="";
                                        $cont_key=0;
                                        for ($f=1; $f<=$cont_filas; $f++) { //filas
                                            echo "<tr>";
                                            for ($c=1;$c<=3;$c++) { //columnas
                                                echo "<td>".$array_valores[$cont_key]."</td>";
                                                $cont_key+=1;
                                            }
                                            echo "</tr>";
                                        }
                                        echo "</table>";
                                        ?>

                                    </fieldset>
                                    <div id="div_opcion" align="center">
                                    </div>


                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <fieldset class='ui-corner-all ui-widget-content'>
                                        <legend><b>Módulos</b></legend>
                                        <input id="chk_all_modulos" type="checkbox"/><label style="color:#3366FF; font-size:12px; font-weight:bold">Marcar/desmarcar todos</label><br/>
                                        <div id="div_modulos">
                                            <table width="100%" >
                                                <tr>
                                                    <td class="empty">
                                                        <?php
                                                        $col=0;
                                                        $i=0;
                                                        $array_valores=array();
                                                        foreach($lista_modulos_tad as $key=> $val) {

                                                            $array_valores[]=Tag::checkboxField("chkmodulos[]", "value: $key","checked: ","onclick: cheks()")."Módulo ".$val."&nbsp;&nbsp;";

                                                        }
                                                        echo "<table>";
                                                        $cont_mod=count($lista_modulos_tad);
                                                        $cont_filas=ceil($cont_mod/3);
                                                        $x=$cont_filas*3;
                                                        $y=$x-$cont_mod;
                                                        for ($z=1;$z<=$y;$z++)
                                                            $array_valores[]="";
                                                        $cont_key=0;
                                                        for ($f=1; $f<=$cont_filas; $f++) { //filas
                                                            echo "<tr>";
                                                            for ($c=1;$c<=3;$c++) { //columnas
                                                                echo "<td>".$array_valores[$cont_key]."</td>";
                                                                $cont_key+=1;
                                                            }
                                                            echo "</tr>";
                                                        }
                                                        echo "</table>";
                                                        ?>

                                                    </td>

                                                </tr>
                                            </table>
                                        </div>
                                    </fieldset>
                                </td>
                            </tr>

                            <tr>
                                <td><fieldset class="ui-corner-all ui-widget-content"><legend><b>Grupo Servicio</b></legend>
                                        <input id="chk_all_gruposervicios" type="checkbox" /><label style="color:#3366FF; font-size:12px; font-weight:bold">Marcar/desmarcar todos</label><br/>
                                        <div id="div_GrupoServicios">
                                        </div>
                                    </fieldset>
                                </td>
                            </tr>
                            <tr>
                                <td><fieldset class="ui-corner-all ui-widget-content"><legend><b>Servicios</b></legend>
                                        <input id="chk_all_servicios" type="checkbox" /><label style="color:#3366FF; font-size:12px; font-weight:bold">Marcar/desmarcar todos</label><br/>

                                        <div id="div_Servicio">
                                            seleccione Grupos de Servicios..para ver Servicios!!
                                        </div>


                                    </fieldset>
                                </td>
                            </tr>
                            <tr>
                                <td>

                                    <table width="100%" >

                                        <tr><td><center><input type="button" id="boton" value="Aceptar" title="Aceptar" >
                                                    <input type="button" id="boton1" value="Velocidad Cargar" title="Aceptar" ></center></td></tr>
                                    </table>

                                </td>
                            </tr>
                        </table>
                    </td>


                </tr>
            </table>
        </fieldset>
    </div>

</div>