<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('sinchistorial/guardar');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Sinchistorial</legend>
		<p><label class='labelform' ><span for='sucursal_id'><b>Sucursal</b>:</span></label><?php echo Tag::select("sucursal_id", $Sucursal->find("order: alias_sucursal"), "using: id,alias_sucursal", "use_dummy: yes","dummyValue: ''","class: ") ?></p>
		<p><label class='labelform' ><span for='fecha_sincronizacion'><b>Fecha Sincronizacion</b>:</span></label><?php echo Tag::textField("fecha_sincronizacion", "size: 0", "maxlength: 0","class:  dateISO") ?></p>
		<p><label class='labelform' ><span for='hora_sincronizacion'><b>Hora Sincronizacion</b>:</span></label><?php echo Tag::textField("hora_sincronizacion", "size: 0", "maxlength: 0","class: ") ?></p>
		<p><label class='labelform' ><span for='registros_sincronizados'><b>Registros Sincronizados</b>:</span></label><?php echo Tag::textField("registros_sincronizados", "size: 5", "maxlength: 11","class:  numeric") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
