<script type="text/javascript" src="http://localhost/pruebas/highcharts-2-1-6/js/highcharts.js"></script>

<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
*/

?>
<table>
    <tr>
        <td>
            <div id="tabla"  style="width: 800px; height: 200px; margin: 0 auto"></div></td>
    </tr>
    <tr>
        <td>
            <div  id="div_cuadro"  style="width: 800px; height: 200px; margin: 0 auto"></div>
        </td>
    </tr>
</table>