<fieldset class='ui-corner-all ui-widget-content'>
    <legend>Tipo de Calificación para los operadores</legend>
    <p><label class='labelform' style="width:300px"><span for='calif_4botones_teclado'><b>Calificación con teclado de 4 botones</b>:</span></label><?php echo Tag::checkboxField("calif_4botones_teclado");?></p>
    <p><label class='labelform' style="width:300px"><span for='calif_4botones_pantalla'><b>Calificación con pantalla touch de 4 botones</b>:</span></label><?php echo Tag::checkboxField("calif_4botones_pantalla");?></p>
    <p><label class='labelform' style="width:300px"><span for='calif_matriz_pantalla'><b>Calificación con pantalla touch de multipreguntas</b>:</span></label><?php echo Tag::checkboxField("calif_matriz_pantalla");?></p>
</fieldset>
