<link rel="stylesheet" href="<?php echo Core::getInstancePath()?>css/themes/ui.jqgrid.css">
<script type='text/javascript' src='<?php echo Core::getInstancePath()?>javascript/core/framework/jQuery/jqGrid/len/grid.locale-sp.js'></script>
<script type='text/javascript' src='<?php echo Core::getInstancePath()?>javascript/core/framework/jQuery/jqGrid/jquery.jqGrid.min.js'></script>

<?php
//print_r($menu_usuario);die();
foreach ($menu_usuario as $menu){
    $tabs[]=array('caption'=>$menu['nombre_modulo'],'content'=>Tag::treeview($menu['idModulo'], $menu['menu'],"options: animated: 'fast',collapsed: true, unique: true","class: filetree"));
}
Tag::accordion($tabs,"options: event: 'mouseover', fillSpace: true,clearStyle: true ");


?>
<script type="text/javascript">
function cargarPagina(url,tipo){
        if(tipo=='popup'){
           var Xpos=(screen.width/2)-285;
           var Ypos=(screen.height/2)-220;
           $("#content-center").html('');
           window.open(url,'popup','width=600,height=480,scrollbars=yes,resizable=yes,left='+Xpos+',top='+Ypos);
        }else{
            $("#content-center").load(url,function(){
            });
        }
   }
</script>