<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('userdispensador/guardar');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Userdispensador</legend>
		<p><label class='labelform' ><span for='usuario_id'><b>Usuario</b>:</span></label><?php echo Tag::select("usuario_id", $Usuario->find("order: id"), "using: id,nombres", "use_dummy: yes","dummyValue: ''","class: ") ?></p>
		<p><label class='labelform' ><span for='dispensador_id'><b>Dispensador</b>:</span></label><?php echo Tag::select("dispensador_id", $Dispensador->find("order: id"), "using: id,descripcion", "use_dummy: yes","dummyValue: ''","class: ") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
