<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('caja/guardar');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Caja</legend>
		<p><label class='labelform' ><span for='numero'><b>Numero</b>:</span></label><?php echo Tag::textField("numero", "size: 11", "maxlength: 11","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='descripcion'><b>Descripcion</b>:</span></label><?php echo Tag::textField("descripcion", "size: 145", "maxlength: 145","class: ") ?></p>
		<p><label class='labelform' ><span for='estado'><b>Estado</b>:</span></label><?php echo Tag::selectStatic("estado",array('1'=>'Activo', '0'=>'Inactivo')) ?></p>
		
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
