<!--
Configurar para operador
-->

<fieldset class="ui-corner-all ui-widget-content">
    <legend>Configuraciones para Operador</legend>
    <p><label class='labelform' ><span for='ver_tiempo_maximo'><b>Ver Tiempo Máximo</b>:</span></label><?php echo Tag::checkboxField("ver_tiempo_maximo");?></p>
    <p><label class='labelform' ><span for='ver_tiempo_atencion'><b>Ver Tiempo de Atención</b>:</span></label><?php echo Tag::checkboxField("ver_tiempo_atencion");?></p>
</fieldset>
