<fieldset class="ui-corner-all ui-widget-content">
    <legend>Datos Generales</legend>
    <p><label class='labelform' ><span for='descripcion'><b>Descripción</b>:</span></label><?php echo Tag::textField("descripcion", "size: 45", "maxlength: 45","class: required") ?></p>
</fieldset>

<?php
$listausuarios=array();
//SELECT u.nombres FROM usuario u, dispensador d, userdispensador ud
//WHERE u.id=ud.usuario_id AND d.id=ud.dispensador_id AND d.id=1;


$condicion = "{#Dispensador}.id = $id";
$query = new ActiveRecordJoin(array(
    "entities" => array("Usuario", "Dispensador", "Userdispensador"),
    "fields" => array(
    "{#Usuario}.id",
    "{#Usuario}.nombres"),
    "conditions" => $condicion
));
foreach($query->getResultSet() as $result) {
    $listausuarios[$result->getId()]=$result->getNombres();
}

$condicion = "{#Grupo}.id = 4";
$query = new ActiveRecordJoin(array(
    "entities" => array("Usuario", "Grupo", "Grupousuario"),
    "fields" => array(
    "{#Usuario}.id",
    "{#Usuario}.nombres"),
    "conditions" => $condicion
));

foreach($query->getResultSet() as $result) {
    $listausuarios[$result->getId()]=$result->getNombres();
}

?>
<fieldset class="ui-corner-all ui-widget-content">
    <legend>Usuario</legend>
    <p><label class='labelform' ><span for='usuarios'><b>Asignar a Usuario</b>:</span></label><?php echo Tag::selectStatic("usuarios", $listausuarios,"class:  required") ?></p>
</fieldset>

<fieldset class="ui-corner-all ui-widget-content">
    <legend>Tipo de Dispensador</legend>
    <table border="0px"  align="left">
        <?php
        if ($dispensadorSimple==1) {
            echo "<tr><td>";
            echo Tag::radioField("radio_tipo_dispensador",array ('simple'=>'Dispensador simple'));
            echo "</tr></td>";
        }
        if ($dispensadorTouch==1) {
            echo "<tr><td>";
            echo Tag::radioField("radio_tipo_dispensador",array ('touch'=>'Dispensador con pantalla touch'));
            echo "</tr></td>";
        }
        if ($dispensadorBotonera==1) {
            echo "<tr><td>";
            echo Tag::radioField("radio_tipo_dispensador",array ('botonera'=>'Dispensador con botonera'));
            echo "</tr></td>";
        }
        if ($dispensadorTouchPequenia==1) {
            echo "<tr><td>";
            echo Tag::radioField("radio_tipo_dispensador",array ('touch_pequenia'=>'Dispensador con pantalla touch pequeña'));
            echo "</tr></td>";
        }
        ?>
    </table>
</fieldset>