<table width="100%">
    <tr>
        <td valign="top">
            <div style='padding:10px'>
                <table align="center" width="100%">
                    <?php
                    $servicio=new Servicio();
                    $buscaServicios = $servicio->find("estado = 1", "order: nombre asc");
                    ?>
                    <tr>
                        <td>
                            <div style='padding:10px'>
                                <b>Seleccione los servicios:</b>
                            </div>
                            <?php if(count($buscaServicios)>0) { ?>
                            <table border="1px"  align="center" width="70%">
                                <thead>
                                    <tr>
                                        <th>Nombre del Servicio</th>
                                        <!--<th>Ubicación</th>
                                        <th>Grupo</th>-->
                                        <th>Asignar <br>
                                            <input type="button" onclick="marcar(this.form)" value="Seleccionar todos"/>
                                            <input type="button" onclick="desmarcar(this.form)" value="Deseleccionar todos"/>
                                        </th>
                                    </tr>
                                </thead>
                                    <?php
                                    $dispensadorservicio=new Dispensadorservicio();
                                    $servicioactivo=$dispensadorservicio->find("conditions: dispensador_id= $id");
                                    //   $servicioactivo=$this->Dispensadorservicio->find("conditions: dispensador_id= $id");
                                    if(count($servicioactivo)>0) {
                                        $listaservicios=array();
                                        foreach($servicioactivo as $fila) {
                                            $listaservicios[]=$fila->getServicioId();
                                        }
                                    }else {
                                        $listaservicios[] = "0";
                                    }

                                    // llenar tabla con servicios
                                    foreach($buscaServicios as $attribute) {
                                        $arrayid[] = $attribute->getId();
                                        $arraynombre[] = $attribute->getNombre();
                                        $idservicio=$attribute->getId();
                                        // print "<td>".$attribute->getId()."</td>";
                                        print "<td>".$attribute->getNombre()."</td>";
                                        if(in_array($idservicio,$listaservicios)) {
                                        //print "<td align='center'>".Tag::checkboxField("chkservicio".$idservicio, "checked: checked")."</td>";
                                            print "<td align='center'>".Tag::checkboxField("chkservicio[]", "value: $idservicio", "checked: checked")."</td>";
                                        }else {
                                            print "<td align='center'>".Tag::checkboxField("chkservicio[]", "value: $idservicio")."</td>";
                                        //print "<td align='center'>".Tag::checkboxField("chkservicio".$idservicio)."</td>";
                                        }
                                        print "</tr>";
                                    }
                                    ?>
                            </table>
                            <?php }  ?>
                        </td>
                    </tr>
            </div>
        </td>
    </tr>
</table>
<script>
    /*Script que marca todos los videos*/
    function marcar(obj) {
        elem=obj.elements;
        for (i=0;i<elem.length;i++)
            if (elem[i].type=="checkbox")
                elem[i].checked=true;
    }
    /*Script que desmarca todos los videos*/
    function desmarcar(obj) {
        elem=obj.elements;
        for (i=0;i<elem.length;i++)
            if (elem[i].type=="checkbox")
                elem[i].checked=false;
    }
</script>