<!--
Configurar para operador
-->
<?php
$logo = '';
$db = DbBase::rawConnect();
$result2 = $db->query("SELECT logo, logo_sinticket, logo_conticket, logo_calificador, logo_ticket	FROM configuracionsistema ;");
while($row = $db->fetchArray($result2)) 
{
$logo=$row['logo'];
$logo_sinticket=$row['logo_sinticket'];
$logo_conticket=$row['logo_conticket'];
$logo_calificador=$row['logo_calificador'];
$logo_ticket=$row['logo_ticket'];
}
?>
<fieldset class="ui-corner-all ui-widget-content">
    <legend>Configuración del logo</legend>
<table width="350" border="1">
  <tr>
    <td>&nbsp;</td>
    <td colspan="2" align="center"><strong> Mostrar Logo pw</strong></td>
  </tr>
  <tr>
    <td><strong>Tipo de pantalla</strong></td>
    <td><strong>NO</strong></td>
    <td><strong>SI</strong></td>    
  </tr>
  <tr>
    <td>Dispensador</td>
    <td>
      <label>
        <input name="RadioGroup2" type="radio" id="RadioGroup2_0" value="opción" <?php if($logo == 0) echo 'checked="checked"'; ?>/>	
      </label>	
	</td>
    <td>
		<input type="radio" name="RadioGroup2" value="opción" id="RadioGroup2_1" <?php if($logo == 1) echo 'checked="checked"'; ?> />	
	</td>    
  </tr>
  


  
  
  
  <tr>
    <td>Turnos sin ticket</td>
    <td>
      <label>
        <input name="RadioGroup3" type="radio" id="RadioGroup3_0" value="opción" <?php if($logo_sinticket == 0) echo 'checked="checked"'; ?>/>	
      </label>	
	</td>
    <td>
		<input type="radio" name="RadioGroup3" value="opción" id="RadioGroup3_1" <?php if($logo_sinticket == 1) echo 'checked="checked"'; ?> />	
	</td>    
  </tr>
  
  <tr>
    <td>Turnos con ticket</td>
    <td>
      <label>
        <input name="RadioGroup4" type="radio" id="RadioGroup4_0" value="opción" <?php if($logo_conticket == 0) echo 'checked="checked"'; ?>/>	
      </label>	
	</td>
    <td>
		<input type="radio" name="RadioGroup4" value="opción" id="RadioGroup4_1" <?php if($logo_conticket == 1) echo 'checked="checked"'; ?> />	
	</td>    
  </tr>  
  

  <tr>
    <td>Calificadores</td>
    <td>
      <label>
        <input name="RadioGroup5" type="radio" id="RadioGroup5_0" value="opción" <?php if($logo_calificador == 0) echo 'checked="checked"'; ?>/>	
      </label>	
	</td>
    <td>
		<input type="radio" name="RadioGroup5" value="opción" id="RadioGroup5_1" <?php if($logo_calificador == 1) echo 'checked="checked"'; ?> />	
	</td>    
  </tr>
  
  <tr>
    <td>Impresión del ticket</td>
    <td>
      <label>
        <input name="RadioGroup6" type="radio" id="RadioGroup6_0" value="opción" <?php if($logo_ticket == 0) echo 'checked="checked"'; ?>/>	
      </label>	
	</td>
    <td>
		<input type="radio" name="RadioGroup6" value="opción" id="RadioGroup6_1" <?php if($logo_ticket == 1) echo 'checked="checked"'; ?> />	
	</td>    
  </tr>  
  
  
</table>

<?php echo Tag::textField("logo", "size: 40", "maxlength: 100","class: required", "hidden: 'hidden'" , "value: $logo") ?>
<?php echo Tag::textField("logo_sinticket", "size: 40", "maxlength: 100","class: required", "hidden: 'hidden'" , "value: $logo_sinticket") ?>
<?php echo Tag::textField("logo_conticket", "size: 40", "maxlength: 100","class: required", "hidden: 'hidden'" , "value: $logo_conticket") ?>
<?php echo Tag::textField("logo_calificador", "size: 40", "maxlength: 100","class: required", "hidden: 'hidden'" , "value: $logo_calificador") ?>
<?php echo Tag::textField("logo_ticket", "size: 40", "maxlength: 100","class: required", "hidden: 'hidden'" , "value: $logo_ticket") ?>

</fieldset>
<script>
$("#RadioGroup2_0").click(function(){
document.getElementById('logo').value = 0;
});
$("#RadioGroup2_1").click(function(){
document.getElementById('logo').value = 1;
});   
</script>


<script>
$("#RadioGroup3_0").click(function(){
document.getElementById('logo_sinticket').value = 0;
});
$("#RadioGroup3_1").click(function(){
document.getElementById('logo_sinticket').value = 1;
});   
</script>
<script>
$("#RadioGroup4_0").click(function(){
document.getElementById('logo_conticket').value = 0;
});
$("#RadioGroup4_1").click(function(){
document.getElementById('logo_conticket').value = 1;
});   
</script>

<script>
$("#RadioGroup5_0").click(function(){
document.getElementById('logo_calificador').value = 0;
});
$("#RadioGroup5_1").click(function(){
document.getElementById('logo_calificador').value = 1;
});   
</script>
<script>
$("#RadioGroup6_0").click(function(){
document.getElementById('logo_ticket').value = 0;
});
$("#RadioGroup6_1").click(function(){
document.getElementById('logo_ticket').value = 1;
});   
</script>



