<!--
Configurar para operador
-->
<?php
$tono = '';
$db = DbBase::rawConnect();
$result2 = $db->query("SELECT 	tono	FROM configuracionsistema ;");
while ($row = $db->fetchArray($result2)) {
    $tono = $row['tono'];
}
?>
<fieldset class="ui-corner-all ui-widget-content">
    <legend>Configuración del tono de llamado</legend>
    
    <p><label class='labelform' ><span for='RadioGroup0_0'><b>Timbre</b>:</span></label><input name="RadioGroup0" type="radio" id="RadioGroup0_0" value="opción" <?php if ($tono == 0) echo 'checked="checked"'; ?>/></p>
    <p><label class='labelform' ><span for='RadioGroup0_1'><b>Voz</b>:</span></label><input type="radio" name="RadioGroup0" value="opción" id="RadioGroup0_1" <?php if ($tono == 1) echo 'checked="checked"'; ?> /></p>
    <p><label class='labelform'><span for='tiempo_tono'><b>Tiempo</b>:</span></label><?php echo Tag::numericField("tiempo_tono", "size: 10", "maxlength: 3","class: required") ?></p>
    
    <?php echo Tag::textField("tono_prueba", "size: 40", "maxlength: 100", "class: required", "hidden: 'hidden'", "value: $tono") ?>
</fieldset>
<script>
    $("#RadioGroup0_0").click(function(){
        document.getElementById('tono_prueba').value = 0;
    });
    $("#RadioGroup0_1").click(function(){
        document.getElementById('tono_prueba').value = 1;
    });   
</script>



