<!--
CON COMBO DE LETRA
-->
<script type="text/javascript" src="../../js/jscolor.js"></script>

<div id='mainContent'>
    <?php //echo View::getContent();
    //echo Tag::form('servicio/guardar');
    ?>
    <?php
    View::renderPartial("toolbarform");
    echo Tag::form("servicio/guardar");
    /*INICIO Para seleccionar las letras con combo*/
    $fun = new Funciones();
    $asignar_letras = $fun->verRestoLetras();
    /*FIN Para seleccionar las letras con combo*/
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Servicio</legend>
        <p><label class='labelform' style="width:200px"><span for='nombre'><b>Nombre</b>:</span></label><?php echo Tag::textField("nombre", "size: 40", "maxlength: 50","class: required") ?></p>
        <p><label class='labelform' style="width:200px"><span for='descripcion'><b>Descripcion</b>:</span></label><?php echo Tag::textField("descripcion",  "size: 40", "maxlength: 150","class: ") ?></p>
        <!--<p><label class='labelform' ><span for='letra'><b>Letra</b>:</span></label><?php //echo Tag::textField("letra", "size: 1", "maxlength: 1","class: required") ?></p>-->
        <p><label class='labelform' style="width:200px"><span for='descripcion'><b>Letra</b>:</span></label><?php echo Tag::selectStatic("letra",$asignar_letras,"class: required") ?></p>
        <!--<p><label class='labelform' ><span for='estado'><b>Estado</b>:</span></label><?php //echo Tag::selectStatic("estado",array(1=>'Activo', 2=>'Inactivo'), "wide=11") ?></p>-->
        <p><label class='labelform' style="width:200px"><span for='estado'><b>Estado (Activo/Inactivo)</b>:</span></label><?php echo Tag::checkboxField("estado");?></p>
        <!--<p><label class='labelform' ><span for='inicio'><b>Inicio</b>:</span></label><?php //echo Tag::textField("inicio", "size: 5", "maxlength: 5","class:  numeric, required", "value: 0") ?></p>
        <p><label class='labelform' ><span for='fin'><b>Fin</b>:</span></label><?php //echo Tag::textField("fin", "size: 5", "maxlength: 5","class:  numeric, required", "value: 100") ?></p>-->
        <!--<p><label class='labelform' ><span for='actual'><b>Actual</b>:</span></label><?php //echo Tag::textField("actual", "size: 11", "maxlength: 11","class:  numeric") ?></p>-->

        <?php
        //INICIO grupo del servicio
        $listagruposervicio="";
        $gruposervicio = new Gruposervicio();
        $buscaGruposervicio = $gruposervicio->find();
        foreach($buscaGruposervicio as $result) {
            $listagruposervicio[$result->getId()]=$result->getNombreGrupoServicio();
        }
        ?>
        <p><label class='labelform' style="width:200px"><span for='ubicacion'><b>Grupo del Servicio</b>:</span></label><?php echo Tag::selectStatic("gruposervicio", $listagruposervicio,"class:  required") ?></p>
        <?php
        //INICIO ubicacion del servicio
        $listagruposervicio="";
        $ubicacion = new Ubicacion();
        $buscaUbicacion = $ubicacion->find();
        foreach($buscaUbicacion as $result) {
            $listaubicacion[$result->getId()]=$result->getNombreUbicacion();
        }
        ?>
        <p><label class='labelform' style="width:200px"><span for='ubicacion'><b>Ubicación</b>:</span></label><?php echo Tag::selectStatic("ubicacion", $listaubicacion,"class:  required") ?></p>
        <p><label class='labelform' style="width:200px"><span for='tiempo_maximo'><b>Tiempo Máximo de atención</b>:</span></label><?php echo Tag::textField("tiempo_maximo", "size: 5", "maxlength: 10","class: ", "value: 00:10:00") ?></p>
        <p><label class='labelform' style="width:200px"><span for='nombre'><b>Color de letra en dispensador</b>:</span></label><?php echo Tag::textField("color", "size: 10", "maxlength: 10","class: color") ?></p>
    </fieldset>
    <!--<div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
    </div>-->
    <?php echo Tag::endForm(); ?>
</div>

<script>
    $("#tiempo_maximo").timepicker({ timeFormat: 'hh:mm:ss' });
</script>