<style type="text/css">
    #div_numero_grande {
        position: absolute;
        left: 529px;
        top: 102px;
        z-index:5;
    }
    #div_foto {
        position: absolute;
        left: 184px;
        top: 150px;
        z-index:5;
    }
    #div_nombre {
        position: absolute;
        left: 32px;
        top: 404px;
        width: 481px;
        z-index:5;
    }
    .nombre {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 38px;
        font-style: normal;
        background-color:transparent;
        border:none;
        text-align:center;
        width: 481px;
    }
</style>

<?php
$arrayPane[]=array('position'=>'middle','options'=>'resizable: false','partial'=>'plantilla_calificacion');
Tag::pane($arrayPane);
?>
<div id="div_numero_grande">
</div>
<div id="div_foto">
</div>
<div id="div_nombre" class="nombre">
</div>
<script>
    var carpeta=String($("#carpeta").val());
    document.getElementById("div_numero_grande").innerHTML =
        '<img src="../../img/'+carpeta+'/sistema/numeros/'+ modulo +'.png" width="231" height="325" />';
    document.getElementById("div_foto").innerHTML =
        '<img src="../../img/fotos/'+ foto +'" width="190" height="235" />';
    document.getElementById("div_nombre").innerHTML =usuario;
</script>