<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('configuracionsistema/guardar');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Configuracionsistema</legend>
		<p><label class='labelform' ><span for='activar_calificador'><b>Activar Calificador</b>:</span></label><?php echo Tag::textField("activar_calificador", "size: 1", "maxlength: 1","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='activar_difusion'><b>Activar Difusion</b>:</span></label><?php echo Tag::textField("activar_difusion", "size: 1", "maxlength: 1","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='publicar_noticias'><b>Publicar Noticias</b>:</span></label><?php echo Tag::textField("publicar_noticias", "size: 1", "maxlength: 1","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='velocidad_publicacion'><b>Velocidad Publicacion</b>:</span></label><?php echo Tag::textField("velocidad_publicacion", "size: 4", "maxlength: 4","class: ") ?></p>
		<p><label class='labelform' ><span for='pc_difusion'><b>Pc Difusion</b>:</span></label><?php echo Tag::textField("pc_difusion", "size: 50", "maxlength: 50","class: ") ?></p>
		<p><label class='labelform' ><span for='puerto'><b>Puerto</b>:</span></label><?php echo Tag::textField("puerto", "size: 10", "maxlength: 10","class: ") ?></p>
		<p><label class='labelform' ><span for='creacion_at'><b>Creacion At</b>:</span></label><?php echo Tag::textField("creacion_at", "size: 0", "maxlength: 0","class:  dateISO") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
