<?php echo Tag::javascriptBase() ?>
<!doctype html>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <script type="text/javascript" src="<?php echo Core::getInstancePath(); ?>public/js/webcam.js"></script>
        <script src="http://<?php echo $servidor_node; ?>/socket.io/socket.io.js"></script>
        <title>Calificador</title>
        <style type="text/css">
            #div_camara{ position:absolute; z-index:0;}

            #div_fondo {
                position: absolute;
                left: 0px;
                top: 0px;
                z-index:1;
            }

            #div_contenido {
                position: absolute;
                left: 161px;
                top: 115px;
                width:523px;
                height:362px;
                z-index:2;
            }

            //*contenido*/
            #div_encabezado {
                position: absolute;
                left: 244px;
                top: 30px;
                z-index:3;
            }
            #div_numero_grande {
                position: absolute;
                left: 529px;
                top: 132px;
                z-index:3;
            }
            #div_foto {
                position: absolute;
                left: 184px;
                top: 150px;
                z-index:3;
            }
            
            #div_nombre {
                position: absolute;
                left: 32px;
                top: 404px;
                width: 481px;
                z-index:3;
            }
            #div_prueba {
                position: absolute;
                left: 244px;
                top: 30px;
                z-index:3;
            }
            .nombre {
                font-family: Arial, Helvetica, sans-serif;
                font-size: 38px;
                font-style: normal;
                background-color:transparent;
                border:none;
                text-align:center;
                width: 481px;
            }

            /*segunda*/

            #div_cenefa {
                position: absolute;
                left: 0px;
                top: 0px;
                z-index:3;
            }
            #div_logo_institucion {
                position: absolute;
                left: 0px;
                top: 0px;
                z-index:3;
            }
            #div_logo_pw {
                position: absolute;
                left: 710px;
                top: 425px;
                z-index:3;
            }

            #div_publicidad222 {
                position: absolute;
                left: 24px;
                top: 200px;
                z-index:3;
            }	
            .encabezado{
                font-family: Arial, Helvetica, sans-serif;
                font-size: 65px;
                font-style: normal;
                color: black;
            }
            #div_publicidad {
                position: absolute;
                left: 161px;
                top: 115px;
                width:523px;
                height:362px;
                z-index:3;
            }

            /*pantalla calificado 4 botones*/
            .fondo_operador{
                background-image:url("../img/fondo.png");
                background-repeat:repeat-x;
                height:100%;
            }
            .boton_calificacion1{
                color:#fff;
                font-weight:bold;
                font-size: 45pt;
                width: 350px;
                height: 85px;
            }
            .boton_calificacion2{
                font-size: 45pt;
                width: 350px;
                height: 75px;
            }
            .boton_excelente{
                background-color:transparent;
                border: transparent;		background-image:url("../img/<?php echo $carpeta; ?>/sistema/excelente.png");
                background-size: 100% 100%;
            }
            .boton_muy_bueno{
                background-color:transparent;
                border: transparent;		background-image:url("../img/<?php echo $carpeta; ?>/sistema/muybueno.png");
                background-size: 100% 100%;		
            }
            .boton_bueno{
                background-color:transparent;
                border: transparent;		background-image:url("../img/<?php echo $carpeta; ?>/sistema/bueno.png");
                background-size: 100% 100%;		
            }
            .boton_regular{
                background-color:transparent;
                border: transparent;		background-image:url("../img/<?php echo $carpeta; ?>/sistema/regular.png");
                background-size: 100% 100%;		
            }


        </style>
    </head>
    <body>
        <div class="div_camara">
            <div id="my_camera" style="width:320px; height:240px;"></div>
            <!-- chat -->
            CHAT
            <div id="chat"></div>
        </div>
        <div id="div_fondo">
            <?php echo Tag::image($carpeta . "/sistema/calificacion_fondo_horizontal7.jpg", 'id: img_logo_calificacion', 'width: 795px', 'height: 470px') ?>
        </div>
        <div id="div_content"> <!-- Aqui se reemplaza segun como cargue-->
<!--            <div id="div_encabezado" class="encabezado">
                MODULO  
            </div>-->
            <div id="div_prueba" class="encabezado">
                MODULO  
            </div>
            <div id="div_numero_grande">
                <img src="../img/<?php echo $carpeta; ?>/sistema/numeros/<?php echo $numero_modulo; ?>.png" width="201" height="295" onclick="prueba()" />
            </div>
            <div id="div_foto">
                <img src="../img/<?php echo $carpeta; ?>/fotos/<?php echo $foto; ?>" width="190" height="235" />
            </div>
            <div id="div_nombre" class="nombre"><?php echo $nombre_operador; ?></div>
        </div>

        <input type="text" id="url" name="url" value="<?php echo Utils::getKumbiaUrl("calificador/ajax") ?>"/>
        <input type="text" id="ip_calificador" name="ip_calificador" value="<?php echo $ip_calificador; ?>"/>
        <input type="text" id="turno_id" name="turno_id" value=""/>
        <br>
<!--        <input type="button" value="enviar" onclick="enviar()"/>-->


        <!-- Configure a few settings and attach camera -->
        <script language="JavaScript">
            Webcam.set({
                image_format: 'jpeg',
                jpeg_quality: 90
            });
            Webcam.attach('#my_camera');

            function take_snapshot() {
                var data_uri = Webcam.snap();
                data = {
                    src: data_uri
                }
                $.ajax({
                    url: $("#url").val(),
                    data: data,
                    type: 'post',
                    success: function(respuesta) {
                        $('#fotoGuardada').attr('src', respuesta).show(500);
                    }
                });
            }
        </script>



        <script>
            try {
                var socket = io.connect("http://<?php echo $servidor_node; ?>");
                $.unblockUI();
            }
            catch (err) {
                alert("No se ha podido conectar con el servidor NODE correctamente.\nIntente nuevamente.\nSi el problema persiste comuníquese con Sistemas.\nCódigo de error: 101");
                $.unblockUI();
            }
            var socket = io.connect("http://<?php echo $servidor_node; ?>");
//            function enviar() {
//                var msg_siguiente = "siguiente|192.168.1.6";
//                socket.emit('send message', msg_siguiente);
//            }
        </script>


        <!-- Code to handle taking the snapshot and displaying it locally -->
        <script language="JavaScript">
            jQuery(function($) {
                var socket = io.connect("http://<?php echo $servidor_node; ?>");
                var $chat = $('#chat');
                socket.on('new message', function(data) {
                    $chat.text(data);   //envio a chat el msg
                    var smg_siguiente = $("#chat").text();
                    var res = smg_siguiente.split("|");
                    //alert(res.length);
                    if (res.length >= 4) {  //si es >=5 dio siguiente
                        //--busco que opcion sigue
                        var op = res[4].split(":");
                        //alert(op[1]);
                        if (op[0] == 'op' & op[1] == 'siguiente') {
                            var turno = res[5].split(":");
                            //--muestra la pantalla de publicidad
                            $("#turno_id").val(turno[1]);
                            cargar('cargarPublicacion');
                        }
                        if (op[0] == 'op' & op[1] == 'atender') {
                            //--muestra la pantalla de publicidad
                            cargar('cargarPublicacion');
                        }
                        if (op[0] == 'op' & op[1] == 'calificar') {
                            alert("cargar pantalla calificacion")
//                            tipo_calificacion = "B";
//                            if (tipo_calificacion == "A") {
//                                //$("#valor1").focus();
//                            } else if (tipo_calificacion == "B") {  //Pantalla Simple
                            cargar('cargarCalificacion');
//                            } else if (tipo_calificacion == "C") {   //Pantalla Matriz
//                                cargar('cargarCalificacionMatriz')
//                            }
                        }
                        /*var ip = res[3].split(":");
                         if (ip[0] == 'ip') {
                         if (ip[1] == '192.168.1.6') {
                         take_snapshot();    //--toma y guarda la foto
                         }
                         }*/
                    }
                });
            });

            function cargar(pantalla) {
                $.ajax({
                    type: "POST",
                    url: "<?php echo Utils::getKumbiaUrl("calificador/") ?>" + pantalla,
                    beforeSend: function() {
                        //$("#city").html("<option>Loading ...</option>");
                    },
                    data: "cartowner=1",
                    success: function(msg) {
                        $("#div_content").html(msg);
                    }
                });
            }
        </script>
    </body>
</html>
