<?php echo Tag::javascriptBase() ?>
<!doctype html>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
        <script type="text/javascript" src="<?php echo Core::getInstancePath(); ?>public/js/webcam.js"></script>
        <script src="http://<?php echo $servidor_node; ?>/socket.io/socket.io.js"></script>
        <title>Calificador</title>
        <style type="text/css">
            #div_camara{ position:absolute; z-index:0;}

            #div_fondo {
                position: absolute;
                left: 0px;
                top: 0px;
                z-index:1;
            }
            .texto_3d{
                font-family: Garamond, serif;
                line-height: 1em;
                color: #ec1c23;
                font-weight:bold;
                text-shadow:0px 0px 0 rgb(212,4,11),1px 1px 0 rgb(197,-11,-4),2px 2px 0 rgb(183,-25,-18),3px 3px 0 rgb(168,-40,-33),4px 4px 0 rgb(154,-54,-47),5px 5px 0 rgb(139,-69,-62), 6px 6px 0 rgb(125,-83,-76),7px 7px 6px rgba(0,0,0,0.6),7px 7px 1px rgba(0,0,0,0.5),0px 0px 6px rgba(0,0,0,.2);
            }

            /*vertical*/
            @media only screen and (min-width:100px) {
                #div_prueba { /*modulo*/
                    position: absolute;
                    top: 40px;
                    left: 160px;
/*                    width: 100%;*/
                    z-index:3;
                    font-size: 70px;
                    text-align: left;
                }
                #div_numero_grande {
                    position: absolute;
                    width: 100%;
                    top: 120px;
/*                    left: 0px;*/
                    z-index:3;
                }
                #div_foto {
                    position: absolute;
                    width: 100%;
                    top: 480px;
                    z-index:3;
                } 
                #div_nombre {
                    position: absolute;
                    width: 100%;
                    top: 850px;
                    z-index:3;
                }
                /*INICIO PUBLICACION*/
                #div_publicidad222 { /*turno*/
                    position: absolute;
                    width:100%;
                    top: 160px;
                    z-index:3;
                    font-size: 90px;
                    text-align: center;
                }	
                #div_publicidad {
                    position: absolute;
                    top: 230px;
                    width:100%;
                    z-index:3;
                }
                .img_publicidad{
                    width: 784px;
                    height: 884px;
                }
                /*FIN PUBLICIDAD*/
                /*INICIO CALIFICACION*/
                #div_contenido { /*para los botones*/
                    position: absolute;
                    top: 150px;
                    width:100%;
                    z-index:3;
                }
                .td_boton{
                    padding-bottom: 20px;
                }
                .boton_calificacion1{
                    color:#fff;
                    font-weight:bold;
                    font-size: 45pt;
                    width: 550px;
                    height: 155px;
                }
            }

            /*horizontal*/
            @media only screen and (min-width:700px) {
                #div_prueba {
                    position: absolute;
                    top: 5px;
                    left: 0px;
                    width: 100%;
                    z-index:3;
                    text-align: center;
                }
                #div_foto {
                    position: absolute;
                    width: 100%;
                    top: 100px;
                    z-index:3;
                }
                #div_numero_grande {
                    position: absolute;
                    width: 100%;
                    top: 100px;
                    left: 300px;
                    z-index:3;
                }
                #div_nombre {
                    position: absolute;
                    width: 100%;
                    top: 460px;
                    z-index:3;
                }
                /*INICIO PUBLICACION*/
                #div_publicidad222{
                    position: absolute;
                    width:120%;
                    top: 200px;
                    z-index:3;
                    font-size: 80px;
                    text-align: left;
                }	

                #div_publicidad {
                    position: absolute;
                    top: 120px;
                    left: 150px;
                    z-index:3;
                }
                .img_publicidad{
                    width: 384px;
                    height: 248px;
                }
                /*FIN PUBLICIDAD*/
                /*INICIO CALIFICACION*/
                #div_contenido { /*para los botones*/
                    position: absolute;
                    top: 80px;
                    width:100%;
                    z-index:3;
                }
                .td_boton{
                    padding-bottom: 5px;
                }
                .boton_calificacion1{
                    color:#fff;
                    font-weight:bold;
                    font-size: 45pt;
                    width: 550px;
                    height: 95px;
                }
            }

            .nombre {
                font-family: Arial, Helvetica, sans-serif;
                font-size: 38px;
                font-style: normal;
                background-color:transparent;
                border:none;
                text-align:center;
                width: 481px;
            }

            .boton_excelente{
                background-color:transparent;
                border: transparent;		background-image:url("<?php echo Core::getInstancePath(); ?>/public/img/<?php echo $carpeta; ?>/sistema/excelente.png");
                background-size: 100% 100%;
            }
            .boton_muy_bueno{
                background-color:transparent;
                border: transparent;		background-image:url("<?php echo Core::getInstancePath(); ?>/public/img/<?php echo $carpeta; ?>/sistema/muybueno.png");
                background-size: 100% 100%;		
            }
            .boton_bueno{
                background-color:transparent;
                border: transparent;		background-image:url("<?php echo Core::getInstancePath(); ?>/public/img/<?php echo $carpeta; ?>/sistema/bueno.png");
                background-size: 100% 100%;		
            }
            .boton_regular{
                background-color:transparent;
                border: transparent;		background-image:url("<?php echo Core::getInstancePath(); ?>/public/img/<?php echo $carpeta; ?>/sistema/regular.png");
                background-size: 100% 100%;		
            }

            #div_pagina{
                width: 100%;
                height: 100%;
                margin-bottom: 0;
                margin:0;
                position: absolute;
                right: 0;
                top: 0;
            }

        </style>
    </head>
    <body>
        <div id="div_pagina" class="fondo">
            <div class="div_camara">
                <div id="my_camera" style="width:320px; height:240px;"></div>
                <!-- chat -->
                CHAT
                <div id="chat"></div>
            </div>
            <div id="div_fondo" class="fondo">
                <?php echo Tag::image($carpeta . "/sistema/calificacion_fondo_horizontal7.jpg", 'id: img_fondo') ?>
            </div>
            <div id="div_content"> <!-- Aqui se reemplaza segun como cargue-->
                <div id="div_inicio" style="display: inline">
                    <div id="div_prueba" class="texto_3d">MODULO</div>
                    <div id="div_numero_grande" style="text-align: center">
                        <img src="<?php echo Core::getInstancePath(); ?>/public/img/<?php echo $carpeta; ?>/sistema/numeros/<?php echo $numero_modulo; ?>.png" width="320" height="395"/>
                    </div>
                    <div id="div_foto" style="text-align: center">
                        <img src="<?php echo Core::getInstancePath(); ?>/public/img/<?php echo $carpeta; ?>/fotos/<?php echo $foto; ?>" width="310" height="360" />
                    </div>
                    <div id="div_nombre" class="nombre" style="text-align: center"><?php echo $nombre_operador; ?></div>
                </div>
                <div id="div_publicacion" style="display: none">
                    <div id="div_prueba" class="texto_3d">MODULO <?php echo $numero_modulo; ?></div>
                    <div id="div_publicidad" style="text-align: center">
                        <?php echo Tag::image($carpeta . "/publicidad/publicidad.png", 'id: img_publicidad') ?>
                    </div>
                </div>
                <div id="div_calificacion" style="display: none">
                    <div id="div_prueba" class="texto_3d" style="text-align: center">MODULO <?php echo $numero_modulo; ?></div>
                    <div id="div_contenido" style="text-align: center">
                        <table border='0' width='100%'>
                            <tr align='center'>
                                <td class="td_boton"><input name='anular' id='excelente' type='button' value='' class='boton_calificacion1 boton_excelente' title='Calificación Excelente' onclick=calificar('Excelente') ></td>
                            </tr>
                            <tr align='center'>
                                <td class="td_boton"><input name='calificar' id='muy_bueno' type='button' value='' class='boton_calificacion1 boton_muy_bueno' title='Calificación Muy Bueno' onclick=calificar('Muy_Bueno')></td>
                            </tr>
                            <tr align='center'>
                                <td class="td_boton"><input name='atender' id='bueno' type='button' value='' class='boton_calificacion1 boton_bueno' title='Calificación Bueno' onclick=calificar('Bueno')></td>
                            </tr>
                            <tr align='center'>
                                <td class="td_boton"><input name='rellamar' id='regular' type='button' value='' class='boton_calificacion1 boton_regular' title='Calificación Regular' onclick=calificar('Regular')></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>

            <div id="div_publicidad222" class="texto_3d"></div>

            <input type="text" id="url" name="url" value="<?php echo Utils::getKumbiaUrl("calificador/ajax") ?>"/>
            <input type="text" id="ip_calificador" name="ip_calificador" value="<?php echo $ip_calificador; ?>"/>
            <input type="text" id="turno_id" name="turno_id" value=""/>
            <input type="text" id="turno_atendiendo" name="turno_atendiendo" value=""/>
        </div>
<!--        <input type="button" value="enviar" onclick="enviar()"/>-->


        <!-- Configure a few settings and attach camera -->
        <script language="JavaScript">
            Webcam.set({
                image_format: 'jpeg',
                jpeg_quality: 90
            });
            Webcam.attach('#my_camera');

            function take_snapshot() {
                var data_uri = Webcam.snap();
                data = {
                    src: data_uri
                }
                $.ajax({
                    url: $("#url").val(),
                    data: data,
                    type: 'post',
                    success: function(respuesta) {
                        $('#fotoGuardada').attr('src', respuesta).show(500);
                    }
                });
            }
        </script>



        <script>
            try {
                var socket = io.connect("http://<?php echo $servidor_node; ?>");
                $.unblockUI();
            }
            catch (err) {
                alert("No se ha podido conectar con el servidor NODE correctamente.\nIntente nuevamente.\nSi el problema persiste comuníquese con Sistemas.\nCódigo de error: 101");
                $.unblockUI();
            }
            var socket = io.connect("http://<?php echo $servidor_node; ?>");
//            function enviar() {
//                var msg_siguiente = "siguiente|192.168.1.6";
//                socket.emit('send message', msg_siguiente);
//            }
        </script>


        <!-- Code to handle taking the snapshot and displaying it locally -->
        <script language="JavaScript">
            //cargar('cargarInicial');

            window.onresize = Resize1;
            Resize1();
            function Resize1() {
                var ancho_pagina = $(document).width();
                var alto_pagina = $(document).height();
                //alert(alto_pagina);
                $("#img_fondo").width(ancho_pagina);
                $("#img_fondo").height(alto_pagina);
            }

            jQuery(function($) {
                var socket = io.connect("http://<?php echo $servidor_node; ?>");
                var $chat = $('#chat');
                socket.on('new message', function(data) {
                    //$("#div_publicidad222").prop('display',false);
                    $("#div_publicidad222").css("display", "none");

                    $chat.text(data);   //envio a chat el msg
                    var smg_siguiente = $("#chat").text();
                    var res = smg_siguiente.split("|");

                    if (res.length >= 4) {  //si es >=5 dio siguiente
                        var ip = res[3].split(":");
                        //alert(ip[1]);
                        if (ip[1] == $("#ip_calificador").val()) {

                            //--busco que opcion sigue
                            var op = res[4].split(":");
                            //alert(op[1]);
                            if (op[0] == 'op' & op[1] == 'siguiente') {
                                var turno = res[5].split(":");
                                //--muestra la pantalla de publicidad
                                $("#turno_id").val(turno[1]);
                                //cargar('cargarPublicacion');
                                //$("#div_publicidad222").css("display", "inline");
                                t = res[0].split(":");
                                t2 = t[1].split("/");
                                $("#div_publicidad222").html("Turno " + t2[0] + t2[1]);
                                $("#div_publicidad222").val(t[1]);
                            }
                            if (op[0] == 'op' & op[1] == 'atender') {
                                $("#div_inicio").css("display", "none");
                                $("#div_publicacion").css("display", "inline");
                                $("#div_calificacion").css("display", "none");
                                //--muestra la pantalla de publicidad
                                //cargar('cargarPublicacion');
                                $("#div_publicidad222").css("display", "inline");
                                t = $("#div_publicidad222").val();
                                t2 = t.split("/");
                                $("#div_publicidad222").html("Turno " + t2[0] + t2[1]);
                            }
                            if (op[0] == 'op' & op[1] == 'calificar') {
                                $("#div_inicio").css("display", "none");
                                $("#div_publicacion").css("display", "none");
                                $("#div_calificacion").css("display", "inline");
                                //alert("cargar pantalla calificacion")
//                            tipo_calificacion = "B";
//                            if (tipo_calificacion == "A") {
//                                //$("#valor1").focus();
//                            } else if (tipo_calificacion == "B") {  //Pantalla Simple
                                //cargar('cargarCalificacion');
//                            } else if (tipo_calificacion == "C") {   //Pantalla Matriz
//                                cargar('cargarCalificacionMatriz')
//                            }
                            }
                        }

                    }
                });
            });

            var calificado = 0;
            function calificar(calificacion) {
                //alert("Calificar. Ip_calificador:" + $("#ip_calificador").val() + " calif:" + calificacion + " turno_id:" + $("#turno_id").val());

                //var msg_siguiente = "siguiente|" + $("#ip_calificador").val();
                //socket.emit('send message', msg_siguiente);

                var data_uri = Webcam.snap();

                data = {
                    turno_id: $("#turno_id").val(),
                    calificacion: calificacion,
                    src: data_uri
                }

                if (calificacion == "Muy_Bueno")
                    calificacion = "Muy Bueno";

                $.post("<?php echo Utils::getKumbiaUrl("calificador/subir_foto") ?>",
                        data
                        , function(json) {
                            exito = json.exito;
                            if (exito == 1) {
                                //alert(1);
                                var msg_siguiente = "siguiente|" + $("#ip_calificador").val() + "|" + calificacion;
                                socket.emit('send message', msg_siguiente);
                                //cargar('cargarInicial');
                                $("#div_inicio").css("display", "inline");
                                $("#div_publicacion").css("display", "none");
                                $("#div_calificacion").css("display", "none");

                            }
                        }, "json");

            }

            function regresar() {
                if (cont == tiempo) {
                    terminaTurno();
                }
                cont++;
            }
            //setInterval("regresar()", 1000);
        </script>
    </body>
</html>
