<div>
    <table border="1px"  align="center">
        <!--<tr>
            <td>
                <b><?php //echo Tag::radioField("radio_modelos",array ('A'=>'Pantalla 1')) ?></b>
            </td>
            <td>
                <b><?php //echo Tag::radioField("radio_modelos",array ('B'=>'Pantalla 2')) ?></b>
            </td>
        </tr>
        <tr>
            <td>
                <b><?php //echo Tag::image('Dibujo1.JPG', 'alt: Imagen') ?></b>
            </td>
            <td>
                <b><?php //echo Tag::image('Dibujo2.JPG', 'alt: Imagen') ?></b>
            </td>

        </tr>-->
        <tr>
            <td>
                <b><?php echo Tag::radioField("radio_pantalla",array ('A'=>'Pantalla')) ?></b>
            </td>
    </table>
</div>