<style type="text/css">
    .parametros{background-color: #fff; color:#000; padding:10px; top:130px; left:350px; position:absolute}

    th{
        background-color:#136FB3;
        color:#fff;
    }
    .cabecera{
        background-color:#86C5F2;
    }
</style>
<fieldset class='ui-corner-all ui-widget-content'>
    <legend><b>Seleccione el horario</b></legend>
    <table>
    <?php
    $horario= new Horario();
    $buscaHorario=$horario->find();
    foreach($buscaHorario as $result) {
        $horario_id=$result->getId();
        echo "<tr>";
        echo "<td>".Tag::radioField("radio_horario",array ($result->getId()=>$result->getNombreHorario()))."</td>";
        echo "<td>".Tag::button("Vista previa", "onclick: ver_div_horario($horario_id)")."</td>";
        echo "</tr>";
    //echo "<td>".Tag::checkboxField("chk_dia_semana[]", "value: $key","checked: ").$valor."</td>";
    }
    ?>
        </table>
    <div id="div_vista_horario" class="parametros">
    </div>

</fieldset>

<script>
    function ver_div_horario(horario_id){
        $.post("<?php echo Utils::getKumbiaUrl("horario/verHorario")?>", {
            horario_id: horario_id
        }
        ,function(data){
            document.getElementById("div_vista_horario").innerHTML = data;
        },'ajax');
    }
//    $("#radio_horario").click(function(){
//        $.post("<?php echo Utils::getKumbiaUrl("horario/verHorario")?>", {
//            horario_id: horario_id
//        }
//        ,function(data){
//            document.getElementById("div_vista_horario").innerHTML = data;
//        },'ajax');
//    });
</script>