<div align='center'>
    <table width="100%">
        <tr>
            <td valign="top">
                <div style='padding:10px'>
                    <table align="center" width="100%">
                        <?php
                        $servicio=new Servicio();
                        $conditions="estado=1";
                        $attributes=$servicio->find("conditions: $conditions");
                        ?>
                        <tr>
                            <td>
                                <div style='padding:10px'>
                                    <b>Seleccione los servicios:</b>
                                </div>
                                <?php if(count($attributes)>0) { ?>
                                <table border="1px"  align="center" width="70%">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Nombre del Servicio</th>
                                            <th>Asignar</th>
                                        </tr>
                                    </thead>
                                        <?php
                                        foreach($attributes as $attribute) {
                                            $idservicio=$attribute->getId();
                                            print "<td>".$attribute->getId()."</td>";
                                            print "<td>".$attribute->getNombre()."</td>";
                                            print "<td align='center'>".Tag::checkboxField("chkservicio[]", "value: $idservicio")."</td>";
                                            print "</tr>";
                                        }
                                        ?>
                                </table>
                                <?php } ?>
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
    </table>
    <?php echo Tag::endForm() ?>
</div>
