<div>
    <table border="1px"  align="center">
        <!--<tr>
            <td>
                <b><?php //echo Tag::radioField("radio_modelos",array ('A'=>'Pantalla 1')) ?></b>
            </td>
            <td>
                <b><?php //echo Tag::radioField("radio_modelos",array ('B'=>'Pantalla 2')) ?></b>
            </td>
        </tr>
        <tr>
            <td>
                <b><?php //echo Tag::image('Dibujo1.JPG', 'alt: Imagen') ?></b>
            </td>
            <td>
                <b><?php //echo Tag::image('Dibujo2.JPG', 'alt: Imagen') ?></b>
            </td>

        </tr>-->
        <tr>
            <td>
                <b><?php echo Tag::radioField("radio_modelos",array ('C'=>'Pantalla 3')) ?></b>
            </td>
            <td>
                <b><?php echo Tag::radioField("radio_modelos",array ('D'=>'Pantalla 4')) ?></b>
            </td>
        <tr>
            <td>
                <b><?php echo Tag::image('Dibujo3.JPG', 'alt: Imagen') ?></b>
            </td>
            <td>
                <b><?php echo Tag::image('Dibujo4.JPG', 'alt: Imagen') ?></b>
            </td>
        </tr>
    </table>
</div>