<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('grupo_menu/guardar');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Grupo Menu</legend>
		<p><label class='labelform' ><span for='grupo_id'><b>Grupo</b>:</span></label><?php echo Tag::select("grupo_id", $Grupo->find("order: id"), "using: id,id", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
		<p><label class='labelform' ><span for='menu_id'><b>Menu</b>:</span></label><?php echo Tag::select("menu_id", $Menu->find("order: id"), "using: id,id", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
		<p><label class='labelform' ><span for='permitir_acceso'><b>Permitir Acceso</b>:</span></label><?php echo Tag::textField("permitir_acceso", "size: 1", "maxlength: 1","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='hora_inicio'><b>Hora Inicio</b>:</span></label><?php echo Tag::textField("hora_inicio", "size: 0", "maxlength: 0","class: ") ?></p>
		<p><label class='labelform' ><span for='hora_fin'><b>Hora Fin</b>:</span></label><?php echo Tag::textField("hora_fin", "size: 0", "maxlength: 0","class: ") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
