<fieldset class='ui-corner-all ui-widget-content'>
    <legend>Módulos</legend>
    <p><label class='labelform' ><span for='modulo_operadores'><b>Módulo Atención con Tickets</b>:</span></label><?php echo Tag::checkboxField("modulo_operadores");?></p>
    <p><label class='labelform' ><span for='modulo_cajas'><b>Módulo Atención sin Tickets</b>:</span></label><?php echo Tag::checkboxField("modulo_cajas");?></p>
</fieldset>
