<!--
FUNCIONA MUY BIEN
ES PARA EMITIR TURNOS NORMALES
-->


<div id="div_botones" align="center">
    <?php
//    if ($total_servicios <= 6)
//        echo "<table width='50%' id='tbl_1' align='center'>";
//    else
//        echo "<table width='100%' id='tbl_1' align='center'>";
    ?>
    <table width = "100%" align = "center" id='tbl_1'>
        <?php
        $habilitar_t_e = 0;   //habilitar vista de turnos en espera
        //inicio buscar ubicaci?n
        //SELECT nombre_ubicacion FROM servicio s, ubicacion u WHERE u.id=s.ubicacion_id GROUP BY nombre_ubicacion;
        $db = DbBase::rawConnect();

        //echo $i;
        //echo $numero[4];

        $result2 = $db->query("SELECT DISTINCT(u.id),u.nombre_ubicacion FROM dispensadorservicio ds,servicio s,ubicacion u WHERE ds.servicio_id=s.id AND s.ubicacion_id=u.id AND ds.dispensador_id=$id_dispensador");

        $contador=1;

        while ($row = $db->fetchArray($result2)) {
            
            $id_ubicacion = $row[0];
            $ubicacion = $row[1];


        $i=0;
        $gs=$db->query("SELECT DISTINCT(g.id),g.nombre_grupo_servicio FROM gruposervicio g,servicio s,ubicacion u WHERE g.id=s.gruposervicio_id AND u.id=s.ubicacion_id AND ubicacion_id=$id_ubicacion");
         while ($row = $db->fetchArray($gs)) {
            $codigos[$i]=$row[0];
            $nombreS[$i]=$row[1];

            //echo $codigos[$i];
            //echo "-";
            
            //echo $codigos[$i];
            $i++;
            //echo $i;

        }

        for ($j=1; $j <= $i; $j++) { 

            $gs1=$db->query("SELECT COUNT(*) FROM servicio WHERE gruposervicio_id=$codigos[0]");
             while ($row1 = $db->fetchArray($gs1)) {
            $numero[$j]=$row1[0];
            //$i++;
            //echo $row1[0];
            }
            //echo $j;
        }

                    echo "<tr><td width=50% align='center' ><center>";
                    echo "<table>";
                    echo "<tr><td align='center'>";
                    echo "<label style='color:white;'>".$nombreS[0]."</label>";
                    echo "</td></tr>";
                    echo "</table>";
                    echo "</center></td></tr>";




            //Inicio por ubicaci?n
            $sql = new ActiveRecordJoin(array("entities" => array("Servicio", "Dispensador", "Dispensadorservicio", "Ubicacion"),
                        "fields" => array(
                            "{#Servicio}.nombre",
                            "{#Servicio}.estado",
                            "{#Servicio}.id",
                            "{#Servicio}.letra",
                            "{#Servicio}.letra_alias",
                            "{#Servicio}.atencion_preferencial",
                            //"{#Servicio}.estilo_letra",
                            "{#Servicio}.gruposervicio_id",
                            "{#Ubicacion}.nombre_ubicacion"
                        //"{#Servicio}.prioridad"
                        ),
                        //"groupFields" => array("{#Servicio}.estilo_letra"),
                        "order" => "gruposervicio_id asc,estilo_letra, nombre asc",
                        "conditions" => "{#Dispensadorservicio}.dispensador_id=$id_dispensador AND {#Ubicacion}.id=$id_ubicacion")
            );



            $cont = 0;
            $total_filas = 0;
            foreach ($sql->getResultSet() as $result1) {
                $total_filas+=1;
            }

            if ($total_filas != 0)
                echo "<center><label size=60 style='color: white; font-size: 12px; border-style: none; background-color:transparent'>" . $ubicacion . "</label></center>";
                    

            

            //echo "TOTAL SERVICIOS:".$total_servicios; die();
//            if ($total_servicios <= 6)
            echo "<table width='100%' align='center'>";



//            else
//                echo "<table width='50%' align='center'>";
            $contadorServicio=1;
            $contador=0;
            $nombreC=1;



            foreach ($sql->getResultSet() as $result) {

                $numeroGrupo=$numero[$contadorServicio];
                //$color = "#" . $result->getEstiloLetra();
                $nombre = $result->getNombre();
                $nombre_ubicacion = $result->getNombreUbicacion();
                $letra = $result->getLetra();
                $letra_alias = $result->getLetraAlias();
                $value = $result->getLetra() . ". " . $result->getNombre();
                $atencion_preferencial = $result->getAtencionPreferencial();

                $prioridad = 0;


                if ($total_servicios <= 3) {

                    echo "<tr><td width=50% align='center' style='padding:2px'><center>";
                    echo "<table>";
                    echo "<tr><td align='center'>";

                    $value = $result->getLetraAlias() . ". " . $result->getNombre();
                        echo '<input name="btn_servicio" type="button" value="' . $value . '" class="boton_dispensador_preferencial"  onclick="emitir_turno(' . $result->getId() . "," . $result->getGruposervicioId() . "," . "'$letra_alias'" . ",'$nombre'" . ",'$nombre_ubicacion'" . ",'$prioridad'" . ",'$letra_alias'" . ')">';


/*
                    if ($atencion_preferencial == 2) {
                        //if ($atencion_preferencial == 1) {
                        $prioridad = 1;
                        $value = $result->getLetraAlias() . ". " . $result->getNombre();
                        echo '<input name="btn_servicio" type="button" value="' . $value . '" class="boton_dispensador_preferencial"  onclick="emitir_turno(' . $result->getId() . "," . $result->getGruposervicioId() . "," . "'$letra_alias'" . ",'$nombre'" . ",'$nombre_ubicacion'" . ",'$prioridad'" . ",'$letra_alias'" . ')">';
                        //}
                    } else {
                        echo '<input name="btn_servicio" type="button" value="' . $value . '" class="boton_dispensador"  onclick="emitir_turno(' . $result->getId() . "," . $result->getGruposervicioId() . "," . "'$letra'" . ",'$nombre'" . ",'$nombre_ubicacion'" . ",'$prioridad'" . ",'$letra_alias'" . ')">';
                        if ($habilitar_t_e == 1)
                            echo '<input name="txt_servicio_' . $result->getId() . '" id="txt_servicio_' . $result->getId() . '" type="text" value="" style="color:#000; background:#fff; width: 22px; text-align: right" readonly="readonly">';
                        if ($atencion_preferencial == 1) {
                            $prioridad = 1;
                            $value = $result->getLetraAlias() . ". " . $result->getNombre();
                            echo '<input name="btn_servicio" type="button" value="' . $value . '" class="boton_dispensador_preferencial"  onclick="emitir_turno(' . $result->getId() . "," . $result->getGruposervicioId() . "," . "'$letra_alias'" . ",'$nombre'" . ",'$nombre_ubicacion'" . ",'$prioridad'" . ",'$letra_alias'" . ')">';
                        }
                    }

                    */


                    echo "</td></tr>";
                    echo "</table>";
                    echo "</center></td></tr>";
                } else {
                   
                    $cont = $cont + 1;
                     $contador = $contador + 1;


                    if ($contador % 2 <> 0 || $contador>$numeroGrupo) {
                    //if ($contador>$numeroGrupo) {

                         // if ($contador==1) {
                                    //echo "<label style='color:white;'>".$nombreS[$nombreC++]."</label>";
                                    //echo $nombreS[$nombreC++];
                            //echo "<tr><td width=50% align='center' style='padding:2px'><center>";
                                    //$contadorServicio++;

                                    //$contador=0;
                            # code...
                           // }

                        if ($contador>$numeroGrupo) {
                           


                            echo "<tr><td width=50% align='center' style='padding:2px'><center>";
                            //contadorServicio++;

                            //$contador=1;
                            # code...
                        }

                        if ($result->getEstado() == 1) {




                            if ($contador>$numeroGrupo ) {
                                    echo "<label style='color:white;'>".$nombreS[$nombreC++]."</label>";
                                    //echo $nombreS[$nombreC++];
                            //echo "<tr><td width=50% align='center' style='padding:2px'><center>";
                                    $contadorServicio++;

                                    $contador=1;
                            # code...
                            }else{

                           echo "<td align='center' style='padding:4px'><center>";
                        }


                            echo "<table>";

                            echo "<tr><td align='center'>";

                            if ($atencion_preferencial == 2) {
                                //if ($atencion_preferencial == 1) {
                                $prioridad = 1;
                                $value = $result->getLetraAlias() . ". " . $result->getNombre();
                                echo '<input name="btn_servicio" type="button" value="' . $value . '" class="boton_dispensador_preferencial_peque"  onclick="emitir_turno(' . $result->getId() . "," . $result->getGruposervicioId() . "," . "'$letra_alias'" . ",'$nombre'" . ",'$nombre_ubicacion'" . ",'$prioridad'" . ",'$letra_alias'" . ')">';
                                //}
                            } else {
                                echo '<input name="btn_servicio" type="button" value="' . $value . '" class="boton_dispensador_peque"  onclick="emitir_turno(' . $result->getId() . "," . $result->getGruposervicioId() . "," . "'$letra'" . ",'$nombre'" . ",'$nombre_ubicacion'" . ",'$prioridad'" . ",'$letra_alias'" . ')">';

                                if ($habilitar_t_e == 1)
                                    echo '<input name="txt_servicio_' . $result->getId() . '" id="txt_servicio_' . $result->getId() . '" type="text" value="" style="color:#000; background:#fff; width: 22px; text-align: right" readonly="readonly">';

                                /*
                                if ($atencion_preferencial == 1) {
                                    $prioridad = 1;
                                    $value = $result->getLetraAlias() . ". " . $result->getNombre();
                                    echo '<input name="btn_servicio" type="button" value="' . $value . '" class="boton_dispensador_preferencial_peque"  onclick="emitir_turno(' . $result->getId() . "," . $result->getGruposervicioId() . "," . "'$letra_alias'" . ",'$nombre'" . ",'$nombre_ubicacion'" . ",'$prioridad'" . ",'$letra_alias'" . ')">';
                                }

                                */
                            }

                            echo "</td></tr>";

                            echo "</table>";

                            echo "</center></td>";
                        }
                    } else {
                                //if ($contador>$numeroGrupo) {$contadorServicio++;$contador=1;}
                        if ($result->getEstado() == 1) {
                            //echo "<tr><td width=50% align='center' style='padding:2px'><center>";

                            echo "<td align='center' style='padding:4px'><center>";


                            echo "<table id='tbl_turno'>";

                            echo "<tr><td align='center'>";
                            if ($atencion_preferencial == 2) {
                                $prioridad = 1;
                                $value = $result->getLetraAlias() . ". " . $result->getNombre();
                                echo '<input name="btn_servicio" type="button" value="' . $value . '" class="boton_dispensador_preferencial_peque"  onclick="emitir_turno(' . $result->getId() . "," . $result->getGruposervicioId() . "," . "'$letra_alias'" . ",'$nombre'" . ",'$nombre_ubicacion'" . ",'$prioridad'" . ",'$letra_alias'" . ')">';
                            } else {
                                echo '<input name="btn_servicio" type="button" value="' . $value . '" class="boton_dispensador_peque"  onclick="emitir_turno(' . $result->getId() . "," . $result->getGruposervicioId() . "," . "'$letra'" . ",'$nombre'" . ",'$nombre_ubicacion'" . ",'$prioridad'" . ",'$letra_alias'" . ')">';

                                if ($habilitar_t_e == 1)
                                    echo '<input name="txt_servicio_' . $result->getId() . '" id="txt_servicio_' . $result->getId() . '" type="text" value="" style="color:#000; background:#fff; width: 22px; text-align: right" readonly="readonly">';

                                /*
                                if ($atencion_preferencial == 1) {
                                    $prioridad = 1;
                                    $value = $result->getLetraAlias() . ". " . $result->getNombre();
                                    echo '<input name="btn_servicio" type="button" value="' . $value . '" class="boton_dispensador_preferencial_peque"  onclick="emitir_turno(' . $result->getId() . "," . $result->getGruposervicioId() . "," . "'$letra_alias'" . ",'$nombre'" . ",'$nombre_ubicacion'" . ",'$prioridad'" . ",'$letra_alias'" . ')">';
                                }

                                */
                            }
                            echo "</td></tr>";

                            echo "</table>";

                            echo "</center></td></tr>";
                        }
                    }
                }
            }
            echo "</table>";
        }
        ?>
        <center><br/>
        </center>
    </table>
</div>






