<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('estilopantallaoperador/guardar');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Estilopantallaoperador</legend>
		<p><label class='labelform' ><span for='contenido'><b>Contenido</b>:</span></label><?php echo Tag::textArea("contenido","cols: 90","rows: 15");?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
