<div id='mainContent'>

    <?php
    //echo View::getContent();
    //echo Tag::form('preguntas/guardar');
    View::renderPartial("toolbarform");
    echo Tag::form("preguntas/guardar");
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Preguntas</legend>
        <p><label class='labelform' ><span for='nom_pregunta'><b>Pregunta</b>:</span></label><?php echo Tag::textField("nom_pregunta", "size: 60", "maxlength: 100","class: ") ?></p>
        <p><label class='labelform' ><span for='publicar'><b>Publicar</b>:</span></label><?php echo Tag::checkboxField("publicar");?></p>
        <p><label class='labelform' ><span for='orden'><b>Orden</b>:</span></label><?php echo Tag::numericField("orden", "size: 2", "maxlength: 2","class:  numeric") ?></p>
    </fieldset>
    <!--<div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
    </div>-->
    <?php echo Tag::endForm(); ?>

</div>
