<div id="div_reporte_servicio">
<div class="ocultar">
    <table align="center">
        <tr>
            <td>
                <input id="chk_barrasServicio" type="checkbox" /><label style="color:#3366FF; font-size:12px; font-weight:bold">BARRAS</label>
                <input id="chk_pastelServicio" type="checkbox"/><label style="color:#3366FF; font-size:12px; font-weight:bold">PASTEL</label>
            </td>
            <td>
                <?php
                //$fun = new Funciones();
                //echo $fun->imprimir();
                ?>
            </td>
        </tr>
    </table>
</div>
<table style="height: 100%; width: 100%; background-color: #E5F1F4"  align="center">
    <tr><th colspan="2"> <div id="div_cabeceraServicio" style="height: 100%; width: 100%"></div></th></tr>
    <tr>
        <td>
            <table style="height: 100%;width: 100%" align="center">
                <tr>
                    <td>
                        <div id="div_ServicioBarras" style="width: 100%; height: 100%" align="center">
                        </div>
                    </td>
                    <td>
                        <div id="div_Serviciopastel" style="width: 100%; height: 100%" align="center"></div>
                        <div  id="div_servicio" align="center"></div>
                    </td>
                <tr>
                    <td colspan="2">
                        <div  id="div_serviciotabla" align="center">

                        </div>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
    </div>
