<div id='mainContent'>
    <?php
    //View::renderPartial('toolbarformrefresh');
    ?>
    <table class='tablesorter' id='Exportar_a_Excel' border="1">
        <thead>
            <tr>
                <th>Usuario</th>
                <th>Estado Login</th>
                <th>Módulo</th>
                <th>Ubicación</th>
                <th>Pausado</th>
                <th>Tipo Pausa</th>
                <th>Hora Inicio</th>
                <th>Hora Fin</th>
                <th>Tiempo Transcurrido<br>en pausa</th>
            </tr>
        </thead>
        <tbody>
            <?php
            //busco el estado actual (del dia actual) de los usuarios
            $db = DbBase::rawConnect();
            $html="";
            $result = $db->query("SELECT u.id AS usuario_id, u.nombres, u.login, c.id AS caja_id, c.numero_caja, ubi.nombre_ubicacion, p.nombre_pausa, cp.estado, cp.fecha_inicio, cp.hora_inicio, cp.fecha_fin, cp.hora_fin,
                CASE cp.estado
                WHEN 1 THEN SEC_TO_TIME(TIME_TO_SEC(CURTIME()) - TIME_TO_SEC(hora_inicio))
                ELSE  SEC_TO_TIME(TIME_TO_SEC(hora_fin) - TIME_TO_SEC(hora_inicio))
                END AS tiempo_transcurrido
                FROM usuario u
                JOIN grupousuario gu ON gu.usuario_id=u.id
                LEFT JOIN caja c ON c.usuario_actual=u.id
                left join ubicacion ubi on ubi.id=c.ubicacion_id
                LEFT JOIN caja_pausas cp ON (SELECT id FROM caja_pausas WHERE usuario_id=u.id AND fecha_inicio= CURDATE() ORDER BY id DESC LIMIT 1)=cp.id 
                left join pausas p on p.id=cp.pausas_id
                WHERE grupo_id IN (5,7)");
            while ($row = $db->fetchArray($result)) {
                $login="<font color='red'><b>Inactivo</b></font>";
                if($row['login']==1)
                    $login="<font color='green'><b>Activo</b></font>";
                $pausado="<font color=''><b>NO</b></font>";
                if($row['estado']==1)
                    $pausado="<font color='green'><b>SI</b></font>";
                $html.="<tr>";
                $html.="<td align='center'> {$row['nombres']} </td>";
                $html.="<td align='center'> $login </td>";
                $html.="<td align='center'> {$row['numero_caja']} </td>";
                $html.="<td align='center'> {$row['nombre_ubicacion']} </td>";
                $html.="<td align='center'>  $pausado</td>";
                $html.="<td align='center'> {$row['nombre_pausa']} </td>";
                $html.="<td align='center'> {$row['hora_inicio']} </td>";
                $html.="<td align='center'> {$row['hora_fin']} </td>";
                $html.="<td align='center'> {$row['tiempo_transcurrido']} </td>";
                $html.="</tr>";
            }
            echo $html;
            ?>
        </tbody>
    </table>
</div>
