<!--
Configurar impresora
-->

<fieldset class="ui-corner-all ui-widget-content">
    <legend>Datos impresora</legend>
    <p><label class='labelform' ><span for='ubicacion_impresora'><b>Ubicación Impresora</b>:</span></label><?php echo Tag::textField("ubicacion_impresora", "size: 40", "maxlength: 100","class: required") ?></p>
    <p><label class='labelform' ><span for='nombre_impresora'><b>Nombre Impresora</b>:</span></label><?php echo Tag::textField("nombre_impresora", "size: 40", "maxlength: 100","class: required") ?></p>
</fieldset>