<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('modulo/guardar/true');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Modulo</legend>
		<p><label class='labelform' ><span for='nombre'><b>Nombre</b>:</span></label><?php echo Tag::textField("nombre", "size: 50", "maxlength: 50","class:  required") ?></p>
		<p><label class='labelform' ><span for='ruta'><b>Ruta</b>:</span></label><?php echo Tag::textField("ruta", "size: 50", "maxlength: 255","class: ") ?></p>
		<p><label class='labelform' ><span for='tipo'><b>Tipo</b>:</span></label><?php echo Tag::selectStatic("tipo", $tipo, "useDummy: yes", "class: required") ?></p>
                <p><label class='labelform' ><span for='estado'><b>Estado</b>:</span></label><?php echo Tag::selectStatic("estado", $estado, "useDummy: yes");?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
<script>
    $("#nombre").blur(function() {
        $(this).val($(this).val().toUpperCase());
    });
    $("#ruta").blur(function() {
        $(this).val($(this).val().toLowerCase());
    });
</script>