<script type="text/javascript" src="../../../js/jscolor.js"></script>
<script>
    function validar_letras(){
        document.getElementById('letra').value = document.getElementById('letra').value.toUpperCase();
        var letra1 = document.getElementById('letra').value;
        $.post("<?php echo Utils::getKumbiaUrl("servicio/buscarletra/" . $id) ?>", {
            letra:  letra1
        },function(respuesta){
            if(respuesta > 0){ 
                document.getElementById("mensaje_letra").innerHTML = 'La letra ' + letra1 + ' ya esta registrada';
                document.getElementById('letra').value='';
            }
            else{
					
                document.getElementById("mensaje_letra").innerHTML = '';
            }
        },'ajax');
    }
	
    function validar_letras_alias(){
        document.getElementById('letra_alias').value = document.getElementById('letra_alias').value.toUpperCase();
        var letra2 = document.getElementById('letra_alias').value;
        $.post("<?php echo Utils::getKumbiaUrl("servicio/buscarletraalias/" . $id) ?>", {
            letra:  letra2
        },function(respuesta){
            if(respuesta > 0){ 
                document.getElementById("mensaje_letra_alias").innerHTML = 'La letra ' + letra2 + ' ya esta registrada';
                document.getElementById('letra_alias').value='';
            }
            else{
                document.getElementById("mensaje_letra_alias").innerHTML = '';
            }
        },'ajax');
    }	
</script>
<div id='mainContent'>

    <?php
    View::renderPartial("toolbarform");
    echo Tag::form("servicio/guardar/true");
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Servicio</legend>
        <p><label class='labelform' style="width:200px"><span for='nombre'><b>Nombre</b>:</span></label><?php echo Tag::textField("nombre", "size: 40", "maxlength: 50", "class: required") ?></p>
        <p><label class='labelform' style="width:200px"><span for='descripcion'><b>Descripción</b>:</span></label><?php echo Tag::textfield("descripcion", "size: 40", "maxlength: 150", "class: ") ?></p>
        <p><label class='labelform' style="width:200px"><span for='letra'><b>Letra</b>:</span></label><?php echo Tag::textfield("letra", "size: 1", "maxlength: 1", "class: required", "onkeyup: validar_letras()") ?>
        <div id="mensaje_letra" style="color:red">
        </div>
        </p>

        <p><label class='labelform' style="width:200px"><span for='estado'><b>Estado (Activo/Inactivo)</b>:</span></label><?php echo Tag::checkboxField("estado"); ?></p>


        <?php
        //INICIO grupo del servicio
        $gruposervicio = array();
        $condicion = "{#Servicio}.id = $id";
        $query = new ActiveRecordJoin(array(
                    "entities" => array("Gruposervicio", "Servicio"),
                    "fields" => array(
                        "{#Gruposervicio}.id",
                        "{#Gruposervicio}.nombre_grupo_servicio"),
                    "conditions" => $condicion
                ));
        foreach ($query->getResultSet() as $result) {
            $listagruposervicio[$result->getId()] = $result->getNombreGrupoServicio();
        }

        $gruposervicio = new Gruposervicio();
        $buscaGruposervicio = $gruposervicio->find();
        foreach ($buscaGruposervicio as $result) {
            $listagruposervicio[$result->getId()] = $result->getNombreGrupoServicio();
        }
        ?>

        <p><label class='labelform' style="width:200px"><span for='ubicacion'><b>Grupo del Servicio</b>:</span></label><?php echo Tag::selectStatic("gruposervicio", $listagruposervicio, "class:  required") ?></p>

        <?php
        //INICIO ubicacion del servicio
        $listaubicacion = array();
        $condicion = "{#Servicio}.id = $id";
        $query = new ActiveRecordJoin(array(
                    "entities" => array("Ubicacion", "Servicio"),
                    "fields" => array(
                        "{#Ubicacion}.id",
                        "{#Ubicacion}.nombre_ubicacion"),
                    "conditions" => $condicion
                ));
        foreach ($query->getResultSet() as $result) {
            $listaubicacion[$result->getId()] = $result->getNombreUbicacion();
        }

        $ubicacion = new Ubicacion();
        $buscaUbicacion = $ubicacion->find();

        foreach ($buscaUbicacion as $result) {
            $listaubicacion[$result->getId()] = $result->getNombreUbicacion();
        }
        ?>

        <p><label class='labelform' style="width:200px"><span for='ubicacion'><b>Ubicación</b>:</span></label><?php echo Tag::selectStatic("ubicacion", $listaubicacion, "class:  required") ?></p>
        <p><label class='labelform' style="width:200px"><span for='tiempo_maximo'><b>Tiempo Máximo de atención</b>:</span></label><?php echo Tag::textField("tiempo_maximo", "size: 5", "maxlength: 10", "class: ") ?>&nbsp;&nbsp;
            <b>Sugerido en base a datos registrados:</b><?php echo Tag::textField("tiempo_maximo_sugerido", "size: 5", "maxlength: 10", "class: ", "readonly: readonly") ?></p>
        <p><label class='labelform' style="width:200px"><span for='nombre'><b>Color de letra en dispensador</b>:</span></label><?php echo Tag::textField("color", "size: 10", "maxlength: 10", "class: color") ?></p>

        <p><label class='labelform' style="width:200px"><span for='atencion_preferencial'><b>Habilitar Atención Preferencial</b>:</span></label><?php echo Tag::checkboxField("atencion_preferencial"); ?></p>
        <p><label class='labelform' style="width:200px"><span for='letra_alias'><b>Letra si es Turno Preferencial</b>:</span></label><?php echo Tag::textField("letra_alias", "size: 1", "maxlength: 1", "class: ", "onkeyup: validar_letras_alias()") ?>
        <p><label class='labelform' style="width:200px"><span for='mostrar_atencion_normal'><b>No Mostrar Atención Normal</b>:</span></label><?php echo Tag::checkboxField("mostrar_atencion_normal"); ?></p>
        <div id="mensaje_letra_alias" style="color:red">
        </div>		
        </p>
        <script>
            if(document.getElementById('letra_alias').value == ' ')
                document.getElementById('letra_alias').value = '';
        </script>
    </fieldset>
    <!--<div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
        <input id="Inicializar" type="button" value="Inicializar"/>
    </div>-->
    <?php echo Tag::endForm(); ?>
</div>

<script>
    $("#tiempo_maximo").timepicker({ timeFormat: 'hh:mm:ss' });
</script>
