<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('sincturnos/guardar/true');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Sincturnos</legend>
		<p><label class='labelform' ><span for='id_referencia'><b>Id Referencia</b>:</span></label><?php echo Tag::textField("id_referencia", "size: 11", "maxlength: 11","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='nombre_sucursal'><b>Nombre Sucursal</b>:</span></label><?php echo Tag::textField("nombre_sucursal", "size: 200", "maxlength: 200","class: ") ?></p>
		<p><label class='labelform' ><span for='base_datos'><b>Base Datos</b>:</span></label><?php echo Tag::textField("base_datos", "size: 50", "maxlength: 50","class: ") ?></p>
		<p><label class='labelform' ><span for='usuario'><b>Usuario</b>:</span></label><?php echo Tag::textField("usuario", "size: 50", "maxlength: 50","class: ") ?></p>
		<p><label class='labelform' ><span for='nombre_servicio'><b>Nombre Servicio</b>:</span></label><?php echo Tag::textField("nombre_servicio", "size: 50", "maxlength: 50","class: ") ?></p>
		<p><label class='labelform' ><span for='numero_turno'><b>Numero Turno</b>:</span></label><?php echo Tag::textField("numero_turno", "size: 5", "maxlength: 5","class: ") ?></p>
		<p><label class='labelform' ><span for='fecha_emision'><b>Fecha Emision</b>:</span></label><?php echo Tag::textField("fecha_emision", "size: 0", "maxlength: 0","class:  dateISO") ?></p>
		<p><label class='labelform' ><span for='hora_emision'><b>Hora Emision</b>:</span></label><?php echo Tag::textField("hora_emision", "size: 0", "maxlength: 0","class: ") ?></p>
		<p><label class='labelform' ><span for='fecha_inicio_atencion'><b>Fecha Inicio Atencion</b>:</span></label><?php echo Tag::textField("fecha_inicio_atencion", "size: 0", "maxlength: 0","class:  dateISO") ?></p>
		<p><label class='labelform' ><span for='hora_inicio_atencion'><b>Hora Inicio Atencion</b>:</span></label><?php echo Tag::textField("hora_inicio_atencion", "size: 0", "maxlength: 0","class: ") ?></p>
		<p><label class='labelform' ><span for='fecha_fin_atencion'><b>Fecha Fin Atencion</b>:</span></label><?php echo Tag::textField("fecha_fin_atencion", "size: 0", "maxlength: 0","class:  dateISO") ?></p>
		<p><label class='labelform' ><span for='hora_fin_atencion'><b>Hora Fin Atencion</b>:</span></label><?php echo Tag::textField("hora_fin_atencion", "size: 0", "maxlength: 0","class: ") ?></p>
		<p><label class='labelform' ><span for='duracion'><b>Duracion</b>:</span></label><?php echo Tag::textField("duracion", "size: 0", "maxlength: 0","class: ") ?></p>
		<p><label class='labelform' ><span for='calificacion'><b>Calificacion</b>:</span></label><?php echo Tag::textField("calificacion", "size: 20", "maxlength: 20","class: ") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
