<div class="ocultar">
    <table>
        <tr>
            <td>
                <input id="chk_barrasCalidad" type="checkbox"/><label style="color:#3366FF; font-size:12px; font-weight:bold">BARRAS</label>
                <input id="chk_pastelCalidad" type="checkbox"/><label style="color:#3366FF; font-size:12px; font-weight:bold">PASTEL</label>
            </td>
            <td>
                <?php
                //$fun = new Funciones();
                //echo $fun->imprimir();
                ?>
            </td>
        </tr>
    </table>
</div>
<table style="height: 100%; width: 100%; background-color: #E5F1F4"  align="center">
    <tr><th colspan="2"> <div id="div_TituloCalidad" style="height: 100%; width: 100%"></div></th></tr>
    <tr>
        <td>
            <table style="height: 100%;width: 100%" align="center">
                <tr>
                    <td>
                        <div id="div_barraCalidad" style="width: 100%; height: 100%" align="center">
                            <div id="div_calidadServicio"  style="height: 100%; width:100%"></div>
                        </div>
                    </td>
                    <td>
                        <div id="div_pastelCalidad" style="width: 100%; height: 100%" align="center"></div>
                    </td>
                <tr><td colspan="2"><div id="div_TablacalidadServicio"  style="width:100%"></div></td></tr>
            </table>
        </td>
    </tr>

</table>