<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('pantallapublicidad/guardar/true');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Pantallapublicidad</legend>
		<p><label class='labelform' ><span for='pantalla_id'><b>Pantalla</b>:</span></label><?php echo Tag::select("pantalla_id", $Pantalla->find("order: descripcion"), "using: id,descripcion", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
		<p><label class='labelform' ><span for='publicidad_id'><b>Publicidad</b>:</span></label><?php echo Tag::select("publicidad_id", $Publicidad->find("order: archivo_publicidad"), "using: id,archivo_publicidad", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
