<div id='mainContent'>

    <?php
    //echo View::getContent();
    View::renderPartial("toolbarform");
    echo Tag::form('ubicacion/guardar/true');
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Ubicación</legend>
        <p><label class='labelform' ><span for='nombre_ubicacion'><b>Nombre Ubicación</b>:</span></label><?php echo Tag::textField("nombre_ubicacion", "size: 45", "maxlength: 45","class:  required") ?></p>
        <p><label class='labelform' ><span for='descripcion'><b>Descripción</b>:</span></label><?php echo Tag::textField("descripcion", "size: 45", "maxlength: 45","class: ") ?></p>
    </fieldset>
    <!--<div class='ui-corner-all ui-widget-content'>
        <?php //echo Tag::submitButton("Grabar");
        //echo Tag::button("Cancelar","onclick: window.location='../index';");
        ?>
    </div>-->
    <?php echo Tag::endForm(); ?>

</div>
