<?php
    View::renderPartial("toolbarform");
    echo Tag::form("sistema/guardar",'autocomplete: off');

?>
<br/>
<div class="ui-corner-all ui-widget-content">

    <table cellpadding="5" ><tr><td><label><span >Nombre Comercial</span></label><br/><?php echo Tag::textField("nombrecomercial", "size: 35", "maxlength: 120","class: required") ?></td>
    <td><label><span>Razon Social</span></label><br/><?php echo Tag::textField("razonsocial", "size: 35", "maxlength: 120","class: required") ?></td></tr></table>
    <p>
       <?php
          $tabs[]=array("caption"=>'General','partial'=>'general');
          $tabs[]=array("caption"=>'Controles de seguridad','partial'=>'seguridad');
          $tabs[]=array("caption"=>'Login','partial'=>'login');
          $tabs[]=array("caption"=>'Envio de E-mail','partial'=>'email');
         // $tabs[]=array("caption"=>'Logos','partial'=>'logo');
         //$tabs[]=array("caption"=>'Apariencia','partial'=>'apariencia');
          Tag::tab($tabs);
       ?>
    </p>
</div>

<?php echo Tag::endForm(); ?>
