<script type="text/javascript" src="../../js/administracion_cookies.js"></script>
<style>
    .fondo_operador{
        background-image:url("../../img/fondo.png");
        background-repeat:repeat-x;
        height:100%;
    }
    .boton_calificacion1{
        color:#fff;
        font-weight:bold;
        font-size: 45pt;
        width: 350px;
        height: 85px;
    }
    .boton_calificacion2{
        font-size: 45pt;
        width: 350px;
        height: 75px;
    }
    .boton_excelente{
        background-color:transparent;
        border: transparent;		background-image:url("../../img/ee/sistema/excelente.png");
        background-size: 100% 100%;
    }
    .boton_muy_bueno{
        background-color:transparent;
        border: transparent;		background-image:url("../../img/ee/sistema/muybueno.png");
        background-size: 100% 100%;		
    }
    .boton_bueno{
        background-color:transparent;
        border: transparent;		background-image:url("../../img/ee/sistema/bueno.png");
        background-size: 100% 100%;		
    }
    .boton_regular{
        background-color:transparent;
        border: transparent;		background-image:url("../../img/ee/sistema/regular.png");
        background-size: 100% 100%;		
    }

    #div_contenido {
        position: absolute;
        left: 161px;
        top: 115px;
        width:523px;
        height:362px;
        z-index:5;
    }
</style>
<?php
$arrayPane[] = array('position' => 'middle', 'options' => 'resizable: false', 'partial' => 'plantilla_calificacion');
Tag::pane($arrayPane);

// Obtener el tiempo de duracion del calificador
$Caja = new Caja();
$objCaja = $Caja->find("ip = '" . $_GET['ip'] . "'");
$tiempoCalificador = 0;
foreach ($objCaja as $resultado) {
    $tiempoCalificador = $resultado->getTiempo();
}
?>
<div id="div_numero_encabezado" class="encabezado" ></div>
<div id="div_contenido" ></div>

<?php echo Tag::hiddenField("idcaja", "size: 1"); ?>
<?php echo Tag::hiddenField("calificador", "size: 1"); ?>
<?php echo Tag::hiddenField("timbre", "size: 1", "value: " . $_GET['tipo']); ?>
<?php Tag::textField("usuario", "size: 5"); ?>

<script>
    var tiempo = <?php echo $tiempoCalificador; ?> ;
    var cont = 1;
    document.getElementById("div_numero_encabezado").innerHTML = modulo;

    window.onresize=Resize;
    Resize();
    function Resize(){
        var ancho=screen.width  //esta variable si utilizo
        //var alto=screen.height  //esta variable si utilizo
        if (ancho>='400' & ancho<='600'){ //pantalla vertical peque馻
            document.getElementById("div_contenido").innerHTML =
                "<table border='0' width='100%'>"+
                "   <tr align='center'>"+
                "       <td style='padding-bottom:10px'><br><br><br><input name='anular' id='excelente' type='button' value='' class='boton_calificacion1 boton_excelente' title='Calificaci贸n Excelente' onclick=calificar('Excelente') ><br><br><br><br><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td style='padding-bottom:10px'><input name='calificar' id='muy_bueno' type='button' value='' class='boton_calificacion1 boton_muy_bueno' title='Calificaci贸n Muy Bueno' onclick=calificar('Muy_Bueno')><br><br><br><br><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td style='padding-bottom:10px'><input name='atender' id='bueno' type='button' value='' class='boton_calificacion1 boton_bueno' title='Calificaci贸n Bueno' onclick=calificar('Bueno')><br><br><br><br><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td style='padding-bottom:10px'><input name='rellamar' id='regular' type='button' value='' class='boton_calificacion1 boton_regular' title='Calificaci贸n Regular' onclick=calificar('Regular')><br><br><br><br><br></td>"+
                "   </tr>"+
                "</table>"
        } else if (ancho>='700' & ancho<='900'){  //pantalla horizontal peque馻
            document.getElementById("div_contenido").innerHTML =
                "<table border='0' width='100%'>"+
                "   <tr align='center'>"+
                "       <td style='padding-bottom:10px'><input name='anular' id='excelente' type='button' value='' class='boton_calificacion2 boton_excelente' title='Calificaci贸n Excelente' onclick=calificar('Excelente') ><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td style='padding-bottom:10px'><input name='calificar' id='muy_bueno' type='button' value='' class='boton_calificacion2 boton_muy_bueno' title='Calificaci贸n Muy Bueno' onclick=calificar('Muy_Bueno')><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td style='padding-bottom:10px'><input name='atender' id='bueno' type='button' value='' class='boton_calificacion2 boton_bueno' title='Calificaci贸n Bueno' onclick=calificar('Bueno')><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td style='padding-bottom:10px'><input name='rellamar' id='regular' type='button' value='' class='boton_calificacion2 boton_regular' title='Calificaci贸n Regular' onclick=calificar('Regular')></td>"+
                "   </tr>"+
                "</table>"
        } else {  //pantalla horizontal peque馻
            document.getElementById("div_contenido").innerHTML =
                "<table border='0' width='100%'>"+
                "   <tr align='center'>"+
                "       <td style='padding-bottom:10px'><input name='anular' id='excelente' type='button' value='' class='boton_calificacion2 boton_excelente' title='Calificaci贸n Excelente' onclick=calificar('Excelente') ><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td style='padding-bottom:10px'><input name='calificar' id='muy_bueno' type='button' value='' class='boton_calificacion2 boton_muy_bueno' title='Calificaci贸n Muy Bueno' onclick=calificar('Muy_Bueno')><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td style='padding-bottom:10px'><input name='atender' id='bueno' type='button' value='' class='boton_calificacion2 boton_bueno' title='Calificaci贸n Bueno' onclick=calificar('Bueno')><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td style='padding-bottom:10px'><input name='rellamar' id='regular' type='button' value='' class='boton_calificacion2 boton_regular' title='Calificaci贸n Regular' onclick=calificar('Regular')></td>"+
                "   </tr>"+
                "</table>"
        }
    }

    //INICIO ABRIR ENVIAR CALIFICACION Y ABRIR PANTALLA INICIAL
    //Funci髇 que permite primero guardar la calificaci髇 y luego abre la pantalla inicial
    function calificar(calificacion){
    
        if (calificacion=="Muy_Bueno")
            calificacion="Muy Bueno";
        $.post("<?php echo Utils::getKumbiaUrl("cajero/terminarTurnoPantalla") ?>",{
            calificacion: calificacion
        }, function(json){
            exito=json.exito;
            if(exito == 1){
                
                //window.open('pantallainicial','Calificador','width=640,height=480,menubar=no,scrollbars=no,toolbar=no,location=no,directories=no,resizable=no,top=0,left=1500');
                if($("#timbre").val()==1){
                    GuardarCookie('nombre',1,1);
                    GuardarCookie('timbre',1,1);
                }else{
                    GuardarCookie('nombre',1,1);
                    GuardarCookie('timbre',0,1);
                }
                window.opener.parent.nuevo_ciclo();
            }		
        },"json");
        //alert(calificacion);
		
        //window.open('pantallainicial','Calificador','width=640,height=480,menubar=no,scrollbars=no,toolbar=no,location=no,directories=no,resizable=no,top=0,left=1500');
        //GuardarCookie('nombre',1,1);
    }
    
    function regresar(){
        if(cont == tiempo){
            terminaTurno();
        }
        cont++;
    }
    setInterval("regresar()", 1000);
    
    function terminaTurno(){
        calificacion = "NO CALIFICADO";
        
        $.post("<?php echo Utils::getKumbiaUrl("cajero/terminaTurno") ?>",{
            calificacion: calificacion
        }, function(json){
            if(json.num_preguntas == json.cont_preguntas){
                //window.open('pantallainicial','Calificador','width=640,height=480,menubar=no,scrollbars=no,toolbar=no,location=no,directories=no,resizable=no,top=0,left=1500');
                if($("#timbre").val()==1){
                    GuardarCookie('nombre',1,1);
                    GuardarCookie('timbre',1,1);
                }else{
                    GuardarCookie('nombre',1,1);
                    GuardarCookie('timbre',0,1);
                }
                window.opener.parent.nuevo_ciclo();
            }
        },"json");
    }
    //INICIO ABRIR ENVIAR CALIFICACION Y ABRIR PANTALLA INICIAL
</script>