<style>
    th{
        background-color:#136FB3;
        color:#fff;
    }
    .cabecera{
        background-color:#86C5F2;
    }
    .semana{
        background-color:#FFD9B3;
    }
    .fin_semana{
        background-color:#CBFAC9;
    }
</style>
<div id='mainContent'>

    <?php
    ////echo View::getContent();
    //echo Tag::form('horario/guardar');
    View::renderPartial("toolbarform");
    echo Tag::form("horario/guardar");
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Horario</legend>
        <p><label class='labelform' ><span for='nombre_horario'><b>Nombre</b>:</span></label><?php echo Tag::textField("nombre_horario", "size: 30", "maxlength: 30","class:  required") ?></p>
        <p><label class='labelform' ><span for='descripcion_horario'><b>Descripción</b>:</span></label><?php echo Tag::textField("descripcion_horario", "size: 50", "maxlength: 50","class: ") ?></p>
    </fieldset>

    <fieldset class='ui-corner-all ui-widget-content'>
        <legend><b>Días de la semana</b></legend>
        <table id="tbl_semana" border="1" class="empty">
            <tr>
                <th align="left"><input id="chk_all_dias" type="checkbox"/>Día de la semana</th>
                <th>Desde</th>
                <th>Hasta</th>
                <th>Horas laborables</th>
            </tr>
            <tr>
                <td class="cabecera"></td>
                <td class="cabecera" colspan="2" align="center">
                    <?php echo Tag::textField("hora_i1_p", "size: 12", "maxlength: 12","class: ", "onChange: calcular()") ?> -
                    <?php echo Tag::textField("hora_f1_p", "size: 12", "maxlength: 12","class: ", "onChange: calcular()") ?> <br>
                    <?php echo Tag::textField("hora_i2_p", "size: 12", "maxlength: 12","class: ", "onChange: calcular()") ?> -
                    <?php echo Tag::textField("hora_f2_p", "size: 12", "maxlength: 12","class: ", "onChange: calcular()") ?> <br>
                    <?php echo Tag::textField("hora_i3_p", "size: 12", "maxlength: 12","class: ", "onChange: calcular()") ?> -
                    <?php echo Tag::textField("hora_f3_p", "size: 12", "maxlength: 12","class: ", "onChange: calcular()") ?> <br>
                </td>
                <td class="cabecera"></td>
            </tr>
            <?php
            $array_dias_semana= array (1=>"Lunes",2=>"Martes",3=>"Miércoles",4=>"Jueves",5=>"Viernes",6=>"Sábado",7=>"Domingo");
            //$array_var_hi= array ('hora_i1_','hora_i2_','hora_i3_');
            //$array_var_hf= array ('hora_f1_','hora_f2_','hora_f3_');
            $cont=0;
            foreach ($array_dias_semana as $key=>$valor) {
                $cont+=1;
                echo "<tr>";
                if ($key==6 | $key==7){
                    $class="fin_semana";
                    echo "<td class='$class'>".Tag::checkboxField("chk_dia_semana[]", "value: $key","checked: ").$valor."</td>";
                } else {
                    $class="semana";
                    echo "<td class='$class'>".Tag::checkboxField("chk_dia_semana[]", "value: $key","checked: checked").$valor."</td>";
                }
                echo "<td colspan='2' align='right' class='$class'>".
                    Tag::textField("hora_i1_".$cont, "size: 12", "maxlength: 12","class: ", "onChange: calcular()")." - ".
                    Tag::textField("hora_f1_".$cont, "size: 12", "maxlength: 12","class: ", "onChange: calcular()")."<br>".
                    Tag::textField("hora_i2_".$cont, "size: 12", "maxlength: 12","class: ", "onChange: calcular()")." - ".
                    Tag::textField("hora_f2_".$cont, "size: 12", "maxlength: 12","class: ", "onChange: calcular()")."<br>".
                    Tag::textField("hora_i3_".$cont, "size: 12", "maxlength: 12","class: ", "onChange: calcular()")." - ".
                    Tag::textField("hora_f3_".$cont, "size: 12", "maxlength: 12","class: ", "onChange: calcular()")."</td>";
                echo "<td align='right' class='$class'>".Tag::textField("horas_laborables_".$cont, "size: 12", "maxlength: 12","class: ")."</td>";
                echo "</tr>";
            }
            ?>
        </table>
    </fieldset>

    <!--<div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
	</div>-->
    <?php echo Tag::endForm(); ?>
</div>

<script>
    $(function() {
        $("#desde").datepicker({ dateFormat: 'yy-mm-dd' });
        $("#hasta").datepicker({ dateFormat: 'yy-mm-dd' });
        $("#hora_i1_p").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i2_p").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i3_p").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f1_p").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f2_p").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f3_p").timepicker({ timeFormat: 'hh:mm:ss' });

        $("#hora_i1_1").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i2_1").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i3_1").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f1_1").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f2_1").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f3_1").timepicker({ timeFormat: 'hh:mm:ss' });

        $("#hora_i1_2").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i2_2").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i3_2").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f1_2").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f2_2").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f3_2").timepicker({ timeFormat: 'hh:mm:ss' });

        $("#hora_i1_3").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i2_3").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i3_3").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f1_3").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f2_3").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f3_3").timepicker({ timeFormat: 'hh:mm:ss' });

        $("#hora_i1_4").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i2_4").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i3_4").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f1_4").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f2_4").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f3_4").timepicker({ timeFormat: 'hh:mm:ss' });

        $("#hora_i1_5").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i2_5").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i3_5").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f1_5").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f2_5").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f3_5").timepicker({ timeFormat: 'hh:mm:ss' });

        $("#hora_i1_6").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i2_6").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i3_6").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f1_6").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f2_6").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f3_6").timepicker({ timeFormat: 'hh:mm:ss' });

        $("#hora_i1_7").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i2_7").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_i3_7").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f1_7").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f2_7").timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f3_7").timepicker({ timeFormat: 'hh:mm:ss' });
    });


    $("#hora_i1_p").change(function(){
        var fecha_i= $("#hora_i1_p").val();
        $("#hora_i1_1").val(fecha_i); $("#hora_i1_2").val(fecha_i); $("#hora_i1_3").val(fecha_i);
        $("#hora_i1_4").val(fecha_i); $("#hora_i1_5").val(fecha_i); $("#hora_i1_6").val(fecha_i); $("#hora_i1_7").val(fecha_i);
    });
    $("#hora_i2_p").change(function(){
        var fecha_i= $("#hora_i2_p").val();
        $("#hora_i2_1").val(fecha_i); $("#hora_i2_2").val(fecha_i); $("#hora_i2_3").val(fecha_i);
        $("#hora_i2_4").val(fecha_i); $("#hora_i2_5").val(fecha_i); $("#hora_i2_6").val(fecha_i); $("#hora_i2_7").val(fecha_i);
    });
    $("#hora_i3_p").change(function(){
        var fecha_i= $("#hora_i3_p").val();
        $("#hora_i3_1").val(fecha_i); $("#hora_i3_2").val(fecha_i); $("#hora_i3_3").val(fecha_i);
        $("#hora_i3_4").val(fecha_i); $("#hora_i3_5").val(fecha_i); $("#hora_i3_6").val(fecha_i); $("#hora_i3_7").val(fecha_i);
    });

    $("#hora_f1_p").change(function(){
        var fecha_f= $("#hora_f1_p").val();
        $("#hora_f1_1").val(fecha_f); $("#hora_f1_2").val(fecha_f); $("#hora_f1_3").val(fecha_f);
        $("#hora_f1_4").val(fecha_f); $("#hora_f1_5").val(fecha_f); $("#hora_f1_6").val(fecha_f); $("#hora_f1_7").val(fecha_f);
    });
    $("#hora_f2_p").change(function(){
        var fecha_f= $("#hora_f2_p").val();
        $("#hora_f2_1").val(fecha_f); $("#hora_f2_2").val(fecha_f); $("#hora_f2_3").val(fecha_f);
        $("#hora_f2_4").val(fecha_f); $("#hora_f2_5").val(fecha_f); $("#hora_f2_6").val(fecha_f); $("#hora_f2_7").val(fecha_f);
    });
    $("#hora_f3_p").change(function(){
        var fecha_f= $("#hora_f3_p").val();
        $("#hora_f3_1").val(fecha_f); $("#hora_f3_2").val(fecha_f); $("#hora_f3_3").val(fecha_f);
        $("#hora_f3_4").val(fecha_f); $("#hora_f3_5").val(fecha_f); $("#hora_f3_6").val(fecha_f); $("#hora_f3_7").val(fecha_f);
    });

    $("#chk_all_dias").click(function(){
        var chks=$("input:checkbox[name^='chk_dia_semana']");
        chks.attr("checked",$(this).is(":checked"))
    });


    function calcular(){
        h1=substractTimes($("#hora_f1_1").val(),$("#hora_i1_1").val());
        h2=substractTimes($("#hora_f2_1").val(),$("#hora_i2_1").val());
        h3=substractTimes($("#hora_f3_1").val(),$("#hora_i3_1").val());
        $("#horas_laborables_1").val(sumarHoras2(h1,h2,h3));

        h1=substractTimes($("#hora_f1_2").val(),$("#hora_i1_2").val());
        h2=substractTimes($("#hora_f2_2").val(),$("#hora_i2_2").val());
        h3=substractTimes($("#hora_f3_2").val(),$("#hora_i3_2").val());
        $("#horas_laborables_2").val(sumarHoras2(h1,h2,h3));

        h1=substractTimes($("#hora_f1_3").val(),$("#hora_i1_3").val());
        h2=substractTimes($("#hora_f2_3").val(),$("#hora_i2_3").val());
        h3=substractTimes($("#hora_f3_3").val(),$("#hora_i3_3").val());
        $("#horas_laborables_3").val(sumarHoras2(h1,h2,h3));

        h1=substractTimes($("#hora_f1_4").val(),$("#hora_i1_4").val());
        h2=substractTimes($("#hora_f2_4").val(),$("#hora_i2_4").val());
        h3=substractTimes($("#hora_f3_4").val(),$("#hora_i3_4").val());
        $("#horas_laborables_4").val(sumarHoras2(h1,h2,h3));

        h1=substractTimes($("#hora_f1_5").val(),$("#hora_i1_5").val());
        h2=substractTimes($("#hora_f2_5").val(),$("#hora_i2_5").val());
        h3=substractTimes($("#hora_f3_5").val(),$("#hora_i3_5").val());
        $("#horas_laborables_5").val(sumarHoras2(h1,h2,h3));

        h1=substractTimes($("#hora_f1_6").val(),$("#hora_i1_6").val());
        h2=substractTimes($("#hora_f2_6").val(),$("#hora_i2_6").val());
        h3=substractTimes($("#hora_f3_6").val(),$("#hora_i3_6").val());
        $("#horas_laborables_6").val(sumarHoras2(h1,h2,h3));

        h1=substractTimes($("#hora_f1_7").val(),$("#hora_i1_7").val());
        h2=substractTimes($("#hora_f2_7").val(),$("#hora_i2_7").val());
        h3=substractTimes($("#hora_f3_7").val(),$("#hora_i3_7").val());
        $("#horas_laborables_7").val(sumarHoras2(h1,h2,h3));
    }

</script>
<!--<script type="text/javascript" src="../../js/jquery-ui-timepicker-addon.js"></script>-->