<script type="text/javascript" src="../../js/administracion_cookies.js"></script>
<style>
    .fondo_operador{
        background-image:url("../../img/fondo.png");
        background-repeat:repeat-x;
        height:100%;
    }
    .boton_calificacion1{
        color:#fff;
        font-weight:bold;
        font-size: 45pt;
        width: 350px;
        height: 85px;
    }
    .boton_calificacion2{
        color:#fff;
        font-weight:bold;
        font-size: 45pt;
        width: 350px;
        height: 85px;
    }
    .boton_excelente{
        background-color:#0042ff;
    }
    .boton_muy_bueno{
        background-color:#05A344;
    }
    .boton_bueno{
        background-color:#E28A12;
    }
    .boton_regular{
        background-color:#CC0000;
    }
</style>

<div  id='mainContent'>

    <?php echo View::getContent();
    //echo Tag::jqGrid("caption: 'Counter'");
    ?>

    <fieldset class='ui-corner-all ui-widget-content ui-state-default'>
        <legend></legend>

        <table border="0" width="100%">
            <tr align="center">
                <td align="center" style="font-size:30px">
                    M&oacute;dulo: <?php echo Tag::textField("numcaja", "style: border:none; background-color:transparent; font-size: 30px; width:120px; text-align:center", "readonly: readonly");?>
                </td>
            </tr>
        </table>
        <div id="div_contenido"></div>
    </fieldset>
</div>
<?php echo Tag::hiddenField("idcaja", "size: 1");?>
<?php echo Tag::hiddenField("calificador", "size: 1");?>
<?php Tag::textField("usuario","size: 5"); ?>

<script>
    function restaurar(){
        var w = screen.width;
        var h = screen.height;
        window.statusbar.visible = false;
        window.scrollbars.visible = false;
        window.menubar.visible = false;
        window.toolbar.visible = false;
        window.locationbar.visible = false;
        window.personalbar.visible = false;
        window.directories.visible = false;
        window.screenX = w+300 ;
        window.screenY = 0;
        window.innerWidth = w;
        window.innerHeight = h;
        //alwaysLowered = false;
        setTimeout("restaurar()",2000);
    }
    restaurar();

    window.onresize=Resize;
    Resize();
    function Resize(){
        var ancho=screen.width  //esta variable si utilizo
        //var alto=screen.height  //esta variable si utilizo
        if (ancho>='400' & ancho<='600'){ //pantalla vertical peque馻
            document.getElementById("div_contenido").innerHTML =
                "<table border='0' width='100%'>"+
                "   <tr align='center'>"+
                "       <td><br><br><br><input name='anular' id='excelente' type='button' value='Excelente' class='boton_calificacion1 boton_excelente' title='Calificaci贸n Excelente' onclick=calificar('Excelente') ><br><br><br><br><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td><input name='calificar' id='muy_bueno' type='button' value='Muy Bueno' class='boton_calificacion1 boton_muy_bueno' title='Calificaci贸n Muy Bueno' onclick=calificar('Muy_Bueno')><br><br><br><br><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td><input name='atender' id='bueno' type='button' value='Bueno' class='boton_calificacion1 boton_bueno' title='Calificaci贸n Bueno' onclick=calificar('Bueno')><br><br><br><br><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td><input name='rellamar' id='regular' type='button' value='Regular' class='boton_calificacion1 boton_regular' title='Calificaci贸n Regular' onclick=calificar('Regular')><br><br><br><br><br></td>"+
                "   </tr>"+
                "</table>"
        } else if (ancho>='700' & ancho<='900'){  //pantalla horizontal peque馻
            document.getElementById("div_contenido").innerHTML =
                "<table border='0' width='100%'>"+
                "   <tr align='center'>"+
                "       <td colspan='2'><input name='anular' id='excelente' type='button' value='Excelente' class='boton_calificacion2 boton_excelente' title='Calificaci贸n Excelente' onclick=calificar('Excelente') ><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td colspan='2'><input name='calificar' id='muy_bueno' type='button' value='Muy Bueno' class='boton_calificacion2 boton_muy_bueno' title='Calificaci贸n Muy Bueno' onclick=calificar('Muy_Bueno')><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td colspan='2'><input name='atender' id='bueno' type='button' value='Bueno' class='boton_calificacion2 boton_bueno' title='Calificaci贸n Bueno' onclick=calificar('Bueno')><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td colspan='2'><input name='rellamar' id='regular' type='button' value='Regular' class='boton_calificacion2 boton_regular' title='Calificaci贸n Regular' onclick=calificar('Regular')></td>"+
                "   </tr>"+
                "</table>"
        } else {  //pantalla horizontal peque馻
            document.getElementById("div_contenido").innerHTML =
                "<table border='0' width='100%'>"+
                "   <tr align='center'>"+
                "       <td colspan='2'><input name='anular' id='excelente' type='button' value='Excelente' class='boton_calificacion2 boton_excelente' title='Calificaci贸n Excelente' onclick=calificar('Excelente') ><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td colspan='2'><input name='calificar' id='muy_bueno' type='button' value='Muy Bueno' class='boton_calificacion2 boton_muy_bueno' title='Calificaci贸n Muy Bueno' onclick=calificar('Muy_Bueno')><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td colspan='2'><input name='atender' id='bueno' type='button' value='Bueno' class='boton_calificacion2 boton_bueno' title='Calificaci贸n Bueno' onclick=calificar('Bueno')><br></td>"+
                "   </tr>"+
                "   <tr align='center'>"+
                "       <td colspan='2'><input name='rellamar' id='regular' type='button' value='Regular' class='boton_calificacion2 boton_regular' title='Calificaci贸n Regular' onclick=calificar('Regular')></td>"+
                "   </tr>"+
                "</table>"
        }
    }

    //INICIO ABRIR ENVIAR CALIFICACION Y ABRIR PANTALLA INICIAL
    //Funci髇 que permite primero guardar la calificaci髇 y luego abre la pantalla inicial
    function calificar(calificacion){
        if (calificacion=="Muy_Bueno")
            calificacion="Muy Bueno";
        $.post("<?php echo Utils::getKumbiaUrl("operador/terminarTurnoPantalla")?>",{
            calificacion: calificacion
        }, function(json){
        },"json");
        window.open('pantallainicial','Calificador','width=640,height=480,menubar=no,scrollbars=no,toolbar=no,location=no,directories=no,resizable=no,top=0,left=1500');
        GuardarCookie('nombre',1,1);
    }
    //INICIO ABRIR ENVIAR CALIFICACION Y ABRIR PANTALLA INICIAL
</script>