<fieldset class='ui-corner-all ui-widget-content'>
    <legend><label style="color:red"><b>Ayuda</b></label></legend>
    <p><label><b>Dirección IP: </b>Sirve para que aparezaca el nombre de usuario automáticamente en la PC con el monitor extendido.</label></p>
</fieldset>
<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Pantalla</b></legend>
    <p><label class='labelform' ><span for='descripcion'>Descripción:</span></label><?php echo Tag::textField("descripcion", "size: 45", "maxlength: 45","class: required") ?></p>
    <p><label class='labelform' ><span for='ip_equipo'>Dirección IP:</span></label><?php echo Tag::textField("ip_equipo", "size: 20", "maxlength: 15","class: ") ?></p>
    <!--<p><label class='labelform' ><span for='con_ticket'><b>Con Ticket</b>:</span></label><?php //echo Tag::textField("con_ticket", "size: 1", "maxlength: 1","class:  numeric") ?></p>-->
    <p><label class='labelform' ><span for='color_turnos'><b>Color Turnos</b>:</span></label><?php echo Tag::textField("color_turnos", "size: 10", "maxlength: 10","class:  required color") ?></p>
    <p><label class='labelform' ><span for='color_noticias'><b>Color Noticias</b>:</span></label><?php echo Tag::textField("color_noticias", "size: 10", "maxlength: 10","class:  required color") ?></p>
    <p><label class='labelform' ><span for='color_reloj'><b>Color Reloj</b>:</span></label><?php echo Tag::textField("color_reloj", "size: 10", "maxlength: 10","class:  required color") ?></p>
    <p><label class='labelform' ><span for='efecto_turno_superior'><b>Efecto Turno Superior</b>:</span></label><?php echo Tag::checkboxField("efecto_turno_superior");?></p>
</fieldset>

<?php
$condicion = "{#Grupo}.id = 6";
$query = new ActiveRecordJoin(array(
                "entities" => array("Usuario", "Grupo", "Grupousuario"),
                "fields" => array(
                        "{#Usuario}.id",
                        "{#Usuario}.nombres"),
                "conditions" => $condicion
));
$listausuarios=array();
foreach($query->getResultSet() as $result) {
    $listausuarios[$result->getId()]=$result->getNombres();
}
?>
<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Usuario</b></legend>
    <p><label class='labelform' ><span for='usuarios'>Asignar a Usuario:</span></label><?php echo Tag::selectStatic("usuarios", $listausuarios,"class:  required") ?></p>
</fieldset>

<?php
//INICIO ubicacion de la pantalla
$ubicacion = new Ubicacion();
$buscaUbicacion = $ubicacion->find();

foreach($buscaUbicacion as $result) {
    $listaubicacion[$result->getId()]=$result->getNombreUbicacion();
}
?>
<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Ubicación de la Pantalla</b></legend>
    <p><label class='labelform' ><span for='ubicacion'>Ubicación:</span></label><?php echo Tag::selectStatic("ubicacion", $listaubicacion,"class:  required") ?></p>
</fieldset>

<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Tipo de Pantalla</b></legend>
    <table border="0px"  align="center">
        <?php
        if ($modulo_atencion_con_ticket==1) {
            echo "<tr>
                <td>
                    <input type='radio' name='radio_tipo_pantalla' value='A' checked> Pantalla para atención con tickets
                </td>
            </tr>";
        }
        if ($modulo_atencion_sin_ticket==1) {
            echo "<tr>
                <td>
                    <input type='radio' name='radio_tipo_pantalla' value='B'> Pantalla para atención sin tickets
                </td>
            </tr>";
        }
        if (($modulo_atencion_con_ticket!=1) & ($modulo_atencion_sin_ticket!=1))
            echo "No tiene acceso a ningún módulo de pantalla. Consulte con el proveedor del sistema SmartQ";
        ?>
    </table>
</fieldset>

<!--<b><?php //echo Tag::radioField("radio_tipo_pantalla",array ('A'=>'Pantalla para atención con tickets')) ?></b>-->