<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('displaycajas/guardar');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Displaycajas</legend>
		<p><label class='labelform' ><span for='id'><b>Id</b>:</span></label><?php echo Tag::textField("id", "size: 11", "maxlength: 11","class:  required numeric") ?></p>
		<p><label class='labelform' ><span for='cajanumero'><b>Cajanumero</b>:</span></label><?php echo Tag::textField("cajanumero", "size: 15", "maxlength: 15","class: ") ?></p>
		<p><label class='labelform' ><span for='ubicacion'><b>Ubicacion</b>:</span></label><?php echo Tag::textField("ubicacion", "size: 4", "maxlength: 4","class:  numeric") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
