<style>
    th{
        background-color:#136FB3;
        color:#fff;
    }
    .cabecera{
        background-color:#86C5F2;
    }
    .semana{
        background-color:#FFD9B3;
    }
    .fin_semana{
        background-color:#CBFAC9;
    }
</style>

<fieldset class='ui-corner-all ui-widget-content'>
    <legend><b>Días de la semana</b></legend>

    <input type="button" value="Agregar programación" onclick="table_agrega_fila();">

    <?php
    //echo Tag::hiddenField("txt1");
    echo Tag::hiddenField("txt1","value:");
    ?>

    <table id="tabla_table" border="1" class="empty">
        <tr>
            <!--<th>Nº</th>-->
            <th width="100px">Inicio</th>
            <th width="100px">Fin</th>
            <th width="100px">Tipo</th>
            <th width="80px">Eliminar</th>
        </tr>

        <?php
        $horariopublicidad = new Horariopublicidad();
        $buscaHorariopublicidad= $horariopublicidad->find("pantalla_id=$id");
        $i=0;
        foreach($buscaHorariopublicidad as $result) {
            $i++;
            //echo "<tr><td></td>";
            echo "<td>".Tag::textField("hora_i_$i", "value: {$result->getHoraInicio()}", "size: 12", "maxlength: 12","class: required", "onChange: cambiarHoraFinal($i)")."</td>";
            echo "<td>".Tag::textField("hora_f_$i", "value: {$result->getHoraFin()}", "size: 12", "maxlength: 12","class: ", "onBlur: verificar($i)")."</td>";
            echo "<td>".Tag::selectStatic("tipo_$i", array('P'=>'Publicidad','D'=>'Difusión','V'=>'Videos'), 'useDummy: yes', "value: {$result->getTipo()}","class: required")."</td>";
            echo '<td> <img onclick="table_elimina(this.parentNode.parentNode);" src="../../../img/delete.gif"></td></tr>';
        }
        ?>
    </table>
</fieldset>

<script>

    var txt=$("input:text[name^='hora_']");
    for (var x=0; x < txt.length; x++) {
        nombre= txt[x].id;
        $("#"+nombre).timepicker({ timeFormat: 'hh:mm:ss' });
    }
    
    function table_agrega_fila(){
        var tabla = document.getElementById('tabla_table');
        var nuevaFila = tabla.insertRow(-1);
        var celda;
        var aux=parseInt($('#txt1').val())+1;
        $('#txt1').attr("value",aux);

        //celda = nuevaFila.insertCell(-1);
        //celda.innerHTML = '';
        celda = nuevaFila.insertCell(-1);
        celda.innerHTML = '<input type="text" id="hora_i_'+aux+'" name="hora_i_'+aux+'" size="12" maxlength="12" onChange="cambiarHoraFinal('+aux+')">';
        celda = nuevaFila.insertCell(-1);
        celda.innerHTML = '<input type="text" id="hora_f_'+aux+'" name="hora_f_'+aux+'" size="12" maxlength="12" onBlur="verificar('+aux+')">';
        celda = nuevaFila.insertCell(-1);
        celda.innerHTML = '<select id="tipo_'+aux+'" usedummy="yes" name="tipo_'+aux+'"><option value="@">Seleccione...</option><option value="P">Publicidad</option><option value="D">Difusión</option><option value="V">Videos</option></select>';   //combo
        celda = nuevaFila.insertCell(-1);
        //celda.innerHTML ='<img onclick="table_elimina(this.parentNode.parentNode);" src="../../../img/delete.gif">';
        celda.innerHTML ='<input type="image" src="../../../img/delete.gif" style="width:15px" title="Eliminar" onclick="table_elimina(this.parentNode.parentNode)">';
        atribuirTimepicker(aux);
    }

    function table_elimina(fila){
        var tabla = document.getElementById('tabla_table');
        tabla.deleteRow(fila.rowIndex);
    }

    function atribuirTimepicker(num_item){
        $("#hora_i_"+num_item).timepicker({ timeFormat: 'hh:mm:ss' });
        $("#hora_f_"+num_item).timepicker({ timeFormat: 'hh:mm:ss' });
    }

    function cambiarHoraFinal(num_item){
        var hora= $("#hora_i_"+num_item).val();
        var valor_a_sumar= '01:00:00';
        var hora_sumado= sumarHoras(hora,valor_a_sumar);
        $("#hora_f_"+num_item).val(hora_sumado);
    }

    /*
     * Funcion que permite verificar que la hora final de cada item
     * no sea menor a la hora inicial
     */
    function verificar(num_item){
        var hora_i= $("#hora_i_"+num_item).val();
        var hora_f= $("#hora_f_"+num_item).val();
        var v = comparaFecha(hora_f,hora_i);
        if (v==-1 | v==0)
            alert("Debe ser mayor");
        cambiarHoraFinal(num_item);
    }

    function pasarHora(){
        var fecha_i= $("#hora_i1_p").val();

    }

</script>


<!--<script type="text/javascript" src="../../js/jquery-ui-timepicker-addon.js"></script>-->