<script>
    function addRow(id,valor){
        var tbody = document.getElementById
        (id).getElementsByTagName("TBODY")[0];
        var row = document.createElement("TR")
        var td1 = document.createElement("TD")
        td1.appendChild(document.createTextNode(valor))
        //td1.appendChild(document.height(30));
        td1.setAttribute('HEIGHT','25');

        //var td2 = document.createElement("TD")
        //td2.appendChild (document.createTextNode("columna 2"))
        row.appendChild(td1);
        //row.appendChild(td2);
        tbody.appendChild(row);
    }
</script>
<fieldset class='ui-corner-all ui-widget-content'>
    <legend><label style="color:red"><b>Ayuda</b></label></legend>
    <p><label><b>Orden: </b>Arrastre la fila según el orden que desee.</label></p>
    <p><label><b>Tipo de pantalla: </b>Si es <b>Pantalla para atención con tickets</b>, no es necesario seleccionar los videos</label></p>
</fieldset>

<fieldset class='ui-corner-all ui-widget-content'>
    <legend><label style="color:black"><b>Seleccione los Videos</b></label></legend>
    <div align='center'>
        <table width="100%">
            <tr>
                <td valign="top">
                    <div style='padding:10px'>
                        <table align="center" width="100%">
                            <?php
                            $videos= new Video();
                            $buscaVideos = $videos->find("activo = 1", "order: nombre asc");
                            ?>
                            <tr>
                                <td>
                                    <?php if(count($buscaVideos)>0) { ?>

                                    <!--Tabla que contiene la tabla de Orden y tabla de Videos-->
                                    <table border="0px"  align="center" width="100%">
                                        <tr>
                                            <td>
                                                <!--Tabla que contiene la tabla de Orden-->
                                                <table id="myTable" border="1px"  align="right">
                                                    <tbody>
                                                        <tr>
                                                            <th height="40px">N.</th>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                            <td>
                                                <!--Tabla que contiene la tabla de Videos-->
                                                <table id="table-1" border="1px"  align=left>
                                                    <tr>
                                                        <th height="40px">Nombre del Video</th>
                                                        <th>Asignado <br>
                                                            <input type="button" onclick="marcar(this.form)" value="Seleccionar todos"/>
                                                            <input type="button" onclick="desmarcar(this.form)" value="Deseleccionar todos"/>
                                                        </th>
                                                    </tr>
                                                        <?php
                                                        //Lista de videos asignados a una pantalla
                                                        $pantallavideos=new Pantallavideos();
                                                        $videoactivo=$pantallavideos->find("conditions: pantalla_id= $id");
                                                        if(count($videoactivo)>0) {
                                                            $listavideos=array();
                                                            foreach($videoactivo as $fila) {
                                                                $listavideos[]=$fila->getVideoId(); //lista de videos asignados a una pantalla
                                                            }
                                                        }else {
                                                            $listavideos[] = "0";
                                                        }

                                                        //Lista de videos
                                                        $videos=new Video();
                                                        $videoactivo=$videos->find("conditions: activo= 1");
                                                        if(count($videoactivo)>0) {
                                                            $todos_videos=array();
                                                            foreach($videoactivo as $fila) {
                                                                $todos_videos[]=$fila->getId(); //lista de videos activos
                                                            }
                                                        }else {
                                                            $todos_videos[] = "0";
                                                        }

                                                        $videos_no_asignados = array_diff($todos_videos, $listavideos);

                                                        //SELECT v.id, nombre FROM video v, pantallavideos pv WHERE v.id=pv.video_id AND pantalla_id=8 ORDER BY orden;
                                                        $contador=0;
                                                        $condicion = "{#Pantallavideos}.pantalla_id = $id";
                                                        $query = new ActiveRecordJoin(array(
                                                            "entities" => array("Video", "Pantallavideos"),
                                                            "fields" => array(
                                                            "{#Video}.id",
                                                            "{#Video}.nombre"),
                                                            "conditions" => $condicion,
                                                            "order"=> "{#Pantallavideos}.orden"
                                                        ));
                                                        foreach($query->getResultSet() as $result) {
                                                            $nombre_video=$result->getNombre();
                                                            $id_video=$result->getId();
                                                            if ($nombre_video!='z-inicio.mpg') {
                                                                $contador+=1;
                                                                print "<script>addRow('myTable','$contador');</script>";
                                                                print "<tr><td>".$result->getNombre()."</td>";
                                                                print "<td align='center' height='25px'>".Tag::checkboxField("chkvideo[]", "value: $id_video", "checked: checked")."</td></tr>";
                                                            }
                                                        }
                                                        foreach($buscaVideos as $attribute) {
                                                            $id_video=$attribute->getId();
                                                            if(in_array($id_video,$listavideos)) {
                                                            }else {
                                                                $contador+=1;
                                                                print "<tr><td>".$attribute->getNombre()."</td>";
                                                                print "<script>addRow('myTable','$contador');</script>";
                                                                print "<td align='center' height='25px'>".Tag::checkboxField("chkvideo[]", "value: $id_video")."</td>";
                                                            }
                                                            print "</tr>";
                                                        }
                                                        ?>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                    <?php }  ?>
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</fieldset>
<?php //echo View::getContent();
//echo Tag::jqGrid("caption: 'Video'");
//echo Tag::jqGrid("caption: 'Videos'","typewinedit: 'popup'","optwinedit: 'width=700,height=300,left=320,top=240,scrollbars=yes'","height: 300","multiselect: false","addbutton: true","editbutton: true","delbutton: true");
?>

<script type="text/javascript">
    $(document).ready(function() {
        // Initialise the table
        $("#table-1").tableDnD();
    });
</script>

<script>
    /*Script que marca todos los videos*/
    function marcar(obj) {
        elem=obj.elements;
        for (i=0;i<elem.length;i++)
            if (elem[i].type=="checkbox")
                elem[i].checked=true;
    }
    /*Script que desmarca todos los videos*/
    function desmarcar(obj) {
        elem=obj.elements;
        for (i=0;i<elem.length;i++)
            if (elem[i].type=="checkbox")
                elem[i].checked=false;
    }
</script>
