<fieldset class='ui-corner-all ui-widget-content'>
    <legend>Areas de la Empresa</legend>
    <p><label class='labelform' ><span for='areas'><b>Número de áreas</b>:</span></label><?php echo Tag::numericField("areas", "size: 5", "maxlength: 10","class: ") ?></p>

   <!-- <p><label class='labelform' ><span for='razonsocial'><b>Razon Social</b>:</span></label><?php echo Tag::textField("razonsocial", "size: 45", "maxlength: 180","class: ") ?></p>
    <p><label class='labelform' ><span for='matriz'><b>Matriz</b>:</span></label><?php echo Tag::checkboxField("matriz");?></p>
    <p><label class='labelform' ><span for='carpeta'><b>Carpeta</b>:</span></label><?php echo Tag::textField("carpeta", "size: 30", "maxlength: 30","class: required") ?></p>
    <p><label class='labelform' ><span for='matriz'><b>Configura Sucursales</b>:</span></label><?php echo Tag::checkboxField("configura_sucursales");?></p>
    -->
</fieldset>