<html>
	<head>
		<title>Pantalla Video</title>
		<link rel="stylesheet" type="text/css" href="styles.css">
		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="archivo.js"></script>

	</head>
	<body>
		<div id="wrap">
			<iframe id="video" src="Redbull.mp4" width="100%" height="100%" wmode="transparent" frameborder="0" autoplay="1" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
			</iframe> 
		</div>

		<div id="foo">
			<div id="content"> Hola Mundo!! </div>
		</div>
		

		<img id="onTop" src="emelec.png"/>

		<!--<img id="publicidad" src="noticia.png"/>-->

		<img id="logo" src="fondo.jpg"/>
	</body>

</html>

<!--<script type="text/javascript">
	
	$(document).ready(function (){
    	$('iframe').each(function(){
        	var url = $(this).attr("src");
        	$(this).attr("src",url+"?wmode=transparent");
    	});
	});
	
</script> -->

