<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('serie/guardar/true');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Serie</legend>
		<p><label class='labelform' ><span for='id'><b>Id</b>:</span></label><?php echo Tag::textField("id", "size: 11", "maxlength: 11","class:  required numeric") ?></p>
		<p><label class='labelform' ><span for='display_id'><b>Display</b>:</span></label><?php echo Tag::select("display_id", $Display->find("order: id"), "using: id,id", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
