<?php View::renderPartial("toolbarform");
    //echo View::getContent();
    echo Tag::form('dispensador/guardar');
?>

<div id='mainContent'>

<?php
        $tabs[]=array("caption"=>'Datos Generales','partial'=>'generalnuevo');
         $tabs[]=array("caption"=>'Videos','partial'=>'videonuevo');
        $tabs[]=array("caption"=>'Banner','partial'=>'bannernuevo');
      
        
        Tag::tab($tabs);
?>
<?php echo Tag::endForm(); ?>

</div>

