
<?php
//print_r(View::getValidationMessages());
if (isset($_GET['invalido'])) {
    echo '<strong style="color:#F00; font-size:15px">No existe la ip registrada porfavor comuniquese con el administrador</strong>';
}

$user = '';
if (isset($_GET['user'])) {
    $user = $_GET['user'];
}
View::getContent();
foreach(View::getValidationMessages() as $mensaje) {
    if(is_object($mensaje))
        Flash::error($mensaje->getMessage());
}
?>
<style type="text/css">
    #img1{
        margin-left:15%;
        margin-top: 3%;
        /*background-image:url("img/sistema.gif");*/
        background-repeat:no-repeat;
        /*height:255px;
        width:250px;*/
        width:25%;
    }
    #img2{
        margin-left:65%;
        margin-top: 0%;
        /*background-image:url("img/sistema.gif");*/
        background-repeat:no-repeat;
        /*height:143px;
        width:385px;*/
        /*height:143px;*/
        width:18%;
    }
    #footer{
        top:90%;
        left:0px;
        position:static;
        text-align: right; 
    }
</style>
<center><br /> <div class="ui-widget-content ui-corner-all ui-widget-header"><h1>SmartQ</h1></div></center>
<div id="img1">
    <?php
    //inicio obtener logo principal
    $empresa= new Empresa();
    $buscaEmpresa= $empresa->findFirst();
    $carpeta= $buscaEmpresa->getCarpeta();
    echo Tag::image($carpeta."/sistema/logo_inicio.png", "width: 100%");
    //fin obtener logo principal
    ?>
</div>
<div id="img2">
    <?php echo Tag::image('SmartQ.png', 'alt: Imagen', 'width: 100%') ?>
</div>
<div id="frmlogin" class="ui-widget ui-widget-content ui-corner-all">

    <div style="width:auto; text-align:center; font-size:14px" class="ui-dialog ui-dialog-titlebar ui-widget-header ui-widget-header  ui-corner-all ui-helper-clearfix">Bienvenido a SmartQueue</div>
    <div class="ui-widget" style="text-align:center">
        <?php echo Tag::form("login/validarUsuario",'id: login')?>
        <br/>
        <p><label><span style="display:block;">Usuario:</span></label><?php echo Tag::textField('usuario','size: 16','maxlenght: 16','value: '.$user)?></p><br/>
        <p><label><span style="display:block;">Password:</span></label><?php echo Tag::passwordField('password','size: 16','maxlenght: 16')?></p><br/>

        <p><?php echo Tag::submitButton("Entrar","class: fg-button ui-submit ui-state-default ui-corner-all") ?></p>
        <?php echo Tag::endForm()?>
    </div>
</div>
<center><br/>
    <div id="footer" class="ui-widget-content ui-corner-all ui-widget-header">
        <h3><a href="http://peopleweb.com.ec" target="_selft" style="text-decoration:none">Desarrollado por "PeopleWeb"</a> <b><?php echo Tag::image('logo_pie.png', 'alt: Imagen') ?></b></h3>
    </div>
</center>
<script>
    //document.getElementById('usuario').focus();
    $(document).ready(function() {
        $('#usuario').focus();
		//$('#login').submit();
    });
	
	function entrar(){
		if($('#usuario').val() != ''){
		//alert($('#usuario').val());
			$('#login').submit();
		}
	} 
	setInterval('entrar()',30000);
</script>
