<!--
Configurar tv
-->

<fieldset class="ui-corner-all ui-widget-content">
    <legend>Configurar Difusión de Tv/Cable</legend>
    <p><label class='labelform' ><span for='activar_difusion'><b>Activar Difusión</b>:</span></label><?php echo Tag::checkboxField("activar_difusion") ?></p>
    <p><label class='labelform' ><span for='pc_difusion'><b>Nombre/Ip</b>:</span></label><?php echo Tag::textField("pc_difusion", "size: 20", "maxlength: 50","class: ") ?></p>
    <p><label class='labelform' ><span for='puerto'><b>Puerto</b>:</span></label><?php echo Tag::numericField("puerto", "size: 5", "maxlength: 10","class: ") ?></p>
</fieldset>