<div id='mainContent'>

    <?php
    //echo View::getContent();
    //echo Tag::form('gruposervicio/guardar');
    View::renderPartial("toolbarform");
    echo Tag::form("gruposervicio/guardar");
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Gruposervicio</legend>
        <p><label class='labelform' ><span for='nombre_grupo_servicio'><b>Nombre Grupo Servicio</b>:</span></label><?php echo Tag::textField("nombre_grupo_servicio", "size: 30", "maxlength: 30","class: ") ?></p>
    </fieldset>
    <!--<div class='ui-corner-all ui-widget-content'>
        <?php //echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
    </div>-->
    <?php echo Tag::endForm(); ?>

</div>
