<?php View::renderPartial("toolbarform");
//echo View::getContent();
echo Tag::form('caja/guardar/true');
?>
<div id='mainContent'>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos del Módulo <?php echo Tag::textField("numero","style: border-style: none", "size: 5", "maxlength: 5", "readonly: readonly") ?></legend>
        <?php
        $tabs[]=array("caption"=>'General','partial'=>'general');
        $tabs[]=array("caption"=>'Asignación de Servicios','partial'=>'servicio');
        $tabs[]=array("caption"=>'Horario de Trabajo','partial'=>'horario');
        $tabs[]=array("caption" => 'Tiempo de Calificador', 'partial' => 'tiempocalificar');
        Tag::tab($tabs);
        ?>
    </fieldset>
</div>

