<table width="100%">
    <tr>
        <td valign="top">
            <table align="center" width="100%">
                <?php
                $servicio=new Servicio();
                $buscaServicios = $servicio->find("estado = 1", "order: nombre asc");
                ?>
                <tr>
                    <td>
                        <b>Seleccione los servicios:</b>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php if(count($buscaServicios)>0) { ?>
                        <table border="1px"  align="center" width="70%">

                            <tr>
                                <th>Nombre del Servicio</th>
                                <th>Asignado</th>
                                <!--<th>Secundario</th>-->
                            </tr>

                                <?php
                                $cajaservicio=new Serviciocaja();
                                $servicioactivo=$cajaservicio->find("conditions: caja_id= $id");
                                //   $servicioactivo=$this->Dispensadorservicio->find("conditions: dispensador_id= $id");
                                if(count($servicioactivo)>0) {
                                    $listaservicios=array();
                                    foreach($servicioactivo as $fila) {
                                        $listaservicios[]=$fila->getServicioId(); //servicios asignados
                                    }
                                }else {
                                    $listaservicios[] = "0";
                                }

                                // llenar tabla con servicios
                                foreach($buscaServicios as $attribute) { //busca todos los servicios
                                    $arrayid[] = $attribute->getId();
                                    $arraynombre[] = $attribute->getNombre();
                                    $idservicio=$attribute->getId();
                                    print "<td>".$attribute->getNombre()."</td>";
                                    if(in_array($idservicio,$listaservicios)) {
                                    //print "<td align='center'>".Tag::checkboxField("chkservicio".$idservicio, "checked: checked")."</td>";
                                        $buscaServicioCaja=$cajaservicio->findFirst("conditions: servicio_id= $idservicio AND caja_id= $id");
                                        $es_secundario=$buscaServicioCaja->getSecundario();
                                        print "<td align='center'>".Tag::checkboxField("chkservicio[]", "value: $idservicio", "checked: checked")."</td>";
                                        //print "<td align='center'>".Tag::checkboxField("chkservicio[]", "value: $idservicio", "checked: checked","onClick=activarValor()")."</td>";
                                        //if ($es_secundario==1)
                                            //print "<td align='center'>".Tag::checkboxField("chkservicio_secundario[]", "value: $idservicio", "checked: checked")."</td>";
                                        //else
                                            //print "<td align='center'>".Tag::checkboxField("chkservicio_secundario[]", "value: $idservicio", "checked: ")."</td>";

                                    }else {
                                        print "<td align='center'>".Tag::checkboxField("chkservicio[]", "value: $idservicio")."</td>";
                                        //print "<td align='center'>".Tag::checkboxField("chkservicio_secundario[]", "value: $idservicio")."</td>";
                                    }
                                    print "</tr>";
                                }
                                ?>
                        </table>
                        <?php }  ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<script>
function activarValor(){
    $("#chkservicio_secundario").val(1);
}
</script>