<?php View::getContent(); ?>

<div align='center'>

<div class='paso'>
Confirmar creaci&oacute;n
</div>

<?php echo Tag::form("create/crearForm") ?>
<table width="100%">
	<tr>
		<td>
			<table align="left" width="100%">
				<tr>
					<td colspan="2">
					<p>Los siguientes archivos ser&aacute;n creados:<br><br>
					<?php
						foreach($files as $file){
							print $file."<br>";
						}
					?>
					</p>
					</td>
				</tr>
				<tr>
					<td colspan="2">
						<table>
							<tr>
								<td><?php echo Tag::checkboxField("force") ?></td>
								<td>Reemplazar si ya existe</td>
							</tr>
							<tr>
								<td><?php echo Tag::checkboxField("modelos") ?></td>
								<td>Crear modelos requeridos</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="2" align="right">
						<?php echo Tag::buttonToAction("Anterior", "create/formOptions") ?>
						<?php echo Tag::submitButton("Finalizar") ?>
					</td>
				</tr>
			</table>
		</td>
		<td valign="top" width="20%" align="center">
			<div id='tipInfo' align="left">
				<b>Informaci&oacute;n &Uacute;til</b><br>
			</div>
		</td>
	</tr>
</table>
<?php echo Tag::endForm() ?>
</div>

<?php echo Tag::javascriptInclude("appgen/create") ?>