<?php View::getContent(); ?>

<div align='center'>

<?php echo Tag::form("create/source") ?>
<table width="100%">
	<tr>
		<td valign="top">
			<div class='paso'>
				Paso 2: Seleccionar tipo de formulario
			</div>
			<table align="center">
				<tr>
					<td align="right">
						<b>Seleccione el tipo de formulario:</b>
					</td>
					<td><?php echo Tag::selectStatic("tipoForm", array(
						"S" => "PANTALLA (MAESTRA)",
						"T" => "PANTALLA TABULAR (GRILLA)",
						"M" => "PANTALLA MIXTA (MAESTRA-DETALLE)"
					)) ?></td>
				</tr>
				<tr>
					<td colspan="2" align="right">
						<?php echo Tag::buttonToAction("Anterior", "create/index") ?>
						<?php echo Tag::submitButton("Siguiente") ?>
					</td>
				</tr>
			</table>
		</td>
		<td valign="top" width="20%" align="center">
			<div id='tipInfo' align="left">
				<b>Informaci&oacute;n &Uacute;til</b><br>
				Seleccione el tipo de formulario que desea crear:<br>
				<p>
				<b>PANTALLA:</b> Crea una p&aacute;gina CRUD (Create, Read, Update, Delete)
				</p>
				<p>
				<b>PANTALLA TABULAR:</b> Crea una pantalla con varias columnas actualizando varios
				registros al tiempo.
				</p>
				<b>PANTALLA MIXTA:</b>Una pantalla dividida en 2 partes, en la superior se puede actualizar
				un registro y en la inferior un conjunto de registros asociados al de arriba.
				</p>
			</div>
		</td>
	</tr>
</table>
<?php echo Tag::endForm() ?>
</div>

<?php echo Tag::javascriptInclude("appgen/create") ?>