<?php View::getContent(); ?>

<div align='center'>

<div class='paso'>
Extra: Datos de la aplicaci&oacute;n
</div>

<?php echo Tag::form("create/crearAplicacion") ?>
<table width="100%">
	<tr>
		<td>
			<table align="center">
				<tr>
					<td align="right">
						<b>Aplicaci&oacute;n:</b>
					</td>
					<td><?php echo $newappname ?></td>
				</tr>
				<tr>
					<td align="right">
						<b>Res&uacute;men Aplicaci&oacute;n:</b>
					</td>
					<td><?php echo Tag::textField("resumen", "size: 40", "maxlength: 100") ?></td>
				</tr>
				<tr>
					<td align="right">
						<b>Descripci&oacute;n:</b>
					</td>
					<td><?php echo Tag::textArea("descripcion", "rows: 5", "cols: 50") ?></td>
				</tr>
				<tr>
					<td align="right">
						<b>Codificaci&oacute;n por Defecto:</b>
					</td>
					<td><?php echo Tag::selectStatic("encoding", array(
						"UTF-8" => "Unicode (UTF-8)",
						"ISO-8859-1" => "Occidental (ISO-8859-1)",
						"ISO-2022-JP" => "Japones (ISO-2022-JP)"
					)) ?></td>
				</tr>
				<tr>
					<td align="right">
						<b>Tipo Adaptador Base de Datos:</b>
					</td>
					<td><?php echo Tag::selectStatic("dbType", array(
						"mysql" => "MySQL Standard",
						"mysqli" => "MySQL Improved",
						"oracle" => "Oracle (OCI)",
						"sqlite" => "SQLite 3 (PDO)"
					)) ?></td>
				</tr>
				<tr id='trHost'>
					<td align="right">
						<b>Host:</b>
					</td>
					<td><?php echo Tag::textField("host", "size: 40", "maxlength: 100") ?></td>
				</tr>
				<tr id='trUsername'>
					<td align="right">
						<b>Nombre Usuario:</b>
					</td>
					<td><?php echo Tag::textField("username", "size: 40", "maxlength: 100") ?></td>
				</tr>
				<tr id='trPassword'>
					<td align="right">
						<b>Password:</b>
					</td>
					<td><?php echo Tag::textField("password", "size: 40", "maxlength: 100") ?></td>
				</tr>
				<tr>
					<td colspan="2" align="right">
						<?php echo Tag::buttonToAction("Anterior", "create/index") ?>
						<?php echo Tag::submitButton("Siguiente") ?>
					</td>
				</tr>
			</table>
		</td>
		<td valign="top" width="20%" align="center">
			<div id='tipInfo' align="left">
				<b>Informaci&oacute;n &Uacute;til</b><br>
				<p>
				Indique en resum&eacute;n el nombre extendido de su aplicaci&oacute;n. Ser&aacute; utilizado en
				los t&iacute;tulos de los reportes (listados) y en la barra de t&iacute;tulo de la aplicaci&oacute;n.
				</p>
				<p>
				La descripci&oacute;n permite documentarla en el Application Forms.
				</p>
			</div>
		</td>
	</tr>
</table>
<?php echo Tag::endForm() ?>
</div>

<?php echo Tag::javascriptInclude("appgen/create") ?>