<!-- Para publicar segun el horario -->
<style>
    .izquierda90 {
        position: absolute;
                top:0px;
                left: 1440px;
   -moz-transform: rotate(90deg);  /* Firefox */
  -o-transform: rotate(90deg);  /* Opera */
  -webkit-transform: rotate(90deg);  /* Safari y Chrome */
  /*filter: progid:DXImageTransform.Microsoft.Matrix(sizingMethod='auto expand', M11=0.7071067811865476, M12=0.7071067811865475, M21=-0.7071067811865475, M22=0.7071067811865476);*/ /* IE */
}
</style>
<div class="rotar izquierda90"> 
<?php
//__________________________INICIO
$ventana = '';
$db = DbBase::rawConnect();
$result2 = $db->query("SELECT 	ventana	FROM configuracionsistema ;");
while ($row = $db->fetchArray($result2)) {
    $ventana = $row['ventana'];
}
if ($ventana == 1) {//$tipo_pantalla = 'vertical';
    ?>
    <script>
        var tipoPantalla = 1;
        var anchoFondo = screen.height;
        var altoFondo = screen.width;
        var marquee_ancho_valor = 690; //esta variable se utiliza mas abajo para saber el tipo de pantalla (horizontal o vertical)

    </script>
    <?php
    $tipo_pantalla = 'contentv';
} else if ($ventana == 0) {//$tipo_pantalla = 'horizontal';
    ?>
    <script>
        var tipoPantalla = 0;
        var anchoFondo = screen.width;
        var altoFondo = screen.height;
        var marquee_ancho_valor = 890;

    </script>
    <?php
    $tipo_pantalla = 'contenth';
}
//__________________________FIN

$arrayPane[] = array('position' => 'middle', 'options' => 'resizable: false', 'partial' => $tipo_pantalla);
Tag::pane($arrayPane);
//$horariopublicidad= new Horariopublicidad();
//echo Tag::textField('txt_aux',"value: $colorReloj");
echo Tag::hiddenField('tipo');  //para el tipo de publicacion V/D/P
?>
</div>
<!-- ***** DIFUNDIR NOTICIAS RSS ***** -->
<script>
    verNoticias();
    setInterval('verNoticias()',1*60*60*1000); //Ver noticias cada hora
    function verNoticias(){
        $.post("<?php echo Utils::getKumbiaUrl("display/verNoticiasRss") ?>", {
            marquee_direccion:  'left',
            marquee_ancho:      marquee_ancho_valor,
            marquee_alto:       46,
            marquee_font_size:  35,
            marquee_alineacion: 'middle'
        },function(data){
            document.getElementById("div_noticias").innerHTML = data;
			
        },'ajax');
    }
</script>

<!-- ***** DIFUNDIR SEGUN HORARIO ***** -->
<script>
    //setInterval('verHorario()',10000); //Ver horario de publicidad cada 10 segundos
    setInterval('verHorario()',1000); //Ver horario de publicidad cada 1 minuto
    var tipo="";
    var recargarV="";

    function verHorario(){
        $.post("<?php echo Utils::getKumbiaUrl("display/verHorario") ?>",{

        }, function(json){
            tipo=json.tipo;
            tipo_aux=$("#tipo").val();
            if (tipo!=tipo_aux){
                $("#tipo").val(tipo)
                if (tipo=='D'){
                    vertv();
                    clearInterval(recargarV);
                }else if (tipo=='P'){
                    verPublicidad(json.archivo);        //con direccion carpeta
                    clearInterval(recargarV);
                } else if (tipo=='V'){
                    /*$.post("<?php //echo Utils::getKumbiaUrl("display/actualizarOrdenPantalla")        ?>",{
                    }, function(json){
                    },"json");*/
                    recargarV=setInterval('recargar()',1000); //Recargar en pantalla el video
                }
            }
        },"json");
    }

    //INICIO PASAR TV
    function vertv(){
        alto:screen.height  //esta variable si utilizo
        document.getElementById("midiv").innerHTML = "<EMBED type='application/x-mplayer2' pluginspage='http://www.microsoft.com/windows/windowsmedia/intl/download/default.asp?DispLang=br' SRC='http://<?php echo $pc_difusion; ?>:<?php echo $puerto; ?>' name='MediaPlayer1' AutoStart=true width='640px' height='500px' showControls='0' ShowStatusBar='0' volume='1'></EMBED>";
    }
    //FIN PASAR TV

    //INICIO PASAR PUBLICIDAD
    function verPublicidad(archivo){
        document.getElementById("midiv").innerHTML = "<object width='640' height='500' attr1='attrValue1' attr2='attrValue2'"+
            "codebase='http://www.apple.com/qtactivex/qtplugin.cab'"+
            "classid='clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B'>"+
            "<param name='src'      value='../../img/"+archivo+"'>"+
            "<param name='autoplay' value='true'>"+
            "<param name='param1'   value='paramValue1'>"+
            "<param name='param2'   value='paramValue2'>"+
            "<embed width='640' height='500' src='../../img/"+archivo+"' autoplay='true'"+
            "attr1='attrValue1' attr2='attrValue2' param1='paramValue1' param2='paramValue2'"+
            "pluginspage='http://www.apple.com/quicktime/download/' > </embed>"+
            "</object>";
    }
    var t;
    function recargar(){
        t=$('#tiempo').val();
        if (t==0){
            recargarVideos();
        } else {
            t=t-1;
            $('#tiempo').val(t);
        }
    }
    function recargarVideos(){
        $.post("<?php echo Utils::getKumbiaUrl("display/vervideo") ?>",{
            accion:'display',
            alto:screen.height  //esta variable si utilizo
        }, function(json){
            $("#tiempo").val(json.tiempo);
            $("#nombre").val(json.nombre);
        },"json");
        var embeber_video = '<object id="MediaPlayer1" CLASSID="CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95" codebase="http://activex.microsoft.com/activex/controls/mplayer/en/nsmp2inf.cab#Version=5,1,52,701"'+
            'standby="Loading Microsoft Windows? Media Player components..." type="application/x-oleobject" width="640" height="490">'+
            '<param name="fileName" value="'+$('#nombre').val()+'">'+
            '<param name="animationatStart" value="true">'+
            '<param name="transparentatStart" value="true">'+
            '<param name="autoStart" value="true">'+
            '<param name="showControls" value="false">'+
            '<param name="Volume" value="-500">'+
            '<embed type="application/x-mplayer2" pluginspage="http://www.microsoft.com/Windows/MediaPlayer/" src="'+$('#nombre').val()+'" name="MediaPlayer1" width=640 height=500 autostart=1 showcontrols=0 volume=-500>'+
            '</object>';
        document.getElementById("midiv").innerHTML = embeber_video;
    }
</script>

<!-- ***** RECARGAR LOS TURNOS EN TABLA ***** -->
<script>
    // setInterval('recargarTurnos()',1000); //Recargar en LCD los turnos luego de 1 segundo
    function recargarTurnos(turnost,cajast){
        var turno='';
        var modulo='';
        $.post("<?php echo Utils::getKumbiaUrl("display/verturnos") ?>",{
            accion:'display'
        }, function(json){
		
            //alert(json.t1);
            //--agregado
            var matTurnos = Array();
            var matCajas = Array();
            matTurnos[0]=json.t1;
            matCajas[0]=json.ta1;
            matTurnos[1]=json.t2;
            matCajas[1]=json.ta2;
            matTurnos[2]=json.t3;
            matCajas[2]=json.ta3;
            matTurnos[3]=json.t4;
            matCajas[3]=json.ta4;
            matTurnos[4]=json.t5;
            matCajas[4]=json.ta5;
            matTurnos[5]=json.t6;
            matCajas[5]=json.ta6;
            
            if(turnost!=json.t1){
                matTurnos.unshift(turnost);
                matTurnos.pop();
            }
            if(cajast != json.ta1){
                matCajas.unshift(cajast);
                matCajas.pop();
            }
            
            //--fin
            /*
            turno = json.t1;
            modulo = json.ta1;
		 
            $("#t1").val(json.t1);
            $("#t2").val(json.t2);
            $("#t3").val(json.t3);
            $("#t4").val(json.t4);
            $("#t5").val(json.t5);
            $("#t6").val(json.t6);

            $("#ta1").val(json.ta1);
            $("#ta2").val(json.ta2);
            $("#ta3").val(json.ta3);
            $("#ta4").val(json.ta4);
            $("#ta5").val(json.ta5);
            $("#ta6").val(json.ta6);

            $("#turno").val(json.t1);
            $("#modulo").val(json.ta1);*/
            
            turno = matTurnos[0];
            modulo = matCajas[0];
            
            for(x = 0 ; x < matTurnos.length ; x++){
                var indice = parseInt(x)+1;
                $("#t"+indice).val(matTurnos[x]);
                $("#ta"+indice).val(matCajas[x]);
            }
            /*
            $("#t1").val(matTurnos[0]);
            $("#t2").val(matTurnos[1]);
            $("#t3").val(matTurnos[2]);
            $("#t4").val(matTurnos[3]);
            $("#t5").val(matTurnos[4]);
            $("#t6").val(matTurnos[5]);

            $("#ta1").val(matCajas[0]);
            $("#ta2").val(matCajas[1]);
            $("#ta3").val(matCajas[2]);
            $("#ta4").val(matCajas[3]);
            $("#ta5").val(matCajas[4]);
            $("#ta6").val(matCajas[5]);*/

            $("#turno").val(matTurnos[0]);
            $("#modulo").val(matCajas[0]);
            //alert(document.getElementById("tono").value);
            if(document.getElementById("tono").value == 1){
                letra = turno.substr(0,1);
                numero1 = turno.substr(1,1);
                numero2 = turno.substr(2,1);
                numero3 = turno.substr(3,1);
			
                if ($('#reproducir').val() == 1){
                    $('#reproducir').val(0);
                    var sonidos='<audio autoplay>'+
                        '<source src="../../sonidos/sonido/turno.mp3" type="audio/mpeg" />'+
                        '</audio>'+
                        '<audio onloadeddata="var audioPlayer = this; setTimeout(function() { audioPlayer.play(); }, 800)">'+
                        '<source src="../../sonidos/sonido/'+letra+'.mp3" type="audio/mpeg" />'+
                        '</audio>'+
                        '<audio onloadeddata="var audioPlayer = this; setTimeout(function() { audioPlayer.play(); }, 1300)">'+
                        '<source src="../../sonidos/sonido/'+numero1+'.mp3" type="audio/mpeg" />'+
                        '</audio>'+
                        '<audio onloadeddata="var audioPlayer = this; setTimeout(function() { audioPlayer.play(); }, 1900)">'+
                        '<source src="../../sonidos/sonido/'+numero2+'.mp3" type="audio/mpeg" />'+
                        '</audio>'+
                        '<audio onloadeddata="var audioPlayer = this; setTimeout(function() { audioPlayer.play(); }, 2400)">'+
                        '<source src="../../sonidos/sonido/'+numero3+'.mp3" type="audio/mpeg" />'+
                        '</audio>'+
                        '<audio onloadeddata="var audioPlayer = this; setTimeout(function() { audioPlayer.play(); }, 3200)">'+
                        '<source src="../../sonidos/sonido/modulo.mp3" type="audio/mpeg" />'+
                        '</audio>'+
                        '<audio onloadeddata="var audioPlayer = this; setTimeout(function() { audioPlayer.play(); }, 4100)">'+
                        '<source src="../../sonidos/sonido/'+modulo+'.mp3" type="audio/mpeg" />'+
                        '</audio>';
                    $("#media1").html(sonidos);
                }
            }
			
        },"json");
		
		
		
		
    }
</script>

<!-- ***** FUNCIONES DE TIMBRE Y EFECTO DE LLAMADO ***** -->
<script>
    
    var matTurnos = Array();
    var matCajas = Array();
    
    var turnot = "";
    var cajat = "";
    setInterval('recargarTimbre()',500); //Recargar el timbre luego de 1 segundo
    var existe = 0;
    function recargarTimbre(){
        $.post("<?php echo Utils::getKumbiaUrl("display/timbrarTurno") ?>",{
            accion:'display'
        }, function(json){
            //$("#reproducir").val(json.reproducir);
            //alert(json.reproducir);
            if(json.existe==1){
                //alert(json.caja_numero);
                matCajas.push(json.caja_numero);
                matTurnos.push(json.numero_turno);
            }
			
        },"json");
        
        if(existe == 0){
            existe = 1;
             
            if(matCajas.length > 0){
                $("#reproducir").val(1);
                turnot=matTurnos[0];
                cajat=matCajas[0];
                matCajas.splice(0,1);
                matTurnos.splice(0,1);
            }else{
                $("#reproducir").val(0);
            }
           
        }
        
        verificar(turnot,cajat);
        
    }
    function verificar(turnost,cajast){ //matTurnos1,matCajas1
        if ($('#reproducir').val()==1){
            
            $('#duracion').val($("#tiempo_tono").val());
            
            //alert(document.getElementById("tono").value);
            if(document.getElementById("tono").value == 0){
                $('#reproducir').val(0);
                empezar();
            }
            recargarTurnos(turnost,cajast);
            //$("#t1").val(matTurnos1);
            //$("#ta1").val(matCajas1);
            //$("#cola").val(turnost);
        }
        var a;
        if ($('#duracion').val()!=0){
            a=$('#duracion').val();
            a=a-1;
            $('#duracion').val(a);
        }
        if ($('#duracion').val()==0){
            existe = 0;
        }
    }
    //__________________________________________________________________________________
    function empezar(){
        //alert('sssssssssssssssssssssss');
        document.getElementById("media1").innerHTML = '<audio autoplay><source src="../../sonidos/timbre2.wav" type="audio/wav"></audio>';
    }

    //__________________________________________________________________________________

    //INICIO EFECTO DE COLOR EN TURNO
    setInterval('colores()',500);
    var color_turnos= "#<?php echo $colorTurnos ?>";
    i=0;
    function colores() {
        if ($('#duracion').val()!=0){
            tabcolores = new Array ("#FFFFFF","#D41904");
            if (i+1 == tabcolores.length) i=0;
            else i++;
            document.getElementById("t1").setAttribute("style", "color:"+tabcolores[i]+"; text-align:center; width:210px; font-family: Impact; font-size: 80px;background: transparent; border:0px;")
            document.getElementById("ta1").setAttribute("style", "color:"+tabcolores[i]+"; text-align:center; width:142px; font-family: Impact; font-size: 80px;background: transparent; border:0px;")

			
            if(marquee_ancho_valor == 690){
                document.getElementById("t1").setAttribute("style", "color:"+tabcolores[i]+"; text-align:center; width:375px; font-family: Impact; font-size: 180px;background: transparent; border:0px;")
                document.getElementById("ta1").setAttribute("style", "color:"+tabcolores[i]+"; text-align:center; width:192px; font-family: Impact; font-size: 180px;background: transparent; border:0px;")
            }
            //$("#div_llamar").css("display", "inline");
            //$("#div_slogan").css("display", "none");
            //document.getElementById("turno").setAttribute("style", "color:"+tabcolores[i]+"; text-align:center; width:250px; font-family: Impact; font-size: 95px;background: transparent; border:0px;")
            //document.getElementById("modulo").setAttribute("style", "color:"+tabcolores[i]+"; text-align:center; width:180px; font-family: Impact; font-size: 95px;background: transparent; border:0px;")
        } else {
            document.getElementById("t1").setAttribute("style", "text-align:center; width:210px; font-family: Impact; font-size: 80px;background: transparent;color: "+color_turnos+"; border:0px;")
            document.getElementById("ta1").setAttribute("style", "text-align:center; width:142px; font-family: Impact; font-size: 80px;background: transparent;color: "+color_turnos+"; border:0px;")

            if(marquee_ancho_valor == 690){
                document.getElementById("t1").setAttribute("style", "text-align:center; width:375px; font-family: Impact; font-size: 180px;background: transparent;color: "+color_turnos+"; border:0px;")
                document.getElementById("ta1").setAttribute("style", "text-align:center; width:192px; font-family: Impact; font-size: 180px;background: transparent;color: "+color_turnos+"; border:0px;")
            }			
            //$("#div_llamar").css("display", "none");
            //$("#div_slogan").css("display", "inline");
            //text-shadow: -2px 0 #000, 0 2px #000, 2px 0 #000, 0 -2px #000
        }
    }
    //FIN EFECTO DE COLOR EN TURNO

</script>

<!-- ***** Restaurar pantalla ***** -->
<script>
    //INICIO RESTAURAR PANTALLA
    function restaurar(){
        if(tipoPantalla == 1){
            $("#imgFondo").attr("width", anchoFondo-5);
            $("#imgFondo").attr("height", altoFondo-5);
            $("#imgFondoNoticia").attr("width", anchoFondo-30);
            $("#div_fondo_turnos").css("top", 150);
            $("#imgFondoTurno").attr("width", anchoFondo-50);
            $("#imgFondoTurno").attr("height", altoFondo-300);
            $("#div_fondo_noticias").css("top", altoFondo-145);
            $("#div_noticias").css("top", altoFondo-100);
        }
        window.innerWidth = screen.width;
        window.innerHeight = screen.height;
        window.screenX = 0;
        window.screenY = 0;
        alwaysLowered = false;
        setTimeout("restaurar()",2000);
    }
    restaurar();
    //FIN RESTAURAR PANTALLA
</script>

<!-- ***** Reloj ***** -->
<script>
    setInterval("reloj()",1000)
    function reloj(){
        momentoActual = new Date()
        hora = momentoActual.getHours()
        minuto = momentoActual.getMinutes()
        segundo = momentoActual.getSeconds()
        dia= momentoActual.getDate();
        mes= momentoActual.getMonth()+1;
        anio= momentoActual.getFullYear();
        if (String(dia).length == 1)
            dia="0"+dia;
        if (String(mes).length == 1)
            mes="0"+mes;
        if (String(hora).length == 1)
            hora="0"+hora;
        if (String(minuto).length == 1)
            minuto="0"+minuto;
        if (String(segundo).length == 1)
            segundo="0"+segundo;
        horaImprimible = hora + " : " + minuto + " : " + segundo;
        $("#hora").val(horaImprimible);
        $("#fecha").val(dia + " / " + mes + " / " + anio);
    }

    document.title= "Pantalla";

</script>


