<?php View::getContent(); ?>

<div align='center'>

<div class='paso'>
Extra: Opciones del formulario
</div>

<?php echo Tag::form("create/crearAplicacion") ?>
<table width="100%">
	<tr>
		<td>
			<table align="center">
				<tr>
					<td align="right">
						<b>Nombre del Controlador:</b>
					</td>
					<td><?php echo Tag::textField("controlador", "size: 40", "maxlength: 100") ?></td>
				</tr>
				<tr>
					<td align="right">
						<b>T&iacute;tulo del Formulario:</b>
					</td>
					<td><?php echo Tag::textField("titulo", "size: 40", "maxlength: 100") ?></td>
				</tr>
				<!--<tr>
					<td align="right">
						<b>Tema:</b>
					</td>
					<td><?php echo Tag::selectStatic("tema", array(
						"NI" => "NINGUNO",
						"BL" => "AZUL"
					)) ?></td>
				</tr>-->
				<tr>
					<td colspan="2">
						<table>
							<tr>
								<td><?php echo Tag::checkboxField("insert") ?></td>
								<td>Operaci&oacute;n de Inserci&oacute;n</td>
							</tr>
							<tr>
								<td><?php echo Tag::checkboxField("update") ?></td>
								<td>Operaci&oacute;n de Actualizaci&oacute;n</td>
							</tr>
							<tr>
								<td><?php echo Tag::checkboxField("delete") ?></td>
								<td>Operaci&oacute;n de Eliminaci&oacute;n</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="2" align="right">
						<?php echo Tag::buttonToAction("Anterior", "create/attributes") ?>
						<?php echo Tag::submitButton("Guardar Cambios") ?>
						<?php echo Tag::buttonToAction("Siguiente", "create/confirmar") ?>
					</td>
				</tr>
			</table>
		</td>
		<td valign="top" width="20%" align="center">
			<div id='tipInfo' align="left">
				<b>Informaci&oacute;n &Uacute;til</b><br>
			</div>
		</td>
	</tr>
</table>
<?php echo Tag::endForm() ?>
</div>

<?php echo Tag::javascriptInclude("appgen/create") ?>