<div id='mainContent'>

    <?php
    //echo View::getContent();
    //echo Tag::form('calificacion/guardar');
    View::renderPartial("toolbarform");
    echo Tag::form("calificacion/guardar");
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Calificación</legend>
        <p><label class='labelform' ><span for='nom_calificacion'><b>Nombre</b>:</span></label><?php echo Tag::textField("nom_calificacion", "size: 15", "maxlength: 15","class: ") ?></p>
        <p><label class='labelform' ><span for='puntos'><b>Puntos</b>:</span></label><?php echo Tag::numericField("puntos", "size: 2", "maxlength: 3","class:  numeric") ?></p>
        <p><label class='labelform' ><span for='orden'><b>Orden</b>:</span></label><?php echo Tag::numericField("orden", "size: 2", "maxlength: 2","class:  numeric") ?></p>
    </fieldset>
    <!--<div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
	</div>-->
    <?php echo Tag::endForm(); ?>

</div>
