<fieldset class='ui-corner-all ui-widget-content'>
    <legend>Tiempo disponible para calificador</legend>
    <p><label class='labelform' ><span for='tiempo'><b>Tiempo (segundos)</b>:</span></label><?php echo Tag::textField("tiempo", "size: 10", "maxlength: 5","placeholder: segundos", "class:  numeric") ?></p>
    <p><label class='labelform' ><span for='ip_calificador'><b>Identificador del Calificador</b>:</span></label><?php echo Tag::textField("ip_calificador", "size: 10", "maxlength: 30","placeholder: ", "class: ") ?></p>
</fieldset>
