<?php echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=UTF-8' />
  <title>SmartQ</title>
  <?php Tag::stylesheetBase() ?>
  <?php echo Tag::stylesheetLinkTags() ?>
  <?php echo Tag::javascriptBase() ?>
 </head>
 <body>
    <?php View::getContent(); ?>
 </body>
</html>
