<div id='mainContent'>

    <?php
    //echo View::getContent();
    View::renderPartial("toolbarform");
    echo Tag::form('datos/guardar');
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Datos</legend>
<!--        <p><label class='labelform' ><span for='id'><b>Id</b>:</span></label><?php //echo Tag::textField("id", "size: 11", "maxlength: 11", "class:  required numeric") ?></p>-->
        <p><label class='labelform' ><span for='nombre'><b>Nombre</b>:</span></label><?php echo Tag::textField("nombre", "size: 50", "maxlength: 50", "class: ") ?></p>
        <p><label class='labelform' ><span for='apellido'><b>Apellido</b>:</span></label><?php echo Tag::textField("apellido", "size: 50", "maxlength: 50", "class: ") ?></p>
    </fieldset>
<!--    <div class='ui-corner-all ui-widget-content'>
    <?php// echo Tag::submitButton("Crear");
    //echo Tag::button("Cancelar", "onclick: window.location='index';"); ?>
    </div>-->
<?php echo Tag::endForm(); ?>

</div>
