<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('grupo/guardar/true');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Grupo</legend>
		<p><label class='labelform' ><span for='modulo_id'><b>Modulo</b>:</span></label><?php echo Tag::select("modulo_id", $Modulo->find("order: nombre"), "using: id,nombre", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
		<p><label class='labelform' ><span for='nombre_largo'><b>Nombre Largo</b>:</span></label><?php echo Tag::textField("nombre_largo", "size: 100", "maxlength: 100","class:  required") ?></p>
		<p><label class='labelform' ><span for='nombre_corto'><b>Nombre Corto</b>:</span></label><?php echo Tag::textField("nombre_corto", "size: 30", "maxlength: 30","class:  required") ?></p>
		<p><label class='labelform' ><span for='descripcion'><b>Descripcion</b>:</span></label><?php echo Tag::textArea("descripcion","cols: 90","rows: 15");?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
