<script>
    function addRow(id,valor){
        var tbody = document.getElementById
        (id).getElementsByTagName("TBODY")[0];
        var row = document.createElement("TR")
        var td1 = document.createElement("TD")
        td1.appendChild(document.createTextNode(valor))
        //td1.appendChild(document.height(30));
        td1.setAttribute('HEIGHT','24');

        //var td2 = document.createElement("TD")
        //td2.appendChild (document.createTextNode("columna 2"))
        row.appendChild(td1);
        //row.appendChild(td2);
        tbody.appendChild(row);
    }
</script>

<div id='mainContent'>

    <?php
    View::renderPartial("toolbarform");
    echo Tag::form("calificacion/guardar_todos");
    ?>

    <table border="0px"  align="center" width="100%">
        <tr>
            <td>
                <!--Tabla que contiene la tabla de Orden-->
                <table id="myTable" border="1px"  align="right">
                    <tbody>
                        <tr>
                            <th height="40px">Orden</th>
                        </tr>
                    </tbody>
                </table>
            </td>
            <td>
                <!--Tabla que contiene los nombres de las calificaciones-->
                <table id="table-1" border="1px"  align=left>
                    <tr>
                        <th height="40px">Nombre</th>
                        <th>Puntos</th>
                    </tr>
                    <?php
                    $calificacion = new Calificacion();
                    $buscaCalificacion= $calificacion->find("order: orden");
                    $contador=0;
                    foreach($buscaCalificacion as $result){
                        $contador+=1;
                        $nombre=$result->getNomCalificacion();
                        $puntos=$result->getPuntos();
                        echo "<script>addRow('myTable','$contador');</script>";
                        echo "<tr><td>".Tag::textField("nombre_$contador", "size: 15", "maxlength: 15","class: ","value: $nombre")."</td>";
                        echo "<td>".Tag::numericField("puntos_$puntos", "size: 2", "maxlength: 3","class:  numeric","value: $puntos")."</td></tr>";
                    }
                    ?>
                </table>
            </td>
        </tr>
    </table>

    <?php echo Tag::endForm(); ?>

</div>

<script type="text/javascript">
    $(document).ready(function() {
        // Initialise the table
        $("#table-1").tableDnD();
    });
</script>