<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('serviciocaja/guardar');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Serviciocaja</legend>
		<p><label class='labelform' ><span for='servicio_id'><b>Servicio</b>:</span></label><?php echo Tag::select("servicio_id", $Servicio->find("order: nombre"), "using: id,nombre", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
		<p><label class='labelform' ><span for='caja_id'><b>Caja</b>:</span></label><?php echo Tag::select("caja_id", $Caja->find("order: id"), "using: id,numero", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
		<p><label class='labelform' ><span for='estado'><b>Estado</b>:</span></label><?php echo Tag::textField("estado", "size: 1", "maxlength: 1","class:  numeric") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
