<div id='mainContent'>

    <?php
    //echo View::getContent();
    View::renderPartial("toolbarform");
    echo Tag::form('grupopregunta/guardar');
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Grupopregunta</legend>
        <!--<p><label class='labelform' ><span for='id'><b>Id</b>:</span></label><?php //echo Tag::textField("id", "size: 11", "maxlength: 11","class:  required numeric")  ?></p>-->
        <p><label class='labelform' ><span for='nom_grupo'><b>Grupo</b>:</span></label><?php echo Tag::textField("nom_grupo", "size: 100", "maxlength: 100", "class: required") ?></p>
        <!--<p><label class='labelform' ><span for='cracion_at'><b>Cracion At</b>:</span></label><?php //echo Tag::textField("cracion_at", "size: 0", "maxlength: 0","class:  dateISO")  ?></p>-->
    </fieldset>
<!--    <div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Crear");
    //echo Tag::button("Cancelar", "onclick: window.location='index';"); ?>
    </div>-->
<?php echo Tag::endForm(); ?>

</div>
