<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('userdisplay/guardar/true');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Userdisplay</legend>
		<p><label class='labelform' ><span for='usuario_id'><b>Usuario</b>:</span></label><?php echo Tag::select("usuario_id", $Usuario->find("order: id"), "using: id,nombres", "use_dummy: yes","dummyValue: ''","class: ") ?></p>
		<p><label class='labelform' ><span for='display_id'><b>Display</b>:</span></label><?php echo Tag::select("display_id", $Display->find("order: id"), "using: id,id", "use_dummy: yes","dummyValue: ''","class: ") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
