<style>
   .visible{
        visibility: hidden;
    }
</style>
<div id='mainContent' enctype="multipart/form-data">

	<?php echo View::getContent();
		 echo Tag::form('banner/guardar');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Banner</legend>
		<p><label class='labelform' ><span for='ubicacion'><b>Ubicacion</b>:</span></label>  <?php echo  Tag::fileField("ubicacion") ?>
                <?php echo Tag::textField("ubicacion1", "size: 2", "maxlength:2","class: visible ");?>
                <p><label class='labelform' ><span for='serie'><b>Serie</b>:</span></label><?php echo Tag::textField("serie", "size: 11", "maxlength: 11","class:  numeric") ?></p>
                <p><label class='labelform' ><span for='posicion'><b>Posicion</b>:</span></label><?php echo Tag::selectStatic("posicion", array(1=>"Superior", 2=>"Inferior")) ?></p>
		<p><label class='labelform' ><span for='display_id'><b>Display</b>:</span></label><?php echo Tag::select("display_id", $Display->find("order: id"), "using: id,id", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>

                <h3>Agregar Foto:</h3>
                <?= form_tag("banner/subir","enctype: multipart/form-data")?>


                 <p><label>Imagen:</label><?php echo file_field_tag("foto"); ?>

                 <?= submit_tag("Agregar") ?>

          


	</div>
	<?php echo Tag::endForm(); ?>

</div>
