<style type="text/css">
    .parametros{background-color: #fff; color:#000; padding:10px; top:130px; left:350px; position:absolute}

    th{
        background-color:#136FB3;
        color:#fff;
    }
    .cabecera{
        background-color:#86C5F2;
    }
</style>
<?php View::renderPartial("toolbarform");
//echo View::getContent();
echo Tag::form('caja/guardar/true');
?>
<div id='mainContent'>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos del Módulo <?php echo Tag::textField("numero","style: border-style: none", "size: 5", "maxlength: 5", "readonly: readonly") ?></legend>
        <?php
        $tabs[]=array("caption"=>'General','partial'=>'general');
        $tabs[]=array("caption"=>'Asignación de Servicios','partial'=>'servicio');
        //$tabs[]=array("caption"=>'Horario de Trabajo','partial'=>'horario');
        Tag::tab($tabs);
        ?>
    </fieldset>
</div>

