<!--
Configurar para operador
-->
<?php
$ventana = '';
$pantalla_ticket = '';
$db = DbBase::rawConnect();
$result2 = $db->query("SELECT 	ventana, pantalla_ticket	FROM configuracionsistema ;");
while($row = $db->fetchArray($result2)) 
{
$ventana=$row['ventana'];
$pantalla_ticket=$row['pantalla_ticket'];
}
?>
<fieldset class="ui-corner-all ui-widget-content">
    <legend>Configuración de la orientación de la pantalla turnos con ticket</legend>
<table width="200" border="0">
  <tr>
    <td><p>
      <label>
        <input name="RadioGroup1" type="radio" id="RadioGroup1_3" value="opción" <?php if($ventana == 0) echo 'checked="checked"'; ?>/>	
      </label>
    </p></td>
	<td><strong>Horizontal</strong></td>	
  </tr>
  <tr>
    <td><input type="radio" name="RadioGroup1" value="opción" id="RadioGroup1_4" <?php if($ventana == 1) echo 'checked="checked"'; ?> /></td>
	<td><strong>Vertical</strong></td>
  </tr>
</table>
<?php echo Tag::textField("ventana", "size: 40", "maxlength: 100","class: required", "hidden: 'hidden'" , "value: $ventana") ?>
</fieldset>

<fieldset class="ui-corner-all ui-widget-content">
    <legend>Configuración de la pantalla turnos sin ticket</legend>
<table width="200" border="0">
  <tr>
    <td><p>
      <label>
        <input name="RadioGroup7" type="radio" id="RadioGroup7_0" value="opción" <?php if($pantalla_ticket == 0) echo 'checked="checked"'; ?>/>	
      </label>
    </p></td>
	<td><strong>Mostrar videos, publicidad, difución, noticias y rss</strong></td>	
  </tr>
  <tr>
    <td><input type="radio" name="RadioGroup7" value="opción" id="RadioGroup7_1" <?php if($pantalla_ticket == 1) echo 'checked="checked"'; ?> /></td>
	<td><strong>Mostrar llamado de turnos centrado en la pantalla</strong></td>
  </tr>
</table>
<?php echo Tag::textField("pantalla_ticket", "size: 40", "maxlength: 100","class: required", "hidden: 'hidden'" , "value: $pantalla_ticket") ?>
</fieldset>

<script>
$("#RadioGroup1_3").click(function(){
document.getElementById('ventana').value = 0;
});
$("#RadioGroup1_4").click(function(){
document.getElementById('ventana').value = 1;
});   
</script>
<script>
$("#RadioGroup7_0").click(function(){
document.getElementById('pantalla_ticket').value = 0;
});
$("#RadioGroup7_1").click(function(){
document.getElementById('pantalla_ticket').value = 1;
});   
</script>


