<div id='mainContent'>

    <?php
    //echo View::getContent();
    //echo Tag::form('preguntas/guardar');
    View::renderPartial("toolbarform");
    echo Tag::form("preguntas/guardar");
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Preguntas</legend>
        <p><label class='labelform' ><span for='id_grupopregunta'><b>Grupo</b>:</span></label><?php echo Tag::select("id_grupopregunta", $Grupopregunta->find("order: nom_grupo"), "using: id,nom_grupo", "use_dummy: yes", "dummyValue: ''", "class: required") ?></p>
        <p><label class='labelform' ><span for='nom_pregunta'><b>Pregunta</b>:</span></label><?php echo Tag::textField("nom_pregunta", "size: 50", "maxlength: 60","class: ") ?></p>
        <p><label class='labelform' ><span for='publicar'><b>Publicar</b>:</span></label><?php echo Tag::checkboxField("publicar");?></p>
        <p><label class='labelform' ><span for='orden'><b>Orden</b>:</span></label><?php echo Tag::numericField("orden", "size: 2", "maxlength: 2","class:  numeric") ?></p>
    </fieldset>
    <!--<div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
    </div>-->
    <?php echo Tag::endForm(); ?>

</div>
