<style type="text/css">
    .parametros{background-color: #fff; color:#000; padding:10px; top:130px; left:350px; position:absolute}

    th{
        background-color:#136FB3;
        color:#fff;
    }
    .cabecera{
        background-color:#86C5F2;
    }
</style>
<?php View::renderPartial("toolbarform");
//echo View::getContent();
echo Tag::form('caja/guardar');
?>
<div id='mainContent'>
    <?php
    $tabs[]=array("caption"=>'Datos Generales','partial'=>'generalnuevo');
    $tabs[]=array("caption"=>'Asignación de Servicios','partial'=>'servicionuevo');
    //$tabs[]=array("caption"=>'Horario de Trabajo','partial'=>'horarionuevo');
    Tag::tab($tabs);
    ?>
</div>

