<div id='mainContent'>

    <?php //echo View::getContent();
    //echo Tag::form('empresa/guardar/true');
    View::renderPartial("toolbarform");
    echo Tag::form("empresa/guardar/true","enctype: multipart/form-data");

    $tabs[]=array("caption"=>'Datos Generales','partial'=>'general_empresa');
    $tabs[]=array("caption"=>'Módulos','partial'=>'modulos_empresa');
    $tabs[]=array("caption"=>'Tipo Calificación','partial'=>'calificacion_empresa');
    $tabs[]=array("caption"=>'Tipo Dispensador','partial'=>'tipo_dispensador');
    Tag::tab($tabs);
    ?>
    <!--<div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
    </div>-->
    <?php echo Tag::endForm(); ?>
</div>
