<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('inicioturnos/guardar/true');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Inicioturnos</legend>
		<p><label class='labelform' ><span for='inicio_turno'><b>Inicio Turno</b>:</span></label><?php echo Tag::textField("inicio_turno", "size: 4", "maxlength: 4","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='fin_turno'><b>Fin Turno</b>:</span></label><?php echo Tag::textField("fin_turno", "size: 4", "maxlength: 4","class:  numeric") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
