<fieldset class="ui-corner-all ui-widget-content">
    <legend>Datos Generales</legend>
    <p><label class='labelform' ><span for='numero'><b>Número de Módulo</b>:</span></label><?php echo Tag::numericField("numero", "size: 2", "maxlength: 2","class: required") ?></p>
    <p><label class='labelform' ><span for='descripcion'><b>Descripción</b>:</span></label><?php echo Tag::textField("descripcion", "size: 80", "maxlength: 145","class: required") ?></p>
    <p><label class='labelform' ><span for='ubicacion_id'><b>Ubicacion</b>:</span></label><?php echo Tag::select("ubicacion_id", $Ubicacion->find("order: nombre_ubicacion"), "using: id,nombre_ubicacion", "use_dummy: yes","dummyValue: ''","class: required") ?></p>
    <p><label class='labelform' ><span for='ip'><b>IP</b>:</span></label><?php echo Tag::textField("ip", "size: 20", "maxlength: 15","class: required") ?></p>
</fieldset>

<?php
/*$listausuarios=array();

$condicion = "{#Grupo}.id = 5"; //operadores
$query = new ActiveRecordJoin(array(
    "entities" => array("Usuario", "Grupo", "Grupousuario"),
    "fields" => array(
    "{#Usuario}.id",
    "{#Usuario}.nombres"),
    "conditions" => $condicion
));
foreach($query->getResultSet() as $result) {
    $listausuarios[$result->getId()]=$result->getNombres();
}

$condicion = "{#Grupo}.id = 7"; //cajeros
$query = new ActiveRecordJoin(array(
    "entities" => array("Usuario", "Grupo", "Grupousuario"),
    "fields" => array(
    "{#Usuario}.id",
    "{#Usuario}.nombres"),
    "conditions" => $condicion
));
foreach($query->getResultSet() as $result) {
    $listausuarios[$result->getId()]=$result->getNombres();
}*/
?>
<!--<fieldset class="ui-corner-all ui-widget-content">
    <legend>Usuario</legend>
    <p><label class='labelform' ><span for='usuarios'><b>Asignar a Usuario</b>:</span></label><?php //echo Tag::selectStatic("usuarios", $listausuarios, "use_dummy: no","dummyValue: ''","class: required") ?></p>
</fieldset>-->

<fieldset class='ui-corner-all ui-widget-content'>
    <legend>Tipo de Calificación</legend>
    <input id='radio_tipo_calificacion' type='radio' name='radio_tipo_calificacion' value='D' checked> Ninguno
    <?php
    $empresa = new empresa;
    $buscaEmpresa=$empresa->findFirst();
    $calif_4botones_teclado=$buscaEmpresa->getCalif4botonesTeclado();
    $calif_4botones_pantalla=$buscaEmpresa->getCalif4botonesPantalla();
    $calif_matriz_pantalla=$buscaEmpresa->getCalifMatrizPantalla();
    $array_op_calificacion= array(
            'A'=>array('activo'=>$calif_4botones_teclado,'etiqueta'=>'Calificación con teclado de 4 botones'),
            'B'=>array('activo'=>$calif_4botones_pantalla,'etiqueta'=>'Calificación con pantalla touch de 4 botones'),
            'C'=>array('activo'=>$calif_matriz_pantalla,'etiqueta'=>'Calificación con pantalla touch de multipreguntas')
    );
    if ($calif_4botones_teclado!=0 | $calif_4botones_pantalla!=0 | $calif_matriz_pantalla!=0) {
        foreach ($array_op_calificacion as $key=>$val) {
            if ($val['activo']!=0)  //key es el value
                echo Tag::radioField("radio_tipo_calificacion",array ($key=>$val['etiqueta'])) ;
        }
    }
    ?>
</fieldset>

<fieldset class="ui-corner-all ui-widget-content">
    <legend>Permisos de transferencia de turnos</legend>
    <p><label class='labelform' ><span for='transferir_uno'><b>Transferir Uno</b>:</span></label><?php echo Tag::checkboxField("transferir_uno");?></p>
    <p><label class='labelform' ><span for='transferir_todos'><b>Transferir Todos</b>:</span></label><?php echo Tag::checkboxField("transferir_todos");?></p>
</fieldset>