<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('turnos_transferidos/guardar/true');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Turnos Transferidos</legend>
		<p><label class='labelform' ><span for='servicio_id'><b>Servicio</b>:</span></label><?php echo Tag::select("servicio_id", $Servicio->find("order: id"), "using: id,id", "use_dummy: yes","dummyValue: ''","class: ") ?></p>
		<p><label class='labelform' ><span for='numero'><b>Número</b>:</span></label><?php echo Tag::textField("numero", "size: 11", "maxlength: 11","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='fecha_emision'><b>Fecha Emisión</b>:</span></label><?php echo Tag::textField("fecha_emision", "size: 0", "maxlength: 0","class:  dateISO") ?></p>
		<p><label class='labelform' ><span for='hora_emision'><b>Hora Emisión</b>:</span></label><?php echo Tag::textField("hora_emision", "size: 0", "maxlength: 0","class: ") ?></p>
		<p><label class='labelform' ><span for='estado'><b>Estado</b>:</span></label><?php echo Tag::textField("estado", "size: 4", "maxlength: 4","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='caja_id'><b>Módulo</b>:</span></label><?php echo Tag::select("caja_id", $Caja->find("order: id"), "using: id,id", "use_dummy: yes","dummyValue: ''","class: ") ?></p>
		<p><label class='labelform' ><span for='por_atender'><b>Por Atender</b>:</span></label><?php echo Tag::textField("por_atender", "size: 4", "maxlength: 4","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='atendido'><b>Atendido</b>:</span></label><?php echo Tag::textField("atendido", "size: 4", "maxlength: 4","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='fecha_inicio_atencion'><b>Fecha Inicio Atención</b>:</span></label><?php echo Tag::textField("fecha_inicio_atencion", "size: 0", "maxlength: 0","class:  dateISO") ?></p>
		<p><label class='labelform' ><span for='hora_inicio_atencion'><b>Hora Inicio Atención</b>:</span></label><?php echo Tag::textField("hora_inicio_atencion", "size: 0", "maxlength: 0","class: ") ?></p>
		<p><label class='labelform' ><span for='fecha_fin_atencion'><b>Fecha Fin Atención</b>:</span></label><?php echo Tag::textField("fecha_fin_atencion", "size: 0", "maxlength: 0","class:  dateISO") ?></p>
		<p><label class='labelform' ><span for='hora_fin_atencion'><b>Hora Fin Atención</b>:</span></label><?php echo Tag::textField("hora_fin_atencion", "size: 0", "maxlength: 0","class: ") ?></p>
		<p><label class='labelform' ><span for='duracion'><b>Duración</b>:</span></label><?php echo Tag::textField("duracion", "size: 0", "maxlength: 0","class: ") ?></p>
		<p><label class='labelform' ><span for='rechazado'><b>Rechazado</b>:</span></label><?php echo Tag::textField("rechazado", "size: 4", "maxlength: 4","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='calificacion'><b>Calificación</b>:</span></label><?php echo Tag::textField("calificacion", "size: 20", "maxlength: 20","class: ") ?></p>
		<p><label class='labelform' ><span for='permiso_cajas'><b>Permiso Cajas</b>:</span></label><?php echo Tag::textField("permiso_cajas", "size: 50", "maxlength: 50","class: ") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
