<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('grupousuario/guardar');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Grupousuario</legend>
		<p><label class='labelform' ><span for='grupo_id'><b>Grupo</b>:</span></label><?php echo Tag::select("grupo_id", $Grupo->find("order: nombre_largo"), "using: id,nombre_largo", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
		<p><label class='labelform' ><span for='usuario_id'><b>Usuario</b>:</span></label><?php echo Tag::select("usuario_id", $Usuario->find("order: ci"), "using: id,ci", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
