<div id='mainContent'>

    <?php
    //echo View::getContent();
    View::renderPartial("toolbarform");
    echo Tag::form("configuracionsistema/guardar/true");

    $tabs[] = array("caption" => 'Noticias', 'partial' => 'noticias');
    //$tabs[] = array("caption" => 'Difusión Tv/Cable', 'partial' => 'tv');
    $tabs[] = array("caption" => 'Operador', 'partial' => 'operador');
    $tabs[] = array("caption" => 'Impresora', 'partial' => 'impresora');
    //$tabs[] = array("caption" => 'Pantalla', 'partial' => 'pantalla');
    $datos = SessionNamespace::get('datosUsuarioSMC');
    $id_usuario = $datos->getId();
    if ($id_usuario == 8) {
        $tabs[] = array("caption" => 'Logo', 'partial' => 'logo');
    }
    Tag::tab($tabs);
    ?>
    <!--<div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';");  ?>
    </div>-->
    <?php echo Tag::endForm(); ?>

</div>