<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('banner/guardar/true');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Banner</legend>
		<p><label class='labelform' ><span for='ubicacion'><b>Ubicacion</b>:</span></label><?php echo Tag::textField("ubicacion", "size: 100", "maxlength: 100","class: ") ?></p>
		<p><label class='labelform' ><span for='serie'><b>Serie</b>:</span></label><?php echo Tag::textField("serie", "size: 11", "maxlength: 11","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='posicion'><b>Posicion</b>:</span></label><?php echo Tag::textField("posicion", "size: 11", "maxlength: 11","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='display_id'><b>Display</b>:</span></label><?php echo Tag::select("display_id", $Display->find("order: id"), "using: id,id", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
