<div id='mainContent'>

    <?php
    //echo View::getContent();
    //echo Tag::form('menu/guardar');
    View::renderPartial("toolbarform");
    echo Tag::form("menu/guardar");
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Menu</legend>
        <p><label class='labelform' ><span for='modulo_id'><b>Modulo</b>:</span></label><?php echo Tag::select("modulo_id", $Modulo->find("order: id"), "using: id,nombre", "use_dummy: yes", "dummyValue: ''", "class:  required") ?></p>
        <p><label class='labelform' ><span for='nombre'><b>Nombre</b>:</span></label><?php echo Tag::textField("nombre", "size: 30", "maxlength: 30", "class:  required") ?></p>
        <p><label class='labelform' ><span for='ruta'><b>Ruta</b>:</span></label><?php echo Tag::textField("ruta", "size: 40", "maxlength: 255", "class: ") ?></p>
        <p><label class='labelform' ><span for='idreferencia'><b>Idreferencia</b>:</span></label><?php echo Tag::textField("idreferencia", "size: 11", "maxlength: 11", "class:  required numeric") ?></p>
        <p><label class='labelform' ><span for='estado'><b>Estado</b>:</span></label><?php echo Tag::textField("estado", "size: 1", "maxlength: 1", "class:  required numeric") ?></p>
        <p><label class='labelform' ><span for='orden'><b>Orden</b>:</span></label><?php echo Tag::textField("orden", "size: 11", "maxlength: 11", "class:  required numeric") ?></p>
        <p><label class='labelform' ><span for='principal'><b>Principal</b>:</span></label><?php echo Tag::textField("principal", "size: 1", "maxlength: 1", "class:  required numeric") ?></p>
        <p><label class='labelform' ><span for='posicion'><b>Posicion</b>:</span></label><?php echo Tag::textField("posicion", "size: 11", "maxlength: 50", "class: ") ?></p>
        <p><label class='labelform' ><span for='tipo_ventana'><b>Tipo Ventana</b>:</span></label><?php echo Tag::textField("tipo_ventana", "size: 11", "maxlength: 20", "class:  required") ?></p>
    </fieldset>
    <!--<div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
    </div>-->
    <?php echo Tag::endForm(); ?>

</div>
