<div id='mainContent'>

    <?php //echo View::getContent();
    //echo Tag::form('sesiones/guardar/true');
    View::renderPartial("toolbarform");
    echo Tag::form("sesiones/guardar/true");
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Sesiones</legend>
        <p><label class='labelform' ><span for='usuario_id'><b>Usuario</b>:</span></label><?php echo Tag::select("usuario_id", $Usuario->find("order: nombres"), "using: id,nombres", "use_dummy: yes","dummyValue: ''","class: ") ?></p>
        <p><label class='labelform' ><span for='caja_id'><b>Módulo</b>:</span></label><?php echo Tag::select("caja_id", $Caja->find("order: numero_caja"), "using: id,numero_caja", "use_dummy: yes","dummyValue: ''","class: ") ?></p>
        <p><label class='labelform' ><span for='ubicacion_id'><b>Ubicación</b>:</span></label><?php echo Tag::select("ubicacion_id", $Ubicacion->find("order: nombre_ubicacion"), "using: id,nombre_ubicacion", "use_dummy: yes","dummyValue: ''","class: ") ?></p>
        <p><label class='labelform' ><span for='estado'><b>Estado</b>:</span></label><?php echo Tag::textField("estado", "size: 15", "maxlength: 15","class: ") ?></p>
        <p><label class='labelform' ><span for='ip'><b>Ip</b>:</span></label><?php echo Tag::textField("ip", "size: 15", "maxlength: 15","class: ") ?></p>
        <p><label class='labelform' ><span for='fecha_inicio'><b>Fecha Inicio</b>:</span></label><?php echo Tag::textField("fecha_inicio", "size: 0", "maxlength: 0","class:  dateISO") ?></p>
        <p><label class='labelform' ><span for='hora_inicio'><b>Hora Inicio</b>:</span></label><?php echo Tag::textField("hora_inicio", "size: 0", "maxlength: 0","class: ") ?></p>
        <p><label class='labelform' ><span for='fecha_fin'><b>Fecha Fin</b>:</span></label><?php echo Tag::textField("fecha_fin", "size: 0", "maxlength: 0","class:  dateISO") ?></p>
        <p><label class='labelform' ><span for='hora_fin'><b>Hora Fin</b>:</span></label><?php echo Tag::textField("hora_fin", "size: 0", "maxlength: 0","class: ") ?></p>
        <p><label class='labelform' ><span for='duracion'><b>Duración</b>:</span></label><?php echo Tag::textField("duracion", "size: 0", "maxlength: 0","class: ") ?></p>
    </fieldset>
    <!--<div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
	</div>-->
    <?php echo Tag::endForm(); ?>

</div>
