
<?php

?>
<div>
<table width="100%">

    <tr id="fila">
        <td rowspan="2" align="center"><img src="../img/logo_pie.png"/>
        </td>
        <td style="font-size:16px; text-decoration:inherit; color:red;">Sistema SmartQ</td>
        <!--<td align="right">Idioma: Espa&ntilde;ol</td>-->
    </tr>
    <tr>
        <td><a href="http://peopleweb.com.ec" target="blank" style="text-decoration:none">Pagina Oficial de PeopleWeb</a></td>
        <td align="right">Copyright 2010, Todos los derechos reservados</td>
    </tr>

</table>
</div>
