<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('timbre/guardar/true');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Timbre</legend>
		<p><label class='labelform' ><span for='estado_timbrar'><b>Id</b>:</span></label><?php echo Tag::textField("estado_timbrar", "size: 11", "maxlength: 4","class:  numeric") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
