<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('pantallafeed/guardar/true');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Pantallafeed</legend>
		<p><label class='labelform' ><span for='pantalla_id'><b>Pantalla</b>:</span></label><?php echo Tag::select("pantalla_id", $Pantalla->find("order: descripcion"), "using: id,descripcion", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
		<p><label class='labelform' ><span for='feed_id'><b>Feed</b>:</span></label><?php echo Tag::select("feed_id", $Feed->find("order: url_feed"), "using: id,url_feed", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
		<p><label class='labelform' ><span for='categoriafeeds_id'><b>Categoriafeeds</b>:</span></label><?php echo Tag::select("categoriafeeds_id", $Categoriafeeds->find("order: nombre_categoria"), "using: id,nombre_categoria", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
		<p><label class='labelform' ><span for='publicar_icono'><b>Publicar Icono</b>:</span></label><?php echo Tag::textField("publicar_icono", "size: 1", "maxlength: 1","class:  required numeric") ?></p>
		<p><label class='labelform' ><span for='publicar_titulo'><b>Publicar Titulo</b>:</span></label><?php echo Tag::textField("publicar_titulo", "size: 1", "maxlength: 1","class:  required numeric") ?></p>
		<p><label class='labelform' ><span for='publicar_fecha'><b>Publicar Fecha</b>:</span></label><?php echo Tag::textField("publicar_fecha", "size: 1", "maxlength: 1","class:  required numeric") ?></p>
		<p><label class='labelform' ><span for='publicar_hora'><b>Publicar Hora</b>:</span></label><?php echo Tag::textField("publicar_hora", "size: 1", "maxlength: 1","class:  required numeric") ?></p>
		<p><label class='labelform' ><span for='publicar_contenido'><b>Publicar Contenido</b>:</span></label><?php echo Tag::textField("publicar_contenido", "size: 1", "maxlength: 1","class:  required numeric") ?></p>
		<p><label class='labelform' ><span for='limite_items'><b>Límite Items</b>:</span></label><?php echo Tag::textField("limite_items", "size: 1", "maxlength: 1","class:  required numeric") ?></p>
		<p><label class='labelform' ><span for='fecha_inicio'><b>Fecha Inicio</b>:</span></label><?php echo Tag::textField("fecha_inicio", "size: 0", "maxlength: 0","class:  required dateISO") ?></p>
		<p><label class='labelform' ><span for='fecha_fin'><b>Fecha Fin</b>:</span></label><?php echo Tag::textField("fecha_fin", "size: 0", "maxlength: 0","class:  required dateISO") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
