<div id='mainContent'>

    <?php
    //echo View::getContent();
    //echo Tag::form('grupo/guardar/true');
    View::renderPartial("toolbarform");
    echo Tag::form("grupo/guardar/true");
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos del Rol</legend>
        <p><label class='labelform' ><span for='nombre_largo'><b>Nombre</b>:</span></label><?php echo Tag::textField("nombre_largo", "size: 40", "maxlength: 100", "class:  required") ?></p>
        <p><label class='labelform' ><span for='unico'><b>Unico</b>:</span></label><?php echo Tag::checkboxField("unico"); ?></p>
        <p><label class='labelform' ><span for='descripcion'><b>Descripción</b>:</span></label><?php echo Tag::textArea("descripcion", "cols: 40", "rows: 2"); ?></p>
    </fieldset>
    <!--<div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
    </div>-->
    <?php echo Tag::endForm(); ?>

</div>
