<fieldset class='ui-corner-all ui-widget-content'>
    <legend><b>Fecha</b></legend>
    <table id="tbl_menu" border="0" width="100%" class="empty">
        <tr>
            <td class="empty">
                <p><label class='labelform' ><span for='desde'>Desde:</span></label><?php echo Tag::textField("desde", "size: 12", "maxlength: 12","class:  dateISO") ?></p>
            </td><td class="empty">
                <p><label class='labelform' ><span for='hasta'>Hasta:</span></label><?php echo Tag::textField("hasta", "size: 12", "maxlength: 12","class:  dateISO") ?></p>
            </td>
        </tr>
    </table>
</fieldset>
<fieldset class='ui-corner-all ui-widget-content'>
    <legend><b>Duración</b></legend>
    <p><label class='labelform' ><span for='horas'>Tomar turnos con duración a partir de:</span></label><?php echo Tag::textField("horas", "size: 2", "maxlength: 2","class: ","value: 00").":";
        echo Tag::textField("minutos", "size: 2", "maxlength: 2","class: ","value: 00").":";
        echo Tag::textField("segundos", "size: 2", "maxlength: 2","class: ","value: 00");?></p>
</fieldset>

<script>
    $(function() {
        $("#desde").datepicker({ dateFormat: 'yy-mm-dd' });
    });
    $(function() {
        $("#hasta").datepicker({ dateFormat: 'yy-mm-dd' });
    });
</script>