<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('usuariomenu/guardar');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Usuariomenu</legend>
		<p><label class='labelform' ><span for='usuario_id'><b>Usuario</b>:</span></label><?php echo Tag::select("usuario_id", $Usuario->find("order: nombres"), "using: id,nombres", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
		<p><label class='labelform' ><span for='menu_id'><b>Menu</b>:</span></label><?php echo Tag::select("menu_id", $Menu->find("order: nombre"), "using: id,nombre", "use_dummy: yes","dummyValue: ''","class:  required") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
