<script type="text/javascript" src="http://localhost/pruebas/FusionCharts_Evaluation/Charts/FusionCharts1.js"></script>
<div class="ocultar">
    <table>
        <tr>
            <td>
                <input id="chk_barras" type="checkbox" checked /><label style="color:#3366FF; font-size:12px; font-weight:bold">BARRAS</label>
                <input id="chk_pastel" type="checkbox"/><label style="color:#3366FF; font-size:12px; font-weight:bold">PASTEL</label>
            </td>
            <td>
                <?php
                //$fun = new Funciones();
                //echo $fun->imprimir();
                ?>
                <!--<button type="button" id="printButton" onClick="FusionCharts.printManager.managedPrint()">Print Page</button>-->
            </td>
        </tr>
    </table>
</div>
<table style="height: 100%; width: 100%; background-color: #E5F1F4"  align="center">
    <tr><th colspan="2"> <div id="div_cabecera" style="height: 100%; width: 100%"></div></th></tr>
    <tr>
        <td>
            <table style="height: 100%;width: 100%" align="center">
                <tr>
                    <td>
                        <div id="maestro_chart" style="width: 100%; height: 100%" align="center">
                        </div>
                    </td>
                    <td>
                        <div id="div_pastel" style="width: 100%; height: 100%" align="center"></div>
                     <!--   <div id="detalle_chart" style="display:none;" align="center"></div>-->
                    </td>
                <tr><td colspan="2"><div id="div_estadisticaModulos" style="width: 100%; height: 100%" align="left"></div></td></tr>
            </table>
        </td>
    </tr>
</table>

<div id="div_imp" >

</div>

