<div id='mainContent'>

    <?php    //View::renderPartial('toolbarform');
    echo Tag::form('reportes/reporteTurnosAtendidosModuloXls');
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend><b>Fecha</b></legend>
        <p><label class='labelform' ><span for='desde'>Desde:</span></label><?php echo Tag::textField("desde", "size: 12", "maxlength: 12","class:  dateISO") ?></p>
        <p><label class='labelform' ><span for='hasta'>Hasta:</span></label><?php echo Tag::textField("hasta", "size: 12", "maxlength: 12","class:  dateISO") ?></p>
        <?php echo Tag::hiddenField('estado','value: 1')?>
    </fieldset>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend><b>Duración</b></legend>
        <p><label class='labelform' ><span for='horas'>Tomar turnos con duración a partir de:</span></label><?php echo Tag::textField("horas", "size: 2", "maxlength: 2","class: ","value: 00").":";
            echo Tag::textField("minutos", "size: 2", "maxlength: 2","class: ","value: 00").":";
            echo Tag::textField("segundos", "size: 2", "maxlength: 2","class: ","value: 00");?></p>
    </fieldset>
    <fieldset class="ui-corner-all ui-widget-content">
        <legend><b>Módulos</b></legend>
        <input id="chk_all_modulos" type="checkbox"/><label style="color:#3366FF; font-size:12px; font-weight:bold">Marcar/desmarcar todos</label><br/>
        <?php
        $col=0;
        $array_valores=array();
        foreach($lista_modulos_xls as $key=> $val) {
            $array_valores[]=Tag::checkboxField("chkmodulos[]", "value: $key","checked: ")."Módulo ".$val."&nbsp;&nbsp;";
        }
        echo "<table>";
        $cont_mod=count($lista_modulos_xls);
        $cont_filas=ceil($cont_mod/5);
        $x=$cont_filas*5;
        $y=$x-$cont_mod;
        for ($z=1;$z<=$y;$z++)
            $array_valores[]="";
        $cont_key=0;
        for ($f=1; $f<=$cont_filas; $f++) { //filas
            echo "<tr>";
            for ($c=1;$c<=5;$c++) { //columnas
                echo "<td>".$array_valores[$cont_key]."</td>";
                $cont_key+=1;
            }
            echo "</tr>";
        }
        echo "</table>";
        ?>

    </fieldset>

    <fieldset class="ui-corner-all ui-widget-content">
        <legend><b>Servicios</b></legend>
        <input id="chk_all_servicios" type="checkbox"/><label style="color:#3366FF; font-size:12px; font-weight:bold">Marcar/desmarcar todos</label><br/>
        <?php
        $col=0;
        $array_valores=array();
        foreach($lista_servicios_xls as $key=> $val) {
            $array_valores[]=Tag::checkboxField("chkservicios[]", "value: $key","checked: ").$val."&nbsp;&nbsp;";
        }
        echo "<table>";
        $cont_mod=count($lista_servicios_xls);
        $cont_filas=ceil($cont_mod/4);
        $x=$cont_filas*4;
        $y=$x-$cont_mod;
        for ($z=1;$z<=$y;$z++)
            $array_valores[]="";
        $cont_key=0;
        for ($f=1; $f<=$cont_filas; $f++) {
            echo "<tr>";
            for ($c=1;$c<=4;$c++) {
                echo "<td>".$array_valores[$cont_key]."</td>";
                $cont_key+=1;
            }
            echo "</tr>";
        }
        echo "</table>";

        ?>
    </fieldset>

    <?php echo Tag::submitButton("Procesar");?>
    <?php echo Tag::endForm(); ?>

</div>

<script>
    $(function() {
        $("#desde").datepicker({ dateFormat: 'yy-mm-dd' });
    });
    $(function() {
        $("#hasta").datepicker({ dateFormat: 'yy-mm-dd' });  
    })
    $("#chk_all_modulos").click(function(){
        var chks=$("input:checkbox[name^='chkmod']");
        chks.attr("checked",$(this).is(":checked"))
    })
    $("#chk_all_servicios").click(function(){
        var chks=$("input:checkbox[name^='chkser']");
        chks.attr("checked",$(this).is(":checked"))
    })
</script>