<?php
//print_r($menu_usuario);die();
$tabs = array();
foreach ($menu_usuario as $menu) {
    $tabs[] = array('caption' => $menu['nombre_modulo'], 'content' => Tag::treeview($menu['idModulo'], $menu['menu'], "options: animated: 'fast',collapsed: true, unique: true", "class: filetree"));
}
if ($tabs) {
    Tag::accordion($tabs, "options: event: 'mouseover', fillSpace: true,clearStyle: true ");
}
?>
<script type="text/javascript">
    function cargarPagina(url, tipo) {
        if (tipo == 'popup') {
            var Xpos = (screen.width / 2) - 285;
            var Ypos = (screen.height / 2) - 220;
            $("#content-center").html('');
            window.open(url, 'popup', 'width=600,height=480,scrollbars=yes,resizable=yes,left=' + Xpos + ',top=' + Ypos);
        } else {
            $("#content-center").load(url, function() {
            });
        }
    }
</script>