
<div id='mainContent'>
    <?php    //View::renderPartial('toolbarform');
    echo Tag::form('indices/indicesTurnosAtendidosModulos');
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Fecha</legend>
        <p><label class='labelform' ><span for='desde'><b>Desde</b>:</span></label><?php echo Tag::textField("desde", "size: 12", "maxlength: 12","class:  dateISO") ?></p>
        <p><label class='labelform' ><span for='hasta'><b>Hasta</b>:</span></label><?php echo Tag::textField("hasta", "size: 12", "maxlength: 12","class:  dateISO") ?></p>
        <?php echo Tag::hiddenField('estado','value: 1')?>
    </fieldset>
    <?php echo Tag::submitButton("Procesar");?>
    <?php echo Tag::endForm(); ?>
</div>
<script>
    $(function() {
        $("#desde").datepicker({ dateFormat: 'yy-mm-dd' });
    });
    $(function() {
        $("#hasta").datepicker({ dateFormat: 'yy-mm-dd' });
    });
</script>
