<!--
Se trata de crear una lista de checkbox para los grupos de usuarios
-->

<?php
$listagrupo=array();
$listagrupo1=array();
$query = new ActiveRecordJoin(array(
                "entities" => array("Usuario", "Grupo", "Grupousuario"),
                "fields" => array(
                        "{#Grupo}.id",
                        "{#Grupo}.nombre_largo"),
                "order"=> "{#Grupo}.nombre_largo ASC"
        //"conditions" => $condicion
));
foreach($query->getResultSet() as $result) {
    $listagrupo[$result->getId()]=$result->getNombreLargo();
}

$grupo=new Grupo();
$query= $grupo->find("order: nombre_largo");
foreach($query as $result) {
    $listagrupo[$result->getId()]=$result->getNombreLargo();
}
$grupos1 = array ('Configuradores del sistema');        //superadmin
//INICIO PREGUNTO SI TIENE PERMISO PARA USAR MODULO DE ATENCION DON TICKET O SIN TICKET
$empresa= new Empresa();
$buscaEmpresa=$empresa->findFirst();
$moduloConTicket=$buscaEmpresa->getModuloOperadores();
$moduloSinTicket=$buscaEmpresa->getModuloCajas();
if ($moduloConTicket==0)
    array_push($grupos1,'Operador con ticket');     //si no tiene el permiso entonces le añadimos a excepciones
if ($moduloSinTicket==0)
    array_push($grupos1,'Operador sin ticket');     //si no tiene el permiso entonces le añadimos a excepciones
//FIN
$listagrupo1 = array_diff($listagrupo, $grupos1);
?>

<fieldset class="ui-corner-all ui-widget-content">
    <legend>Grupo de Acceso</legend>
    <!--<p><label class='labelform' ><span for='descripcion'><b>Grupo de usuario:</b>:</span></label><?php //echo Tag::textField("descripcion", "size: 45", "maxlength: 45","class: required") ?></p>-->
    <!--<p><label class='labelform' ><span for='descripcion'><b>Letra</b>:</span></label><?php //echo Tag::selectStatic("grupo",$nombre_grupo,"class: required") ?></p>-->
    <!--<p><label class='labelform' ><span for='grupo'><b>Grupo</b>:</span></label><?php //echo Tag::select("grupo", $grupo->find("order: nombre_largo"), "using: id,nombre_largo", "use_dummy: no","dummyValue: ''","class:  required") ?></p>-->
    <!--<p><label class='labelform' ><span for='grupo'><b>Grupo</b>:</span></label><?php //echo Tag::select("grupo", $grupo->find("order: nombre_largo"), "using: id,nombre_largo", "use_dummy: no","dummyValue: ''","class:  required") ?></p>-->

    <table border="0">
        <tr>
            <td>
                <?php
                $grupousuario= new Grupousuario();
                $sistema=0;
                foreach ($listagrupo1 as $key=>$val) {
                    $grupo_id=$key;

                    if ($id) { //SI ES EDITAR
                        $buscaGrupousuario = $grupousuario->findFirst("grupo_id=$grupo_id AND usuario_id=$id");
                        //echo "grupo".$buscaGrupousuario->getGrupoId();
                        if ($buscaGrupousuario) {
                            if ($val=='Administradores' || $val=='Configuradores' ) {
                                if ($buscaGrupousuario) {
                                    $sistema+=1;
                                    if ($sistema==1) {
                                        echo Tag::hiddenField('sistema','value: 1');
                                        echo "<input type='checkbox' id='chk_grupo_0' name='chk_grupo_0' value='0' class='c_unico_1' onclick='seleccionar(1,0)' checked='cheked' />Sistema<br>";
                                    }
                                } else {
                                    echo $sistema+=1;
                                    if ($sistema==1) {
                                        echo Tag::hiddenField('sistema','value: 1');
                                        echo "<input type='checkbox' id='chk_grupo_0' name='chk_grupo_0' value='0' class='c_unico_1' onclick='seleccionar(1,0)' checked='cheked' disabled='disabled'/>Sistema<br>";
                                    }
                                }
                            }
                        }

                        if ($val=='Operador con ticket' | $val=='Operador sin ticket' | $val=='Pantallas' | $val=='Dispensadores') {
                            if ($buscaGrupousuario)
                                echo "<input type='checkbox' id='chk_grupo_$key' name='chk_grupo_$key' value='$grupo_id' class='c_unico_1' onclick='seleccionar(1,$grupo_id)' checked='cheked' />$val<br>";
                            else
                                echo "<input type='checkbox' id='chk_grupo_$key' name='chk_grupo_$key' value='$grupo_id' class='c_unico_1' onclick='seleccionar(1,$grupo_id)' />$val<br>";
                        }
                    } else { //SI ES NUEVO
                        if ($val=='Administradores' | $val=='Configuradores' ) {
                            $sistema+=1;
                            if ($sistema==1)
                                echo "<input type='checkbox' id='chk_grupo_0' name='chk_grupo_0' value='0' class='c_unico_1' onclick='seleccionar(1,0)' />Sistema<br>";
                        }
                        if ($val=='Operador con ticket' | $val=='Operador sin ticket' | $val=='Pantallas' | $val=='Dispensadores') {
                            echo "<input type='checkbox' id='chk_grupo_$key' name='chk_grupo_$key' value='$grupo_id' class='c_unico_1' onclick='seleccionar(1,$grupo_id)' />$val<br>";
                        }
                    }
                }
                ?>
            </td>
        </tr>
        <tr>
            <td width="350px">
                <div id="div_permisos_sistema">
                    <?php
                    //echo "usuario_id=".$id;
                    $menu=new Menu();
                    $tabs1=array();
                    $modulos= array(2,3);
                    if($modulos!=false) {
                        foreach ($modulos as $mod) {
                            $modulo= new Modulo();
                            $buscaModulo= $modulo->findFirst("id=$mod");
                            //$menupermisos=$menu->obtenerArbolMenuPermisos($mod);
                            $menupermisos=$menu->obtenerArbolMenuPermisos($id,$mod,$idreferencia=0);
                            $contpermisos='';
                            if(isset($menupermisos)) {
                                $contpermisos=Tag::treeview($mod, $menupermisos,"options: animated: 'fast',collapsed: true, unique: true","class: filetree");
                                $tabs1[]=array('caption'=>$buscaModulo->getNombre(),'content'=>$contpermisos);
                            }
                        }
                    }

                    $tabs[]=array("caption"=>'General','partial'=>'general');
                    Tag::accordion($tabs1,"options: event: 'mouseover', fillSpace: true,clearStyle: true ");
                    ?>
                </div>
            </td>
        </tr>
    </table>
</fieldset>


<script>
    if ($("#sistema").val()==1)
        $("#div_permisos_sistema").show();
    else
        $("#div_permisos_sistema").hide("");

    function seleccionar(val, v){
        if (v==0)
            $("#div_permisos_sistema").show(1000);
        else
            $("#div_permisos_sistema").hide("slow");
        var chks1=$("input:checkbox[name^='chk_grupo']");
        var nombre="";
        for (var x=0; x < chks1.length; x++) {
            nombre= chks1[x].id;
            var clase = chks1[x].className;
            var nom_clase="c_unico_"+val;
            if (clase==nom_clase){
                //$("#"+nombre).attr("checked", "checked");
            } else {
                $("#"+nombre).attr("checked", "");
            }
        }

        var chks1=$("input:checkbox[name^='chk_grupo']");
        var nombre="";
        for (var x=0; x < chks1.length; x++) {
            value= chks1[x].value;
            nombre= chks1[x].id;
            var clase = chks1[x].className;
            //alert (clase);
            //var nom_clase="c_modulos_"+val;
            if (clase=="c_unico_1"){
                if (v!=value){
                    $("#"+nombre).attr("checked", "");
                }

            }
        }
    }
</script>