<!--
Se trata de crear una lista de checkbox para los grupos de usuarios
-->
<!--SELECT g.id, nombre_largo, gu.usuario_id
FROM grupo g
LEFT JOIN grupousuario gu ON gu.grupo_id=g.id AND usuario_id=69-->

<?php
?>

<fieldset class="ui-corner-all ui-widget-content">
    <legend>Rol</legend>
    <table border="0">
        <tr>
            <td>
                <?php
                //-- busco la configuracion del sistema
                $array_roles_no_permitidos=array();
                $where ="1";

                //-- busco si el usuario conectado es superadmin
                /*$dataUsuario = SessionNamespace::get('datosUsuarioSMC');
                $username = $dataUsuario->getUsername();
                if ($username!='superadmin')*/
                $array_roles_no_permitidos[]=1; //rol configuradores del sistema

                $empresa = new Empresa();
                $bucaEmpresa = $empresa->findFirst();
                $modulo_operadores = $bucaEmpresa->getModuloOperadores();
                $modulo_cajas = $bucaEmpresa->getModuloCajas();
                if ($modulo_operadores==0)
                    $array_roles_no_permitidos[]=5; //rol operadores con ticket
                if ($modulo_cajas==0)
                    $array_roles_no_permitidos[]=7; //rol operadores sin ticket
                
                $where.=  " AND g.id NOT IN (".  implode(',', $array_roles_no_permitidos).")";

                $db = DbBase::rawConnect();
                if ($id) { //si es editar
                    $sql = "SELECT g.id, nombre_largo, g.unico, gu.usuario_id
                    FROM grupo g
                    LEFT JOIN grupousuario gu ON gu.grupo_id=g.id AND usuario_id=$id WHERE $where ORDER BY unico DESC";
                } else {
                    $sql = "SELECT g.id, nombre_largo, g.unico FROM grupo g WHERE $where ORDER BY unico DESC";
                }
                $result = $db->query($sql);
                while ($row = $db->fetchArray($result)) {
                    //echo $dataUsuario->setSesionId($row['id']);
                    $val = $row['nombre_largo'];
                    $grupo_id = $row['id'];
                    if ($id)
                        $usuario_id = $row['usuario_id'];
                    else
                        $usuario_id = "";
                    $unico = $row['unico'];
                    if ($unico == 1) {    //si solo puede seleccionar un solo rol
                        if ($usuario_id)    //si es != null  => esta asignado el rol/grupo al usuario
                            echo "<input type='checkbox' id='chk_grupo_$grupo_id' name='chk_grupo_$grupo_id' value='$grupo_id' class='c_unico' onclick='seleccionar(1,$grupo_id)' checked='checked' />$val<br>";
                        else
                            echo "<input type='checkbox' id='chk_grupo_$grupo_id' name='chk_grupo_$grupo_id' value='$grupo_id' class='c_unico' onclick='seleccionar(1,$grupo_id)' />$val<br>";
                    } else {
                        if ($usuario_id)
                            echo "<input type='checkbox' id='chk_grupo_$grupo_id' name='chk_grupo_$grupo_id' value='$grupo_id' class='c_varios' onclick='seleccionar(0,$grupo_id)' checked='checked'/>$val<br>";
                        else
                            echo "<input type='checkbox' id='chk_grupo_$grupo_id' name='chk_grupo_$grupo_id' value='$grupo_id' class='c_varios' onclick='seleccionar(0,$grupo_id)'/>$val<br>";
                    }
                }
                ?>
            </td>
        </tr>
    </table>
</fieldset>


<script>
    function seleccionar(val, grupo_id) {
        nombre = "chk_grupo_" + grupo_id;
        if (val == 1) //unico
            deshabilitar_todos(nombre); //todos menos nombre
        else if (val == 0)    //no unico
            deshabilitar_todos_de_clase('c_unico');
    }

    function deshabilitar_todos(excepcion) {
        var chks1 = $("input:checkbox[name^='chk_grupo']");
        var nombre = "";
        for (var x = 0; x < chks1.length; x++) {
            nombre = chks1[x].id;
            if (nombre != excepcion)
                $("#" + nombre).attr("checked", "");
        }
    }

    function deshabilitar_todos_de_clase(nom_clase) {
        var chks1 = $("." + nom_clase);
        var nombre = "";
        for (var x = 0; x < chks1.length; x++) {
            nombre = chks1[x].id;
            $("#" + nombre).attr("checked", "");
        }
    }
</script>