<div id='mainContent'>

    <?php
    //echo View::getContent();
    //echo Tag::form('usuario/guardar');
    ?>
    <?php
    View::renderPartial("toolbarform");
    echo Tag::form("usuario/guardar","enctype: multipart/form-data");
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Usuario</legend>
        <p><label class='labelform' ><span for='nombres'><b>Nombres</b>:</span></label><?php echo Tag::textField("nombres", "size: 60", "maxlength: 150","class:  required") ?></p>
        <p><label class='labelform' ><span for='username'><b>Username</b>:</span></label><?php echo Tag::textField("username", "size: 25", "maxlength: 25","class:  required") ?></p>
        <!--<p><label class='labelform' ><span for='ci'><b>Ci</b>:</span></label><?php //echo Tag::textField("ci", "size: 15", "maxlength: 15","class: ") ?></p>
        <p><label class='labelform' ><span for='telefono'><b>Telefono</b>:</span></label><?php //echo Tag::textField("telefono", "size: 15", "maxlength: 15","class: ") ?></p>
        <p><label class='labelform' ><span for='movil'><b>Movil</b>:</span></label><?php //echo Tag::textField("movil", "size: 15", "maxlength: 15","class: ") ?></p>
        <p><label class='labelform' ><span for='estado'><b>Estado</b>:</span></label><?php //echo Tag::textField("estado", "size: 20", "maxlength: 20","class: ") ?></p>
        <p><label class='labelform' ><span for='email'><b>Email</b>:</span></label><?php //echo Tag::textField("email", "size: 100", "maxlength: 100","class:  email") ?></p>
        <p><label class='labelform' ><span for='descripcion'><b>Descripcion</b>:</span></label><?php //echo Tag::textField("descripcion", "size: 0", "maxlength: 0","class: ") ?></p>-->
    </fieldset>

    <?php
    $tabs[]=array("caption"=>'General','partial'=>'general');
    $tabs[]=array("caption"=>'Rol','partial'=>'grupousuario');
    Tag::tab($tabs);
    ?>

    <!--<div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
    </div>-->
    <?php echo Tag::endForm(); ?>
</div>