<div id='mainContent'>

<?php echo View::getContent();
      //echo Tag::jqGrid("caption: 'Caja'");
//       echo Tag::jqGrid("caption: 'Seleccione una Caja'","typewinedit: 'popup'","addbutton: false","editbutton: false","optwinedit: 'width=780,height=490,left=115,top=100,scrollbars=yes'","height: 260");

?>
</div>
    
<fieldset class='ui-corner-all ui-widget-content ui-state-default' height="100" width="290">
       <legend>Seleccione una Caja</legend>
       <p><label class='labelform' ><span for='id'><b>Caja #</b></span></label><?php echo Tag::select("numero", $Caja->find("order: numero"), "using: id,numero", "use_dummy: yes","dummyValue: ''");?></p>
</fieldset>
<div class='ui-corner-all ui-widget-content'>
       <input id="seleccionar" type="button" value="Aceptar"/>
</div>
	<?php echo Tag::form("listacaja/activarcaja");
        echo Tag::endForm(); ?>


<script>
    $("#seleccionar").click(function(){
        var numerocaja='NULL';
        var Xpos=(screen.width/2)+285;
        var Ypos=(screen.height/2)+220;
        var direccion="";
        numerocaja=$("#numero").val();
        if( numerocaja == "" )
           alert('Por favor seleccione una Caja!');
        else{

           $.post("<?php echo Utils::getKumbiaUrl("listacaja/activarcaja")?>",{
            action:'activarcaja',
            id:$("#numero[id]").val()
           });
           $("#content-center").html('');
           direccion="<?php echo Utils::getKumbiaUrl("operador/index/")?>"
           window.open(direccion+numerocaja,'popup','width=280,height=280,scrollbars=no,directories= no,resizable=no,status=no,location=no,menubar=no,left='+Xpos+',top='+Ypos);
           // if (window.focus) {newwindow.focus()}
           return false;
        }
     });
</script>
