<form id="frm_datos">
    <input type="button" value="Guardar" id="btn_guardar" class="boton_operador"/>
    <div id="div_datos"><?php echo $tabla; ?></div>
</form>
<script>
    //$(document).ajaxStart($.blockUI).ajaxStop($.unblockUI);
    $("#btn_guardar").click(function() {
        $.blockUI({message: "Guardando datos…"});
//        $.post("<?php echo Utils::getKumbiaUrl("permiso/asignarRolMenu") ?>",
//                $("#frm_datos").serialize() // Formulario
//                , function(json) {
//                    $.unblockUI();
//                }, 'json');
        $.ajax({
            data: $("#frm_datos").serialize(),
            type: "POST",
            dataType: "json",
            url: "<?php echo Utils::getKumbiaUrl("permiso/asignarRolMenu") ?>",
            timeout: 90000,
            success: function(data) {
                //$("#principal").unblock();
                $.unblockUI();
            },
            error: function(x, t, m) {	//error por timeout
                $.unblockUI();
                if (t === 'timeout') {
                    alert("No se pudo guardar los datos");
                } else {
                    alert("Datos guardados con exito!");
                    location.reload(); 
                }
            }
        });
    });
    
    
</script>
