<div id="div_tabs" class="ocultar">
<?php
$tabs[]=array("caption"=>'Turnos Atendios x Modulos','partial'=>'ReporteGrafico');
$tabs[]=array("caption"=>'Turnos Atendios x Servicio','partial'=>'ReporteServicio');
$tabs[]=array("caption"=>'Turnos Semanales','partial'=>'reporteTurnoSemanales');
$tabs[]=array("caption"=>'Detalle Turnos','partial'=>'reporteTurnosXLS');
$tabs[]=array("caption"=>'Reporte Turnero','partial'=>'reporteTurnero');
$tabs[]=array("caption"=>'Calidad Servicio','partial'=>'ReporteCalidadServicio');
$tabs[]=array("caption"=>'Preguntas Calificadas','partial'=>'PreguntasCalificadas');
Tag::tab($tabs);
?>
</div>