<?php
/*$tabs[]=array('caption'=>'Tab 1','content'=>'contenido tab 1');
$tabs[]=array('caption'=>'Tab 2','content'=>'contenido tab 2');
$tabs[]=array('caption'=>'Tab 3','content'=>'contenido tab 3');
$tabs[]=array('caption'=>'Tab 4','content'=>'contenido tab 4');
Tag::tab($tabs);
echo "<br/>";*/
//echo Tag::jqGrid('grdprueba','controller: provincia','width: 600',"typewinedit: 'popup'");
//echo "<div style='text-align:center;width:220px;height:150px;position:absolute;margin-left:-110px;top:50%; left:50%;margin-top:-75px;'><h1>LOGO</h1></div>";
//echo Router::getController();
?>
