<!--
Configurar tv
-->

<fieldset class="ui-corner-all ui-widget-content">
    <legend>Configurar Servidor Node</legend>
    <p><label class='labelform' ><span for='pc_difusion'><b>Ip</b>:</span></label><?php echo Tag::textField("ip_servidor_node", "size: 20", "maxlength: 50","class: ") ?></p>
    <p><label class='labelform' ><span for='puerto'><b>Puerto</b>:</span></label><?php echo Tag::numericField("puerto_servidor_node", "size: 5", "maxlength: 10","class: ") ?></p>
</fieldset>