<?php 
  $estmail='';
  $clsemail='class: required email';
  $chkemail='checked: true';
  if(!Tag::getValueFromAction('emailadmin')){
      $estmail='disabled: true';
      $clsemail='class: email';
      $chkemail='';
  }

?>

<fieldset class="ui-corner-all ui-widget-content">
    <legend><?php echo Tag::checkboxField('emailadminchk',$chkemail)?><label>Activar recurso de correo el&eacute;ctronico</label></legend>
    <p><label><span>Email para envio de mensajes</span></label><br/>
    <?php echo Tag::textField('emailadmin','size: 50','maxlength: 70',$estmail,$clsemail)?>
    </p>
    <p></p>
</fieldset>
<script type="text/javascript">
    $(function(){
        $("#emailadminchk").click(function(){
            if($(this).is(":checked")){
                $("#emailadmin").attr("disabled",false);
                $("#emailadmin").addClass("required");
            }
            else{
                $("#emailadmin").attr("disabled",true);
                $("#emailadmin").val("");
                $("#emailadmin").removeClass("required");
            }
        });
    });
</script>

