<style>
    #div_cargando {
        position: absolute;
        /*left: 20px;*/
        top: 180px;
        border: none;
        width: 100%;
    }
</style>
<link rel='STYLESHEET' type='text/css' href='../../css/impresion/estilo_imprimir.css' media='print'>
<link rel='STYLESHEET' type='text/css' href='../../css/varios/menu_desplegable.css'>

<!-- OPCIONES -->
<div id="div_menu" class="ocultar">
    <div class="panel">
        <div align="top" style="height: 90%;width: 100%">
            <fieldset class='ui-corner-all ui-widget-content' style="height: 100%">
                <table  id="tbl_menu" border="0" width="100%">
                    <tr>
                        <td width="200px" height="500px"  style="vertical-align:top">
                            <table border="0" style="vertical-align: top; width: 100%;height: 100%">
                                <tr>
                                    <td>
                                        <fieldset class='ui-corner-all ui-widget-content'>
                                            <legend><b>Fecha</b></legend>
                                            <table width="100%" >
                                                <tr>
                                                    <td class="empty">
                                                        <label class='labelform' style="width: 60px"><span for='desde'>Desde:</span></label><?php echo Tag::textField("desde", "size: 8", "maxlength: 12","class:  dateISO") ?>
                                                    </td>
                                                    <td class="empty">
                                                        <label class='labelform' style="width: 60px"><span for='hasta'>Hasta:</span></label><?php echo Tag::textField("hasta", "size: 8", "maxlength: 12","class:  dateISO") ?>
                                                    </td>
                                                </tr>
                                            </table>
                                        </fieldset>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <table width="100%" >
                                            <tr>
                                                <td class="empty">
                                                    <fieldset class='ui-corner-all ui-widget-content'>
                                                        <legend><b>Duraci&oacute;n</b></legend>
                                                        <label class='labelform' style="width: 150px"><span for='horas'>Tomar turnos con duraci&oacute;n a partir de:</span></label><?php echo Tag::textField("horas", "size: 2", "maxlength: 2","class: ","value: 00").":";
                                                        echo Tag::textField("minutos", "size: 2", "maxlength: 2","class: ","value: 00").":";
                                                        echo Tag::textField("segundos", "size: 2", "maxlength: 2","class: ","value: 00");?>
                                                    </fieldset>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <fieldset class='ui-corner-all ui-widget-content'>
                                            <legend><b>Sucursales</b></legend>
                                            <table border="1">
                                                <tr>
                                                    <th>No</th>
                                                    <th>Sucursal
                                                    </th>
                                                    <th>Fecha y Hora <br> de última sincronización</th>
                                                </tr>
                                                <?php
                                                $cont=0;
                                                $sucursal=new Sucursal();
                                                $buscaSucursal  =$sucursal->find("order: alias_sucursal");
                                                $array_valores=array();
                                                foreach($buscaSucursal as $result) {
                                                    $cont+=1;
                                                    $sucursal_id    =$result->getId();
                                                    $alias_sucursal =$result->getAliasSucursal();
                                                    $sinchistorial      =new Sinchistorial();
                                                    $buscaSinchistorial = $sinchistorial->findFirst("sucursal_id=$sucursal_id","order: id","limit: 1");
                                                    if($buscaSinchistorial) {
                                                        $fecha_ultima_sinc=$buscaSinchistorial->getFechaSincronizacion();
                                                        $hora_ultima_sinc=$buscaSinchistorial->getHoraSincronizacion();
                                                    } else {
                                                        $fecha_ultima_sinc="2010-01-01";
                                                        $hora_ultima_sinc="00:00:00";
                                                    }

                                                    echo "<tr><td>".$cont."</td>";
//                                                echo "<td> <input type='checkbox' id='checksucursal' name='check_sucursal' value='$sucursal_id' onclick='checkSucursales()'/>$alias_sucursal</td>";
                                                    $array_valores[]=Tag::checkboxField("chksucursal[]", "value: $sucursal_id","checked: ","onclick:   checkSucursales()").$alias_sucursal."&nbsp;&nbsp;";
                                                    echo "<td>".$array_valores[$cont-1]."</td>";
                                                    echo "<td>".$fecha_ultima_sinc." ".$hora_ultima_sinc."</td></tr>";
                                                }

                                                ?>
                                            </table>
                                        </fieldset>
                                        <fieldset class='ui-corner-all ui-widget-content'>
                                            <input id="chk_all_modulos" type="checkbox"/><label style="color:#3366FF; font-size:12px; font-weight:bold">Marcar/desmarcar todos (MODULOS)</label><br/>
                                            <div id="div_modulos" align="center">
                                            </div>
                                        </fieldset>
                                        <fieldset class='ui-corner-all ui-widget-content'>
                                            <input id="chk_all_servicios" type="checkbox"/><label style="color:#3366FF; font-size:12px; font-weight:bold">Marcar/desmarcar todos (SERVICIOS)</label><br/>
                                            <div id="div_servicios" align="center">
                                            </div>
                                        </fieldset>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <table width="100%" >
                                            <tr><td><center><input type="button" id="boton" value="Aceptar" title="Aceptar" > </center></td></tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>

                    </tr>
                </table>
            </fieldset>
        </div>
        <div style="clear:both;"></div>
    </div>
    <a class="trigger" href="#">Opciones<br>de reporte</a>
</div>

<div id="div_cargando" style="display:none; color: green;">
    <center>
    Cargando...<?php echo "<td>".Tag::image("cargando.gif","width: 30px","height: 30px"); ?>
    </center>
</div>

<div id="container">
    <?php
    $tabs[]=array("caption"=>'Turnos Atendios x Modulos','partial'=>'ReporteGrafico');
    $tabs[]=array("caption"=>'Turnos Atendios x Servicio','partial'=>'ReporteServicio');
    //$tabs[]=array("caption"=>'Turnos Semanales','partial'=>'reporteTurnoSemanales');
    $tabs[]=array("caption"=>'Detalle Turnos','partial'=>'reporteTurnosXLS');
    //$tabs[]=array("caption"=>'Reporte Turnero','partial'=>'reporteTurnero');
    $tabs[]=array("caption"=>'Calidad Servicio','partial'=>'ReporteCalidadServicio');
    //$tabs[]=array("caption"=>'Preguntas Calificadas','partial'=>'PreguntasCalificadas');
    Tag::tab($tabs);
    ?>
</div>

<script type="text/javascript">
$(document).ready(function(){
	$(".trigger").click(function(){
		$(".panel").toggle("fast");
		$(this).toggleClass("active");
		return false;
	});
});
</script>

<script>
    var encontro=false;
    var ids="";
    function obtener_modulos_servicios(){
        document.getElementById("div_modulos").innerHTML = "";
        document.getElementById("div_servicios").innerHTML = "";
        //$("#cargando").css("display", "inline");
        $.post("<?php echo Utils::getKumbiaUrl("reportes_sucursales/obtenerModulosServicios")?>", {
            sucursal_id: arregloIdSucursal.join(',')
            //            nombres_sucursal: arreglonombre.join(',')
        }
        ,function(json){
            // $("#cargando").css("display", "none");
            document.getElementById("div_modulos").innerHTML = json.modulos;
            document.getElementById("div_servicios").innerHTML = json.servicios;
        },'json');
    }
    function validar(){
        var activos=$("input:checked[name^='chkmodulos']");
        var cont=activos.length;
        if (cont ==0){
            alert("Seleccione la sucursal y al menos un módulo")
            encontro=false;
            return 0;
        }
        else
        {
            encontro=true;
            cheks();
            chekservicio();
        }

    }
    var arregloIdSucursal=new Array();

    var arregloArea=new Array();
    var arreglo=new Array();
    var arregloGrupo=new Array();
    var arregloservicio=new Array();
    var servicio, estado="No Hay Datos";
    var marcar_modulos=false;
    function checkSucursales(){
        var chksucursal=$("input:checkbox[name^='chksucursal']");
        var ids="";
        var con=0;
        arregloIdSucursal=[];

        for (var x=0; x < chksucursal.length; x++) {
            if (chksucursal[x].checked) {
                ids=ids+chksucursal[x].value+",";
                arregloIdSucursal[con]=chksucursal[x].value;
                con++;
            }
        }
        obtener_modulos_servicios();
    }

    function chekArea(){
        var chkareas=$("input:checkbox[name^='chkareas']");
        var ids="";
        var con=0;
        arregloArea=[];
        for (var x=0; x < chkareas.length; x++) {
            if (chkareas[x].checked) {
                ids=ids+chkareas[x].value+",";
                arregloArea[con]=chkareas[x].value;
                con++;
            }
        }
        $.post("<?php echo Utils::getKumbiaUrl("reportes/GraficaChkModulos")?>", {
            areas: arregloArea.join(",")
        }
        ,function(json){
            document.getElementById("div_modulos").innerHTML = json.cks;
        },'json');

    }
    function cheks(){
        var chkmodulos=$("input:checkbox[name^='chkmodulos']");
        var ids="";
        arreglo=[];
        var con=0;
        for (var x=0; x < chkmodulos.length; x++) {
            if (chkmodulos[x].checked) {
                ids=ids+chkmodulos[x].value+",";
                arreglo[con]= chkmodulos[x].value;

                con++;
            }


        }
    }
    function chekGrupo(){
        var chkgrupo=$("input:checkbox[name^='chkgruposervicio']");
        var ids="";
        var con=0;
        arregloGrupo=[];
        for (var x=0; x < chkgrupo.length; x++) {
            if (chkgrupo[x].checked) {
                ids=ids+chkgrupo[x].value+",";
                arregloGrupo[con]=chkgrupo[x].value;
                con++;
            }
        }
        $.post("<?php echo Utils::getKumbiaUrl("reportes/GraficarChkServicios")?>", {
            grupos_servicios: arregloGrupo.join(",")
        }
        ,function(json){
            // document.getElementById("div_Servicio").innerHTML = json.chkservicio;
        },'json');

    }
    function chekservicio(){
        var chks=$("input:checkbox[name^='chkservicios']");
        var ids="";
        var con=0;
        arregloservicio=[];
        for (var x=0; x < chks.length; x++) {
            if (chks[x].checked) {
                ids=ids+chks[x].value+",";
                arregloservicio[con]=chks[x].value;
                con++;
            }
        }

    }
    $("#boton1").click(function(){
        validar();
        $.post("<?php echo Utils::getKumbiaUrl("reportes_sucursales/LLenaQuerySucursal");?>", {
            sucursal_id:arregloIdSucursal.join(','),
            desde: $("#desde").val(),
            hasta: $("#hasta").val(),
            chkmodulos: arreglo.join(','),
            chkservicios: arregloservicio.join(','),
            horas:      $("#horas").val(),
            minutos:    $("#minutos").val(),
            segundos:   $("#segundos").val()

        });
    })
    $("#boton").click(function(){
        $(".panel").toggle("fast");
        $(".trigger").toggleClass("active");
        validar();
        $.post("<?php echo Utils::getKumbiaUrl("reportes_sucursales/LLenaQuerySucursal");?>", {
            sucursal_id:arregloIdSucursal.join(','),
            desde: $("#desde").val(),
            hasta: $("#hasta").val(),
            chkmodulos: arreglo.join(','),
            chkservicios: arregloservicio.join(','),
            horas:      $("#horas").val(),
            minutos:    $("#minutos").val(),
            segundos:   $("#segundos").val()
        } ,function(json){  
            if(json.html=="Exitoso")
            {
                //   alert("hola Ex");
                tablaXLS();
                parametrosBBDD();
                if ($('#chk_pastel').is(':checked'))ActualizaPastel();
                if ($('#chk_barras').is(':checked')) ActualizarBarras();
                servicio=arregloservicio;                

            }
            else alert("No Hay Datos");
        },'json')
    }
)

    $(function() {
        $("#desde").datepicker({ dateFormat: 'yy-mm-dd' });
    });
    $(function(){
        $("#hasta").datepicker({ dateFormat: 'yy-mm-dd' });
    });
    $("#chk_all_areas").click(function(){
        var chkareas=$("input:checkbox[name^='chkareas']");
        chkareas.attr("checked",$(this).is(":checked"))
        for (var x=0; x < chkareas[x].length; x++) {
            arregloArea[x]=chkareas[x].value;
        }
        chekArea();
        if(marcar_modulos==true){
            $("#chk_all_modulos").click();
            $("#chk_all_gruposervicios").click();
            $("#chk_all_servicios").click();
            marcar_modulos=false;
        }


    })

    $("#chk_all_modulos").click(function(){
        var chkmodulos=$("input:checkbox[name^='chkmodulos']");
        chkmodulos.attr("checked",$(this).is(":checked"))
        for (var x=0; x < chkmodulos.length; x++) {
            arreglo[x]=chkmodulos[x].value;
        }
        cheks();
        //        $("#chk_all_gruposervicios").click();
        chekGrupo();
        marcar_modulos=true;
    })
    //    function desmarcar(){
    //        $("#chk_all_modulos").click();
    ////            if ($("#chk_all_modulos").checked) this.checked=false;
    ////            else this.checked=true;
    //    }

    $("#chk_all_gruposervicios").click(function(){
        //  alert("todos grupos");
        var chkgruposervicio=$("input:checkbox[name^='chkgruposervicio']");
        chkgruposervicio.attr("checked",$(this).is(":checked"))
        for (var x=0; x <chkgruposervicio.length; x++) {
            arregloGrupo[x]=chkgruposervicio[x].value;
        }
        chekGrupo();
        //chekservicio();
    })

    $("#chk_all_servicios").click(function(){
        var chkserv=$("input:checkbox[name^='chkservicios']");
        chkserv.attr("checked",$(this).is(":checked"))
        for (var x=0; x < chkserv.length; x++) {
            //  alert(chkserv[x].value);
            arregloservicio[x]=chkserv[x].value;
        }
        //        alert(arregloservicio[0]);
        chekservicio();
        marcar_modulos=true;
    })
    $("#chk_pastel").click(function(){

        if ($('#chk_pastel').is(':checked')) {
            ActualizaPastel();}
        else
            document.getElementById("div_pastel").innerHTML = "";
    })

    function ActualizaPastel(){
        $.post("<?php echo Utils::getKumbiaUrl("reportes_sucursales/Graficador1")?>", {
            modulos: arreglo.join(","),
            sucursal_id:arregloIdSucursal.join(','),
            desde: $("#desde").val(),
            hasta:  $("#hasta").val(),
            chkservicios: arregloservicio.join(','),
            Grafica:"Pastel"
        }
        ,function(json){
            document.getElementById("div_pastel").innerHTML = json.html;
        },'json');
    }

    $("#chk_barras").click(function(){
        if ($('#chk_barras').is(':checked')) {
            ActualizarBarras();
        }else
            document.getElementById("maestro_chart").innerHTML = "";
    })
    function ActualizarBarras(){
        $.post("<?php echo Utils::getKumbiaUrl("reportes_sucursales/Graficador1")?>", {
            sucursal_id:arregloIdSucursal.join(','),
            modulos: arreglo.join(","),
            desde: $("#desde").val(),
            hasta:  $("#hasta").val(),
            chkservicios: arregloservicio.join(','),
            Grafica:"Barras"
        }
        ,function(json){
            document.getElementById("maestro_chart").innerHTML = json.html;
        },'json');

    }

    $("#chk_barrasServicio").click(function(){
        if ($('#chk_barrasServicio').is(':checked')) {
            $.post("<?php echo Utils::getKumbiaUrl("reportes_sucursales/GraficadorServicioBarras")?>", {
                sucursal_id:arregloIdSucursal.join(','),
                modulos: arreglo.join(","),
                desde: $("#desde").val(),
                hasta:  $("#hasta").val(),
                Tipo:"Barras",
                chkservicios: arregloservicio.join(',')
            }
            ,function(json){
                document.getElementById("div_cabeceraServicio").innerHTML = json.html;
                document.getElementById("div_ServicioBarras").innerHTML = json.grafica;
                document.getElementById("div_serviciotabla").innerHTML = json.tabla;
            },'json');
        }
        else{
            document.getElementById("div_ServicioBarras").innerHTML = "";
            document.getElementById("div_serviciotabla").innerHTML = "";
        }
    })
    $("#chk_pastelServicio").click(function(){
        if ($('#chk_pastelServicio').is(':checked')) {
            $.post("<?php echo Utils::getKumbiaUrl("reportes_sucursales/GraficadorServicioBarras")?>", {
                sucursal_id:arregloIdSucursal.join(','),
                modulos: arreglo.join(","),
                desde: $("#desde").val(),
                hasta:  $("#hasta").val(),
                Tipo:"Pastel",
                chkservicios: arregloservicio.join(',')
            }
            ,function(json){
                document.getElementById("div_cabeceraServicio").innerHTML = json.html;
                document.getElementById("div_Serviciopastel").innerHTML = json.grafica;
                document.getElementById("div_serviciotabla").innerHTML = json.tabla;
            },'json');
        }
        else
            document.getElementById("div_Serviciopastel").innerHTML = "";
    })
    $("#chk_barrasCalidad").click(function(){
        if ($('#chk_barrasCalidad').is(':checked')) {
            var tipo='barras';
            $.post("<?php echo Utils::getKumbiaUrl("reportes_sucursales/CalidadServicio")?>", {
                modulos: arreglo.join(","),
                sucursal_id:arregloIdSucursal.join(','),
                desde: $("#desde").val(),
                hasta:  $("#hasta").val(),
                graficar:tipo,
                chkservicios: arregloservicio.join(',')
            }
            ,function(json){
                document.getElementById("div_TituloCalidad").innerHTML = json.text;
                document.getElementById("div_calidadServicio").innerHTML = json.graficaCalidad;
                document.getElementById("div_TablacalidadServicio").innerHTML = json.tabla;
            },'json');
        }
        else
            document.getElementById("div_calidadServicio").innerHTML = "";
    })
    $("#chk_pastelCalidad").click(function(){
        if ($('#chk_pastelCalidad').is(':checked')) {
            var tipo='pastel';
            $.post("<?php echo Utils::getKumbiaUrl("reportes_sucursales/CalidadServicio")?>", {
                modulos: arreglo.join(","),
                sucursal_id:arregloIdSucursal.join(','),
                desde: $("#desde").val(),
                hasta:  $("#hasta").val(),
                graficar:tipo,
                chkservicios: arregloservicio.join(',')
            }
            ,function(json){
                document.getElementById("div_TituloCalidad").innerHTML = json.text;
                document.getElementById("div_pastelCalidad").innerHTML = json.graficaCalidad;
                document.getElementById("div_TablacalidadServicio").innerHTML = json.tabla;
            },'json');
        }
        else{
            document.getElementById("div_pastelCalidad").innerHTML = "";
            document.getElementById("div_TablacalidadServicio").innerHTML = "";
        }
    })


    function ventanaSecundaria (URL){
        var Xpos=0;
        var Ypos=0;
        window.open(URL,'ventana1','width=600,height=480,scrollbars=yes,resizable=yes,left='+Xpos+',top='+Ypos)
        document.getElementById("div_cuadro").innerHTML = URL;
        $.post("<?php echo Utils::getKumbiaUrl("reportes/verGraficoHoras")?>", {
            action: 'verGraficoHoras',
            DatosURL: URL
        }
        ,function(json){
            document.getElementById("div_cuadro").innerHTML =json.v1;
        },'json');

    }


    $('#desde').click(function(){
        document.getElementById("div_cuadro").innerHTML="";
    });
    $('#hasta').click(function(){
        document.getElementById("div_cuadro").innerHTML="";
    });
    $('#cajas').click(function(){
        document.getElementById("div_cuadro").innerHTML="";
    });
    $('#servicios').click(function(){
        document.getElementById("div_cuadro").innerHTML="";
    });

    /*function cargarPagina(url,tipo){
        if(tipo=='popup'){
            var Xpos=(screen.width/2)-285;
            var Ypos=(screen.height/2)-220;
            $("#content-center").html('');
            window.open(url,'popup','width=600,height=480,scrollbars=yes,left='+Xpos+',top='+Ypos);
        }else{
            $("#content-center").load(url,function(){
            });
        }
    }*/
    function Graficar(){
        $.post("<?php echo Utils::getKumbiaUrl("reportes/ejemplo")?>", {

        }
        ,function(json){
            document.getElementById("mi_div").innerHTML =json.html;
        },'json');
    }
    var $tabs = $('#tab-1').tabs();

    function verGraficoHoras(id_modulo,dia,tot_t_atendidos_x_dia,tot_t_anulados_x_dia,duracion_total,duracion_promedio,desde,hasta,id_servicio,forma_duracion){
        $.post("<?php echo Utils::getKumbiaUrl("reportes/verGraficoHoras")?>", {
            id_modulo:              id_modulo,
            dia:                    dia,
            tot_t_atendidos_x_dia:  tot_t_atendidos_x_dia,
            tot_t_anulados_x_dia:   tot_t_anulados_x_dia,
            duracion_total:         duracion_total,
            duracion_promedio:      duracion_promedio,
            desde:                  desde,
            hasta:                  hasta,
            id_servicio:            id_servicio,
            forma_duracion:         forma_duracion
        }
        ,function(json){
            document.getElementById("tabla").innerHTML =json.v2;
            var chart;
            chart = new Highcharts.Chart({
                chart: {
                    renderTo: 'div_cuadro',
                    defaultSeriesType: 'line',
                    marginRight: 130,
                    marginBottom: 50
                },
                title: {
                    text: json.titulo,
                    x: -20 //center
                },
                subtitle: {
                    text: '',
                    x: -20
                },
                xAxis: {
                    categories: ['8-9', '9-10', '10-11', '11-12', '12-13', '13-14', '14-15', '15-16', '16-17', '17-18', '18-19']
                },
                yAxis: {
                    title: {
                        text: 'Turnos'
                    },
                    plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                },
                tooltip: {
                    formatter: function() {
                        return '<b>'+ this.series.name +'</b><br/>'+
                            this.x +': '+ this.y +'TA';
                    }
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'top',
                    x: -10,
                    y: 100,
                    borderWidth: 0
                },
                series: json.v1
            });
        },'json');
    }
    function verGraficoSemana(id_modulo,ttat,ttan,desde,hasta,lu,ma,mi,ju,vi,sa,dom){
        $.post("<?php echo Utils::getKumbiaUrl("reportes/verGrafico")?>", {
            id_modulo:id_modulo,
            subtotal_total_turnos_atendidos: ttat,
            subtotal_total_turnos_anulados:  ttan,
            desde:desde,
            hasta: hasta,
            lunes:lu,
            martes: ma,
            miercoles: mi,
            jueves: ju,
            viernes:vi,
            sabado:sa,
            domingo:dom
        }
        ,function(json){
            document.getElementById("tabla").innerHTML =json.html;
            var chart;
            chart = new Highcharts.Chart({
                chart: {
                    renderTo: 'div_cuadro',
                    defaultSeriesType: 'line',
                    marginRight: 130,
                    marginBottom: 50
                },
                title: {
                    text: 'TURNOS ATENDIDOS',
                    x: -20 //center
                },
                subtitle: {
                    text: '',
                    x: -20
                },
                xAxis: {
                    categories: ['Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab', 'Dom']
                },
                yAxis: {
                    title: {
                        text: 'Turnos'
                    },
                    plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                },
                tooltip: {
                    formatter: function() {
                        return '<b>'+ this.series.name +'</b><br/>'+
                            this.x +': '+ this.y +'°C';
                    }
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'top',
                    x: -10,
                    y: 100,
                    borderWidth: 0
                },
                series:json.data
            });
        },'json');
    }
    function verGraficoTotalSemanasTodos(arreglocompacta)
    {
        $.post("<?php echo Utils::getKumbiaUrl("reportes/verGraficoTodos")?>", {

            array:arreglocompacta

        }
        ,function(json){

            var chart;
            chart = new Highcharts.Chart({
                chart: {
                    renderTo: 'div_cuadro',
                    defaultSeriesType: 'line',
                    marginRight: 130,
                    marginBottom: 50
                },
                title: {
                    text: json.html,
                    x: -20 //center
                },
                subtitle: {
                    text: '',
                    x: -20
                },
                xAxis: {
                    categories: ['Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab', 'Dom']
                },
                yAxis: {
                    title: {
                        text: 'Turnos'
                    },
                    plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                },
                tooltip: {
                    formatter: function() {
                        return '<b>'+ this.series.name +'</b><br/>'+
                            this.x +': '+ this.y +'-TA';
                    }
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'top',
                    x: -10,
                    y: 100,
                    borderWidth: 0
                },
                series:json.data
            });
        },'json');
    }
    function verGraficoTotalFechasTodos(arreglocompacta)
    {
        $.post("<?php echo Utils::getKumbiaUrl("reportes/verGraficoFechas")?>", {

            desde: $("#desde").val(),
            hasta:  $("#hasta").val(),
            array:arreglocompacta

        }
        ,function(json){

            var chart;
            chart = new Highcharts.Chart({
                chart: {
                    renderTo: 'div_cuadro',
                    defaultSeriesType: 'line',
                    marginRight: 130,
                    marginBottom: 50
                },
                title: {
                    text: json.html,
                    x: -20 //center
                },
                subtitle: {
                    text: '',
                    x: -20
                },
                xAxis: {
                    categories: json.categoria
                },
                yAxis: {
                    title: {
                        text: 'Turnos'
                    },
                    plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                },
                tooltip: {
                    formatter: function() {
                        return '<b>'+ this.series.name +'</b><br/>'+
                            this.x +': '+ this.y +'-TA';
                    }
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'top',
                    x: -10,
                    y: 100,
                    borderWidth: 0
                },
                series:json.data
            });
        },'json');
    }

    function verGraficoTotalSemana(ttat,ttan,desde,hasta,lu,ma,mi,ju,vi,sa,dom){
        $.post("<?php echo Utils::getKumbiaUrl("reportes/verGrafico")?>", {
            id_modulo:arreglo.join(','),
            subtotal_total_turnos_atendidos: ttat,
            subtotal_total_turnos_anulados:  ttan,
            desde:desde,
            hasta: hasta,
            lunes:lu,
            martes: ma,
            miercoles: mi,
            jueves: ju,
            viernes:vi,
            sabado:sa,
            domingo:dom
        }
        ,function(json){
            document.getElementById("tabla").innerHTML =json.html;
            var chart;
            chart = new Highcharts.Chart({
                chart: {
                    renderTo: 'div_cuadro',
                    defaultSeriesType: 'line',
                    marginRight: 130,
                    marginBottom: 50
                },
                title: {
                    text: 'TURNOS ATENDIDOS',
                    x: -20 //center
                },
                subtitle: {
                    text: '',
                    x: -20
                },
                xAxis: {
                    categories: ['Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab', 'Dom']
                },
                yAxis: {
                    title: {
                        text: 'Turnos'
                    },
                    plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                },
                tooltip: {
                    formatter: function() {
                        return '<b>'+ this.series.name +'</b><br/>'+
                            this.x +': '+ this.y +'°C';
                    }
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'top',
                    x: -10,
                    y: 100,
                    borderWidth: 0
                },
                series:json.data
            });
        },'json');
    }

    function parametrosBBDD(){
        // alert("maestro");

        $.post("<?php echo Utils::getKumbiaUrl("reportes_sucursales/Graficador1")?>", {
            sucursal_id:arregloIdSucursal.join(','),
            modulos: arreglo.join(","),
            desde: $("#desde").val(),
            hasta:  $("#hasta").val(),
            chkservicios: arregloservicio.join(','),
            Grafica: "Barras"
        }
        ,function(json){
            document.getElementById("div_cabecera").innerHTML =json.titulo;
            //document.getElementById("maestro_chart").innerHTML =json.html;
            document.getElementById("div_estadisticaModulos").innerHTML =json.tabla;
        },'json');

    }

    function tablaXLS(){
        $.post("<?php echo Utils::getKumbiaUrl("reportes_sucursales/reporteTurnosAtendidosModuloXls")?>", {
            action: 'reporteTurnosAtendidosModuloXls',
            desde: $("#desde").val(),
            hasta: $("#hasta").val(),
            chkmodulos: arreglo.join(','),
            chkservicios:arregloservicio.join(','),
            horas:      $("#horas").val(),
            minutos:    $("#minutos").val(),
            segundos:   $("#segundos").val()
        }
        ,function(data){
            document.getElementById("div_xls").innerHTML = data;
        },'ajax')
    }


    function VerCuadroPreguntasCalificadas()
    {
        $.post("<?php echo Utils::getKumbiaUrl("reportes/verCuadroCalificaciones")?>", {
            action: 'verCuadro',
            //id: $("#cajas").val()
            desde: $("#desde").val(),
            hasta: $("#hasta").val(),
            chkmodulos: arreglo.join(','),
            preguntas: arreglopreguntas.join(','),
            chkservicios: arregloservicio.join(',')
        }
        ,function(data){
            document.getElementById("div_TablaPreguntasCalificadas").innerHTML = data;
        },'ajax');
    }
    var tipo="";
    $('#chk_barrasPreguntasCalificada').click(function(){
        if ($('#chk_barrasPreguntasCalificada').is(':checked'))
            tipo="Barras";
    });
    $('#chk_pastelPreguntasCalificadas').click(function(){
        if ($('#chk_pastelPreguntasCalificadas').is(':checked')) tipo="Pastel";
    });
    function GraficarTodasLasPreguntas(array_serie,array_categorias,array_etiqueta_fila,etiqueta_categoria)
    {
        $.post("<?php echo Utils::getKumbiaUrl("reportes/graficarPicos")?>",
        {
            array_serie: array_serie,
            array_categorias: array_categorias,
            array_etiqueta_fila: array_etiqueta_fila,
            etiqueta_categoria:etiqueta_categoria
        }
        ,function(json){
            var chart;
            chart = new Highcharts.Chart({
                chart: {
                    renderTo: 'Div_Todo',
                    defaultSeriesType: 'line',
                    marginRight: 130,
                    marginBottom: 50
                },
                title: {
                    text: 'PREGUNTAS CALIFICADAS',
                    x: -20 //center
                },
                subtitle: {
                    text: '',
                    x: -20
                },
                xAxis: {
                    categories: json.categoria
                },
                yAxis: {
                    title: {
                        text: 'Turnos'
                    },
                    plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                },
                tooltip: {
                    formatter: function() {
                        return '<b>'+ this.series.name +'</b><br/>'+
                            this.x +': '+ this.y +'°C';
                    }
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'top',
                    x: -10,
                    y: 100,
                    borderWidth: 0
                },
                series:json.datos
            });
        },'json')
    }

    function GraficarPregunta(id_pregunta,total)
    {
        $.post("<?php echo Utils::getKumbiaUrl("reportes/GraficaPregunta")?>", {
            chkmodulos: arreglo.join(','),
            preguntas: id_pregunta,
            chkservicios: arregloservicio.join(','),
            totales:total,
            tipo: tipo
        }
        ,function(json){
            if (tipo=="Barras"){
                document.getElementById("div_barraPreguntasCalificada").innerHTML = json.datos;}
            else if (tipo=="Pastel"){
                document.getElementById("div_pastelPreguntasCalificada").innerHTML = json.datos;}
            else{
                document.getElementById("div_pastelPreguntasCalificada").innerHTML = "";
                document.getElementById("div_barraPreguntasCalificada").innerHTML = "";
            }

        },'json')


    }

</script>

<!--****** RESTAURAR VENTANA ****** -->
<script>
    function restaurar(){
        var w = screen.width * 0.80;
        var h = screen.height * 0.80;
        window.statusbar.visible = false;
        window.scrollbars.visible = false;
        window.menubar.visible = false;
        window.toolbar.visible = false;
        window.locationbar.visible = false;
        window.personalbar.visible = false;
        window.directories.visible = false;
        window.innerWidth = w;
        window.innerHeight = h;
        window.screenX = (screen.width-w)/2;
        window.screenY = (screen.height-h)/2-40;
        //alwaysLowered = false;
        //setTimeout("restaurar()",2000);
    }
    restaurar();
</script>