<fieldset class='ui-corner-all ui-widget-content'>
    <legend><label style="color:red"><b>Ayuda</b></label></legend>
    <p><label><b>Dirección IP: </b>Sirve para que aparezaca el nombre de usuario automáticamente en la PC con el monitor extendido.</label></p>
</fieldset>
<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Pantalla</b></legend>
    <p><label class='labelform' ><span for='numero'>Número:</span></label><?php echo Tag::textField("numero", "size: 5", "maxlength: 2", "class: ") ?></p>
    <p><label class='labelform' ><span for='descripcion'>Descripción:</span></label><?php echo Tag::textField("descripcion", "size: 45", "maxlength: 45", "class: required") ?></p>
    <p><label class='labelform' ><span for='ip_equipo'>Dirección IP:</span></label><?php echo Tag::textField("ip_equipo", "size: 20", "maxlength: 15", "class: ") ?></p>
    <p><label class='labelform' ><span for='plantilla'>Plantilla:</span></label><?php echo Tag::textField("plantilla", "size: 20", "maxlength: 150","class: ") ?></p>
    <p><label class='labelform' ><span for='color_turnos'><b>Color Turnos</b>:</span></label><?php echo Tag::textField("color_turnos", "size: 10", "maxlength: 10", "class: color") ?></p>
    <p><label class='labelform' ><span for='color_noticias'><b>Color Noticias</b>:</span></label><?php echo Tag::textField("color_noticias", "size: 10", "maxlength: 10", "class: color") ?></p>
    <p><label class='labelform' ><span for='color_reloj'><b>Color Reloj</b>:</span></label><?php echo Tag::textField("color_reloj", "size: 10", "maxlength: 10", "class:  color") ?></p>
    <!--<p><label class='labelform' ><span for='efecto_turno_superior'><b>Efecto Turno Superior</b>:</span></label><?php //echo Tag::checkboxField("efecto_turno_superior");     ?></p>-->
</fieldset>

<?php
$idPantalla = $id;
$listausuarios = array();
$condicion = "{#Pantalla}.id = $id";
$query = new ActiveRecordJoin(array(
    "entities" => array("Usuario", "Pantalla", "Userpantalla"),
    "fields" => array(
        "{#Usuario}.id",
        "{#Usuario}.nombres"),
    "conditions" => $condicion
        ));
foreach ($query->getResultSet() as $result) {
    $listausuarios[$result->getId()] = $result->getNombres();
}

$condicion = "{#Grupo}.id = 6";
$query = new ActiveRecordJoin(array(
    "entities" => array("Usuario", "Grupo", "Grupousuario"),
    "fields" => array(
        "{#Usuario}.id",
        "{#Usuario}.nombres"),
    "conditions" => $condicion
        ));
foreach ($query->getResultSet() as $result) {
    $listausuarios[$result->getId()] = $result->getNombres();
}
?>
<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Usuario</b></legend>
    <p><label class='labelform' ><span for='usuarios'>Asignar a Usuario:</span></label><?php echo Tag::selectStatic("usuarios", $listausuarios, "class:  required") ?></p>
    <!--<p><label class='labelform' ><span for='usuarios'><b>Asignar a Usuario</b>:</span></label><?php //echo Tag::select("pantalla_id", $Pantalla->find("order: id"), "using: id,descripcion", "use_dummy: yes","dummyValue: ''","class: ")      ?></p>-->
</fieldset>

<?php
//INICIO ubicacion de la pantalla
$listaubicacion = array();
$condicion = "{#Pantalla}.id = $id";
$query = new ActiveRecordJoin(array(
    "entities" => array("Ubicacion", "Pantalla"),
    "fields" => array(
        "{#Ubicacion}.id",
        "{#Ubicacion}.nombre_ubicacion"
    ),
    "conditions" => $condicion
        ));
foreach ($query->getResultSet() as $result) {
    $listaubicacion[$result->getId()] = $result->getNombreUbicacion();
}

$ubicacion = new Ubicacion();
$buscaUbicacion = $ubicacion->find();

foreach ($buscaUbicacion as $result) {
    $listaubicacion[$result->getId()] = $result->getNombreUbicacion();
}
?>

<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Ubicación de la Pantalla</b></legend>
    <p><label class='labelform' ><span for='ubicacion'>Ubicación:</span></label><?php echo Tag::selectStatic("ubicacion", $listaubicacion, "class:  required") ?></p>
</fieldset>

<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Tipo de Pantalla</b></legend>
    <table border="0"  >
        <?php
        if ($modulo_atencion_con_ticket == 1) {
            echo "<tr>
                <td>" . Tag::radioField("radio_tipo_pantalla", array('A' => 'Pantalla para atención con tickets')) .
            "</td>
            </tr>";
        }
        if ($modulo_atencion_sin_ticket == 1) {
            echo "<tr>
                <td>" . Tag::radioField("radio_tipo_pantalla", array('B' => 'Pantalla para atención sin tickets')) .
            "</td>
            </tr>";
        }
        if (($modulo_atencion_con_ticket != 1) & ($modulo_atencion_sin_ticket != 1))
            echo "No tiene acceso a ningún módulo de pantalla. Consulte con el proveedor del sistema SmartQ";
        ?>
    </table>
</fieldset>
<?php
$tono = '';
$db = DbBase::rawConnect();
$result2 = $db->query("SELECT 	tono	FROM pantalla WHERE id = $idPantalla");
while ($row = $db->fetchArray($result2)) {
    $tono = $row['tono'];
}
if ($tono == "")
    $tono = 0;$tono = $tono;
?>
<fieldset class="ui-corner-all ui-widget-content">
    <legend>Configuración del tono de llamado</legend>

    <p><label class='labelform' ><span for='RadioGroup0_0'><b>Timbre</b>:</span></label><input type="radio" name="rTono" id="rTono1" onclick="mostrar_datos_tono()" <?php if ($tono == 0) echo 'checked="checked"'; ?>/></p>
    <p><label class='labelform' ><span for='RadioGroup0_1'><b>Voz</b>:</span></label><input type="radio" name="rTono"  id="rTono2" onclick="mostrar_datos_tono()" <?php if ($tono == 1) echo 'checked="checked"'; ?> /></p>
    <div id="div_datos_tono" style="display: none">
        <?php
            echo Tag::radioField("formato_voz", array('caja-#' => 'Caja #'));
            echo Tag::radioField("formato_voz", array('modulo-#' => 'Módulo #'));
            echo Tag::radioField("formato_voz", array('ventanilla-#' => 'Ventanilla #'));
            echo Tag::radioField("formato_voz", array('pase_a_la_caja-#' => 'Pase a la Caja #'));
            echo Tag::radioField("formato_voz", array('pase_al_modulo-#' => 'Pase al Módulo #'));
            echo Tag::radioField("formato_voz", array('pase_a_la_ventanilla-#' => 'Pase a la Ventanilla #'));
        ?>
    </div>
    <p><label class='labelform'><span for='tiempo_tono'><b>Tiempo</b>:</span></label><?php echo Tag::numericField("tiempo_tono", "size: 10", "maxlength: 3", "class: required") ?></p>

    <?php echo Tag::hiddenField("tono", "size: 5", "maxlength: 5", "class: required", "value: $tono") ?>
</fieldset>
<script>
    //$("#usuarios option[value=188]").attr("selected", true);
    //$('input:radio[name=rd_datos_tono][value=caja-#]').attr('checked', true);

    mostrar_datos_tono();
    function mostrar_datos_tono() {
        if ($('#rTono2').is(':checked') == true)
            $("#div_datos_tono").css('display', 'inline');
        else
            $("#div_datos_tono").css('display', 'none');
    }

    $("#rTono1").click(function() {
        document.getElementById('tono').value = 0;
    });
    $("#rTono2").click(function() {
        document.getElementById('tono').value = 1;
    });
</script>