<script>
    function addRow(id,valor){
        var tbody = document.getElementById
        (id).getElementsByTagName("TBODY")[0];
        var row = document.createElement("TR")
        var td1 = document.createElement("TD")
        td1.appendChild(document.createTextNode(valor))
        //td1.appendChild(document.height(30));
        td1.setAttribute('HEIGHT','25');

        //var td2 = document.createElement("TD")
        //td2.appendChild (document.createTextNode("columna 2"))
        row.appendChild(td1);
        //row.appendChild(td2);
        tbody.appendChild(row);
    }
</script>

<fieldset class='ui-corner-all ui-widget-content'>
    <legend><label style="color:red"><b>Ayuda</b></label></legend>
    <p><label><b>Orden: </b>Seleccione un solo archivo swf para la pantalla</label></p>
</fieldset>

<fieldset class='ui-corner-all ui-widget-content'>
    <legend><label style="color:black"><b>Seleccione el archivo swf a publicar</b></label></legend>
    <div align='center'>
        <table width="100%">
            <tr>
                <td valign="top">
                    <div style='padding:10px'>
                        <table align="center" width="100%">
                            <?php
                            $publicidad= new Publicidad();
                            $buscaPublicidad = $publicidad->find("order: archivo_publicidad asc");
                            ?>
                            <tr>
                                <td>
                                    <?php if(count($buscaPublicidad)>0) { ?>

                                    <!--Tabla que contiene la tabla de Orden y tabla de Videos-->
                                    <table border="0px"  align="center" width="100%">
                                        <tr>
                                            <td>
                                                <!--Tabla que contiene la tabla de Orden-->
                                                <table id="myTable_2" border="1px"  align="right">
                                                    <tbody>
                                                        <tr>
                                                            <th height="40px">N.</th>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                            <td>
                                                <!--Tabla que contiene la tabla de Videos-->
                                                <table id="table-2" border="1px"  align=left>
                                                    <tr>
                                                        <th height="40px">Nombre archivo SWF<span style="text-align:center">
                                                          
                                                        </span></th>
                                                        <!--<th>Asignado</th>-->
                                                    </tr>
                                                        <?php
                                                        //Lista de archivos swf asignados a una pantalla
                                                        $pantallapublicidad=new Pantallapublicidad();
                                                        $listavideos=array();
                                                        if (!empty($id)) {
                                                            $videoactivo=$pantallapublicidad->find("conditions: pantalla_id= $id");
                                                            if(count($videoactivo)>0) {
                                                                $listavideos=array();
                                                                foreach($videoactivo as $fila) {
                                                                    $listavideos[]=$fila->getPublicidadId(); //lista de videos asignados a una pantalla
                                                                }
                                                            }else {
                                                                $listavideos[] = "0";
                                                            }
                                                        }

                                                        //Lista de archivos swf
                                                        $publicidad=new Publicidad();
                                                        $videoactivo=$publicidad->find("");
                                                        if(count($videoactivo)>0) {
                                                            $todos_videos=array();
                                                            foreach($videoactivo as $fila) {
                                                                $todos_videos[]=$fila->getId(); //lista de videos activos
                                                            }
                                                        }else {
                                                            $todos_videos[] = "0";
                                                        }

                                                        $contador=0;
                                                        if (!empty($id)) {
                                                            $condicion = "{#Pantallapublicidad}.pantalla_id = $id";
                                                            $query = new ActiveRecordJoin(array(
                                                                            "entities" => array("Publicidad", "Pantallapublicidad"),
                                                                            "fields" => array(
                                                                                    "{#Publicidad}.id",
                                                                                    "{#Publicidad}.archivo_publicidad"),
                                                                            "conditions" => $condicion
                                                            ));
                                                            foreach($query->getResultSet() as $result) {
                                                                $archivo_publicidad=$result->getArchivoPublicidad();
                                                                $id_publicidad=$result->getId();
                                                                $contador+=1;
                                                                print "<script>addRow('myTable_2','$contador');</script>";
                                                                //print "<tr><td>".$result->getArchivoPublicidad()."</td>";
                                                                //print "<td align='center' height='25px'>".Tag::checkboxField("chkpublicidad[]", "value: $id_publicidad", "checked: checked")."</td></tr>";
																print "<td align='left' height='25px'>".Tag::checkboxField("chkpublicidad[]", "value: $id_publicidad", "checked: checked")."".$result->getArchivoPublicidad()."</td></tr>";
                                                                //print "<td align='center' height='25px'><input type='radio' name='radio_publicidad' value='$id_publicidad' checked>".$result->getArchivoPublicidad()."</td></tr>";
                                                            }
                                                        }
                                                        foreach($buscaPublicidad as $attribute) {
                                                            $id_publicidad=$attribute->getId();
                                                            if(in_array($id_publicidad,$listavideos)) {
                                                            }else {
                                                                $contador+=1;
                                                                print "<script>addRow('myTable_2','$contador');</script>";
                                                                //print "<tr><td>".$attribute->getArchivoPublicidad()."</td>";
                                                                //print "<td align='center' height='25px'>".Tag::checkboxField("chkpublicidad[]", "value: $id_publicidad")."</td>";
																print "<td align='left' height='25px'>".Tag::checkboxField("chkpublicidad[]", "value: $id_publicidad")."".$attribute->getArchivoPublicidad()."</td>";
                                                                //print "<td align='center' height='25px'><input type='radio' name='radio_publicidad' value='$id_publicidad'>".$attribute->getArchivoPublicidad()."</td>";
                                                            }
                                                            print "</tr>";
                                                        }
                                                        ?>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                        <?php }  ?>

                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</fieldset>

<script type="text/javascript">
    $(document).ready(function() {
        // Initialise the table
        $("#table-2").tableDnD();
    });

    function seleccionar(val){
        if (v==0)
            $("#div_permisos_sistema").show(1000);
        else
            $("#div_permisos_sistema").hide("slow");
        var chks1=$("input:checkbox[name^='chk_grupo']");
        var nombre="";
        for (var x=0; x < chks1.length; x++) {
            nombre= chks1[x].id;
            var clase = chks1[x].className;
            var nom_clase="c_unico_"+val;
            if (clase==nom_clase){
                //$("#"+nombre).attr("checked", "checked");
            } else {
                $("#"+nombre).attr("checked", "");
            }
        }

        var chks1=$("input:checkbox[name^='chk_grupo']");
        var nombre="";
        for (var x=0; x < chks1.length; x++) {
            value= chks1[x].value;
            nombre= chks1[x].id;
            var clase = chks1[x].className;
            //alert (clase);
            //var nom_clase="c_modulos_"+val;
            if (clase=="c_unico_1"){
                if (v!=value){
                    $("#"+nombre).attr("checked", "");
                }

            }
        }
    }
</script>

