<?php Tag::stylesheetLink("appgen/appgen") ?>
<div id='header' class="ui-layout-north ui-widget-header ui-corner-all">
	<table>
		<tr>
                    <td><h1>Aplicaci&oacute;n de generaci&oacute;n de formularios</h1></td>
		</tr>
	</table>
	<div>Usuario: <b>test</b>
	<?php
		if($extappname!=""){
			print "Aplicaci&oacute;n: <b>$extappname</b>";
		}
	?>
	</div>


<div style=" padding: 5px;" class="ui-corner-all ui-state-default">
	<?php echo Tag::linkTo("create/index", "Inicio") ?>
</div>
</div>
<div align='center'>
	<div id="mainContent" align="left" class="ui-corner-all ui-widget ui-widget-content">
		<?php View::getContent(); ?>
	</div>
</div>

<div id='footer' class="ui-widget-header ui-corner-all">
<div align="right">
Application Forms 0.1
</div>
<table width="100%">
	<tr>
		<td align="left">Idioma: Espa&ntilde;ol</td>
		<td align="right">Copyright 2005-2009, Todos los derechos reservados</td>
	</tr>
</table>
</div>