<fieldset class='ui-corner-all ui-widget-content'>
    <legend>Datos de Empresa</legend>
    <p><label class='labelform' ><span for='nombrecomercial'><b>Nombre Comercial</b>:</span></label><?php echo Tag::textField("nombrecomercial", "size: 45", "maxlength: 45","class: ") ?></p>
    <p><label class='labelform' ><span for='razonsocial'><b>Razon Social</b>:</span></label><?php echo Tag::textField("razonsocial", "size: 45", "maxlength: 180","class: ") ?></p>
    <p><label class='labelform' ><span for='matriz'><b>Matriz</b>:</span></label><?php echo Tag::checkboxField("matriz");?></p>
    <p><label class='labelform' ><span for='carpeta'><b>Carpeta</b>:</span></label><?php echo Tag::textField("carpeta", "size: 30", "maxlength: 30","class: required") ?></p>
</fieldset>
