<div id='mainContent'>

    <?php
    //echo View::getContent();
    View::renderPartial("toolbarform");
    echo Tag::form("categoriafeeds/guardar");
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Categoriafeeds</legend>
        <p><label class='labelform' ><span for='nombre_categoria'><b>Nombre Categoría</b>:</span></label><?php echo Tag::textField("nombre_categoria", "size: 50", "maxlength: 50","class:  required") ?></p>
    </fieldset>
    <!--<div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Crear"); echo Tag::button("Cancelar","onclick: window.location='index';"); ?>
	</div>-->
    <?php echo Tag::endForm(); ?>

</div>
