<table  align="center" border ="0" width="100%">
    <tr><td><div id="div_titulo" style="width: 100%"></div></td><tr>
    <tr>
        <th>
            <div  id="division_cuadro" >
            </div>
        </th>
    <tr>
    <tr>
        <td>
            <div id="div_detalle">
                <div  id="div_cuadro"></div>
                <div id="tabla"></div>
            </div>
        </td>
    <tr>

</table>

<script>
    window.onresize=Resize;
    Resize();

    function Resize(){
        ancho= $(window).width()-70;
        alto=$(window).height()/2-75;
        document.getElementById("division_cuadro").setAttribute("style", "background-color:#transparent; width:"+ancho+"px; height:"+alto+"px; border:1px solid black; overflow-y:auto; overflow-x:auto; ");
        document.getElementById("div_detalle").setAttribute("style", "background-color:#transparent; width:"+ancho+"px; height:"+alto+"px; border:1px solid black; overflow-y:auto; overflow-x:auto; ");
        //document.getElementById("tabla").setAttribute("style", "background-color:#transparent; width:"+ancho+"px; height:"+alto+"px; border:1px solid black; overflow-y:auto; overflow-x:auto; ");
    }

    function restaurar(){
        var w = screen.width * 0.76;
        var h = screen.height * 0.70;
        window.statusbar.visible = false;
        window.scrollbars.visible = false;
        window.menubar.visible = false;
        window.toolbar.visible = false;
        window.locationbar.visible = false;
        window.personalbar.visible = false;
        window.directories.visible = false;
        window.innerWidth = 355;
        window.innerHeight = 470;
        window.screenX = w;
        window.screenY = h;
        //alwaysLowered = false;
        setTimeout("restaurar()",2000);
    }
    //restaurar();

    //$("#alto_frame_5").attr({'readonly':'','style': 'background-color: #fff'}); //activar alto_frame_5
    //document.getElementById("div_previo_frame_imagen_"+num_frame).setAttribute("style", "background-color:#transparent; left:"+x_f1+"px; top:"+y_f1+"px; width:"+ancho_f1+"px; height:"+alto_f1+"px; border:1px solid black; overflow-y:auto; overflow-x:auto; position:absolute;");

</script>