<div id='mainContent'>

    <?php    //View::renderPartial('toolbarform');
    echo Tag::form('reportes/verCuadro');
    ?>

    <fieldset class='ui-corner-all ui-widget-content'>
        <legend><b>Fecha</b></legend>
        <table id="tbl_menu" border="0" width="100%" class="empty">
            <tr>
                <td class="empty">
                    <p><label class='labelform' ><span for='desde'>Desde:</span></label><?php echo Tag::textField("desde", "size: 12", "maxlength: 12","class:  dateISO") ?></p>
                </td><td class="empty">
                    <p><label class='labelform' ><span for='hasta'>Hasta:</span></label><?php echo Tag::textField("hasta", "size: 12", "maxlength: 12","class:  dateISO") ?></p>
                </td>
            </tr>
        </table>
    </fieldset>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend><b>Duración</b></legend>
        <p><label class='labelform' ><span for='horas'>Tomar turnos con duración a partir de:</span></label><?php echo Tag::textField("horas", "size: 2", "maxlength: 2","class: ","value: 00").":";
            echo Tag::textField("minutos", "size: 2", "maxlength: 2","class: ","value: 00").":";
            echo Tag::textField("segundos", "size: 2", "maxlength: 2","class: ","value: 00");?></p>
    </fieldset>

    <fieldset class="ui-corner-all ui-widget-content">
        <legend><b>Módulos</b></legend>
        <input id="chk_all_modulos" type="checkbox"/><label style="color:#3366FF; font-size:12px; font-weight:bold">Marcar/desmarcar todos</label><br/>
        <?php
        $col=0;
        $array_valores=array();
        foreach($lista_modulos_tad as $key=> $val) {
            $array_valores[]=Tag::checkboxField("chkmodulos[]", "value: $key","checked: ")."Módulo ".$val."&nbsp;&nbsp;";
        }
        echo "<table>";
        $cont_mod=count($lista_modulos_tad);
        $cont_filas=ceil($cont_mod/5);
        $x=$cont_filas*5;
        $y=$x-$cont_mod;
        for ($z=1;$z<=$y;$z++)
            $array_valores[]="";
        $cont_key=0;
        for ($f=1; $f<=$cont_filas; $f++) { //filas
            echo "<tr>";
            for ($c=1;$c<=5;$c++) { //columnas
                echo "<td>".$array_valores[$cont_key]."</td>";
                $cont_key+=1;
            }
            echo "</tr>";
        }
        echo "</table>";
        ?>

    </fieldset>

    <fieldset class="ui-corner-all ui-widget-content">
        <legend><b>Servicios</b></legend>
        <input id="chk_all_servicios" type="checkbox"/><label style="color:#3366FF; font-size:12px; font-weight:bold">Marcar/desmarcar todos</label><br/>
        <?php
        $col=0;
        $array_valores=array();
        foreach($lista_servicios_tad as $key=> $val) {
            $array_valores[]=Tag::checkboxField("chkservicios[]", "value: $key","checked: ").$val."&nbsp;&nbsp;";
        }
        echo "<table>";
        $cont_mod=count($lista_servicios_tad);
        $cont_filas=ceil($cont_mod/4);
        $cont_key=0;

        if ($cont_mod<=4) {
            echo "<tr>";
            for ($c=1;$c<=$cont_mod;$c++) {
                echo "<td>".$array_valores[$cont_key]."</td>";
                $cont_key+=1;
            }
            echo "</tr>";
        } else {
            $x=$cont_filas*4;   //numero de celdas
            $y=$x-$cont_mod;    //numero de celdas vacias
            for ($z=1;$z<=$y;$z++)
                $array_valores[]="";
            for ($f=1; $f<=$cont_filas; $f++) {
                echo "<tr>";
                for ($c=1;$c<=4;$c++) {
                    echo "<td>".$array_valores[$cont_key]."</td>";
                    $cont_key+=1;
                }
                echo "</tr>";
            }
        }
        echo "</table>";

        ?>
    </fieldset>
    <!--<input type="button" id="btn_vercuadro" name="btn_vercuadro" value="Procesar">-->

    <div id="div_cuadro" align="center"> <!--No uso este div-->
    </div>
    <?php echo Tag::submitButton("Ver Cuadro");?>
    <?php echo Tag::endForm(); ?>

</div>


<script>
    $(function() {
        $("#desde").datepicker({ dateFormat: 'yy-mm-dd' });
    });
    $(function() {
        $("#hasta").datepicker({ dateFormat: 'yy-mm-dd' });
    });

    $("#chk_all_modulos").click(function(){
        var chks=$("input:checkbox[name^='chkmod']");
        chks.attr("checked",$(this).is(":checked"))
    })

    $("#chk_all_servicios").click(function(){
        var chks=$("input:checkbox[name^='chkser']");
        chks.attr("checked",$(this).is(":checked"))
    })

    $("#btn_vercuadro").click(function(){ //muestra el cuadro con los resultador
        $.post("<?php echo Utils::getKumbiaUrl("reportes/verCuadro")?>", {
            action: 'verCuadro',
            //id: $("#cajas").val()
            desde: $("#desde").val(),
            hasta: $("#hasta").val(),
            modulo: $("#cajas").val(),
            servicio: $("#servicios").val()
        }
        ,function(data){
            document.getElementById("div_cuadro").innerHTML = data;
        },'ajax');
    });

    function ventanaSecundaria (URL){
        //var Xpos=(screen.width/2)-400;
        //var Ypos=(screen.height/2)-400;
        var Xpos=0;
        var Ypos=0;
        window.open(URL,'ventana1','width=600,height=480,scrollbars=yes,resizable=yes,left='+Xpos+',top='+Ypos)
    }

    $('#desde').click(function(){
        document.getElementById("div_cuadro").innerHTML="";
    });
    $('#hasta').click(function(){
        document.getElementById("div_cuadro").innerHTML="";
    });
    $('#cajas').click(function(){
        document.getElementById("div_cuadro").innerHTML="";
    });
    $('#servicios').click(function(){
        document.getElementById("div_cuadro").innerHTML="";
    });

    /*function cargarPagina(url,tipo){
        if(tipo=='popup'){
            var Xpos=(screen.width/2)-285;
            var Ypos=(screen.height/2)-220;
            $("#content-center").html('');
            window.open(url,'popup','width=600,height=480,scrollbars=yes,left='+Xpos+',top='+Ypos);
        }else{
            $("#content-center").load(url,function(){
            });
        }
    }*/
</script>