<div id="div_prueba" class="encabezado" style="text-align: center">MODULO</div>
<div id="div_numero_grande" style="text-align: center">
    <img src="<?php echo Core::getInstancePath(); ?>/public/img/<?php echo $carpeta; ?>/sistema/numeros/<?php echo $numero_modulo; ?>.png" width="320" height="395" onclick="" />
</div>
<div id="div_foto" style="text-align: center">
    <img src="<?php echo Core::getInstancePath(); ?>/public/img/<?php echo $carpeta; ?>/fotos/<?php echo $foto; ?>" width="310" height="360" />
</div>
<div id="div_nombre" class="nombre" style="text-align: center"><?php echo $nombre_operador; ?></div>