<div id="div_prueba" class="encabezado" style="text-align: center">MODULO <?php echo $numero_modulo; ?></div>
<div id="div_publicidad" style="text-align: center">
    <!--    <object width='523' height='362' attr1='attrValue1' attr2='attrValue2' codebase='http://www.apple.com/qtactivex/qtplugin.cab' classid='clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B'>
            <param name='src'      value='<?php echo Core::getInstancePath(); ?>/public/img/<?php echo $carpeta; ?>/publicidad/publicidad.swf'>
            <param name='autoplay' value='true'>
            <param name='param1'   value='paramValue1'>
            <param name='param2'   value='paramValue2'>
            <embed wmode='transparent' width='523' height='362' src='<?php echo Core::getInstancePath(); ?>/public/img/<?php echo $carpeta; ?>/publicidad/publicidad.swf' autoplay='true'
                   attr1='attrValue1' attr2='attrValue2' param1='paramValue1' param2='paramValue2'
                   pluginspage='http://www.apple.com/quicktime/download/' > </embed>
        </object>-->
    <?php echo Tag::image($carpeta . "/publicidad/publicidad.png", 'width: 684px', 'height: 448px') ?>
</div>
