<div id='mainContent'>

	<?php echo View::getContent();
		 echo Tag::form('display/guardar/true');
	?>
	<fieldset class='ui-corner-all ui-widget-content'>
		<legend>Datos de Display</legend>
		<p><label class='labelform' ><span for='formato'><b>Formato</b>:</span></label><?php echo Tag::textField("formato", "size: 4", "maxlength: 4","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='turnos'><b>Turnos</b>:</span></label><?php echo Tag::textField("turnos", "size: 45", "maxlength: 45","class: ") ?></p>
		<p><label class='labelform' ><span for='chkbanner'><b>Chkbanner</b>:</span></label><?php echo Tag::textField("chkbanner", "size: 4", "maxlength: 4","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='numvideos'><b>Numvideos</b>:</span></label><?php echo Tag::textField("numvideos", "size: 11", "maxlength: 11","class:  numeric") ?></p>
		<p><label class='labelform' ><span for='horainicio'><b>Horainicio</b>:</span></label><?php echo Tag::textField("horainicio", "size: 10", "maxlength: 0","class: ") ?></p>
		<p><label class='labelform' ><span for='horafin'><b>Horafin</b>:</span></label><?php echo Tag::textField("horafin", "size: 10", "maxlength: 0","class: ") ?></p>
	</fieldset>
	<div class='ui-corner-all ui-widget-content'>
		<?php echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
	</div>
	<?php echo Tag::endForm(); ?>

</div>
