<script type="text/javascript" src="../../../js/jscolor.js"></script>

<div id='mainContent'>

    <?php
    View::renderPartial("toolbarform");
    echo Tag::form("servicio/guardar/true");
    ?>
    <fieldset class='ui-corner-all ui-widget-content'>
        <legend>Datos de Servicio</legend>
        <p><label class='labelform' style="width:200px"><span for='nombre'><b>Nombre</b>:</span></label><?php echo Tag::textField("nombre", "size: 40", "maxlength: 50","class: required") ?></p>
        <p><label class='labelform' style="width:200px"><span for='descripcion'><b>Descripción</b>:</span></label><?php echo Tag::textfield("descripcion","size: 40","maxlength: 150", "class: ") ?></p>
        <p><label class='labelform' style="width:200px"><span for='descripcion'><b>Letra</b>:</span></label><?php echo Tag::textfield("letra","size: 1","maxlength: 1","class: required") ?></p>
        <p><label class='labelform' style="width:200px"><span for='estado'><b>Estado (Activo/Inactivo)</b>:</span></label><?php echo Tag::checkboxField("estado");?></p>


        <?php
        //INICIO grupo del servicio
        $gruposervicio=array();
        $condicion = "{#Servicio}.id = $id";
        $query = new ActiveRecordJoin(array(
                        "entities" => array("Gruposervicio", "Servicio"),
                        "fields" => array(
                                "{#Gruposervicio}.id",
                                "{#Gruposervicio}.nombre_grupo_servicio"),
                        "conditions" => $condicion
        ));
        foreach($query->getResultSet() as $result) {
            $listagruposervicio[$result->getId()]=$result->getNombreGrupoServicio();
        }

        $gruposervicio = new Gruposervicio();
        $buscaGruposervicio = $gruposervicio->find();
        foreach($buscaGruposervicio as $result) {
            $listagruposervicio[$result->getId()]=$result->getNombreGrupoServicio();
        }
        ?>

        <p><label class='labelform' style="width:200px"><span for='ubicacion'><b>Grupo del Servicio</b>:</span></label><?php echo Tag::selectStatic("gruposervicio", $listagruposervicio,"class:  required") ?></p>

        <?php
        //INICIO ubicacion del servicio
        $listaubicacion=array();
        $condicion = "{#Servicio}.id = $id";
        $query = new ActiveRecordJoin(array(
                        "entities" => array("Ubicacion", "Servicio"),
                        "fields" => array(
                                "{#Ubicacion}.id",
                                "{#Ubicacion}.nombre_ubicacion"),
                        "conditions" => $condicion
        ));
        foreach($query->getResultSet() as $result) {
            $listaubicacion[$result->getId()]=$result->getNombreUbicacion();
        }

        $ubicacion = new Ubicacion();
        $buscaUbicacion = $ubicacion->find();

        foreach($buscaUbicacion as $result) {
            $listaubicacion[$result->getId()]=$result->getNombreUbicacion();
        }
        ?>

        <p><label class='labelform' style="width:200px"><span for='ubicacion'><b>Ubicación</b>:</span></label><?php echo Tag::selectStatic("ubicacion", $listaubicacion,"class:  required") ?></p>
        <p><label class='labelform' style="width:200px"><span for='tiempo_maximo'><b>Tiempo Máximo de atención</b>:</span></label><?php echo Tag::textField("tiempo_maximo", "size: 5", "maxlength: 10","class: ") ?>&nbsp;&nbsp;
            <b>Sugerido en base a datos registrados:</b><?php echo Tag::textField("tiempo_maximo_sugerido", "size: 5", "maxlength: 10","class: ","readonly: readonly") ?></p>
        <p><label class='labelform' style="width:200px"><span for='nombre'><b>Color de letra en dispensador</b>:</span></label><?php echo Tag::textField("color", "size: 10", "maxlength: 10","class: color") ?></p>
        
        <p><label class='labelform' style="width:200px"><span for='atencion_preferencial'><b>Habilitar Atención Preferencial</b>:</span></label><?php echo Tag::checkboxField("atencion_preferencial");?></p>
        <p><label class='labelform' style="width:200px"><span for='letra_alias'><b>Letra si es Turno Preferencial</b>:</span></label><?php echo Tag::textField("letra_alias", "size: 1", "maxlength: 1","class: ") ?></p>
		<script>
		if(document.getElementById('letra_alias').value == ' ')
		document.getElementById('letra_alias').value = '';
		</script>
    </fieldset>
    <!--<div class='ui-corner-all ui-widget-content'>
    <?php //echo Tag::submitButton("Grabar"); echo Tag::button("Cancelar","onclick: window.location='../index';"); ?>
        <input id="Inicializar" type="button" value="Inicializar"/>
    </div>-->
    <?php echo Tag::endForm(); ?>
</div>

<script>
    $("#tiempo_maximo").timepicker({ timeFormat: 'hh:mm:ss' });
</script>