<div id='mainContent'>
    <?php
    //View::renderPartial('toolbarformrefresh');
    ?>
    <table class='tablesorter' id='Exportar_a_Excel' border="1">
        <thead>
            <tr>
                <th>Usuario</th>
                <th>Estado Login</th>
                <th>Módulo</th>
                <th>Ubicación</th>
                <th>Pausado</th>
                <th>Tipo Pausa</th>
                <th>Hora Inicio</th>
                <th>Hora Fin</th>
                <th>Tiempo Transcurrido<br>en pausa</th>
            </tr>
        </thead>
        <tbody>
            <?php
            
            echo $tabla;
            ?>
        </tbody>
    </table>
</div>
