<div>
    <table width="100%">

        <tr id="fila">
            <td rowspan="2" align="center"><img src="../img/logo_pie.png"/>
            <td style="font-size:16px; text-decoration:inherit; color:red;">Sistema SmartQ</td>
            <td align="right">

                <div id="mensaje" style="">
<!--                    <input id="mensaje" name="mensaje" type="text"  size= "30"  
                           style="color: #000; background-color:transparent; font-size: 14px; text-align: center; border: 0; font-weight:bold; font-family: verdana" readonly="readonly" >
                    -->
                </div>
            </td>
        </tr>
        <tr>
    <!--        <td></td>-->
            <td><a href="http://peopleweb.com.ec" target="blank" style="text-decoration:none">Pagina Oficial de PeopleWeb</a></td>
            <td align="right">Copyright 2010, Todos los derechos reservados</td>
        </tr>
    </table>
</div>

<script>
    function actualizar_turno(turno_id){
        if($("#chk_turno_"+turno_id).is(':checked')){
            $.post("<?php echo Utils::getKumbiaUrl("admturnos/actualizarTurno") ?>",{
                turno_id: turno_id
            }, function(data){
            
            },'ajax');
        }
    }

    function actualizar_turno_trans(turno_id){
        if($("#chk_turno_trans_"+turno_id).is(':checked')){
            $.post("<?php echo Utils::getKumbiaUrl("admturnos/actualizarTurnoTransferido") ?>",{
                turno_id: turno_id
            }, function(data){

            },'ajax');
        }
    }
</script>

<script>
    setInterval('contarTurnosMalaCalificacion()',"10000"); //actualizar cada 10 segundos
    function contarTurnosMalaCalificacion(){
        $.post("<?php echo Utils::getKumbiaUrl("admturnos/contarTurnosMalaCalificacion") ?>",{
        }, function(data){
            //alert(data);
            if (data==0){
                //$("#mensaje").val("-");
                $("#mensaje").html("-");
                detiene();
            } else {
                $("#mensaje").html("<a href='javascript:verTurno()' id='a_mensaje'>"+data+"</a>");
                //$("#mensaje").val("<a href='#'>"+data+"</a>");
                comienza();
            }
        },'ajax');
    }
    
    function verTurno(){
        $.post("<?php echo Utils::getKumbiaUrl("admturnos/verTurno") ?>",{
            calificacion: "Regular"
        }, function(data){
            $("#content-center").html(data);
        },'ajax');
    } 
</script>

<!-- ***** CRONOMETRO ***** -->
<script>
    
    //detiene();  //detiene el tiempo de atencion
    //$("#tiempo").attr({'style': 'color: #000; background-color:#EAEAEA; font-size: 20px; text-align: center'});
    
    var timerito_1;
    var tiempo_total = 0;

    function muestra_segundos(){
        var horas = 0;
        var minutos = 0;
        var segundos = 0;
        var segundos_aux = 0;
        var tiempo_temp = 0.0;
        tiempo_total++;
        tiempo_temp = tiempo_total/3600;
        horas = Math.floor(tiempo_temp);
        tiempo_temp = tiempo_temp - horas;
        tiempo_temp = tiempo_temp*60;
        minutos = Math.floor(tiempo_temp);
        tiempo_temp = (tiempo_temp - minutos)*60;
        segundos = Math.floor(tiempo_temp);
        segundos_aux = Math.floor(tiempo_temp);

        if(String(horas).length == 1)
            horas = "0" + horas;
        if(String(minutos).length == 1)
            minutos = "0" + minutos;
        if(String(segundos).length == 1)
            segundos = "0" + segundos;
        resultado = horas+':'+minutos+':'+segundos;


        //if (resultado>=$("#tiempo_maximo").val()){
        if( segundos_aux % 2){
            $("#a_mensaje").attr({'style': 'color: #000; background-color:transparent; font-size: 14px; text-align: center; border: 0; font-weight:bold; font-family: verdana'});
            //$("#tiempo").addClass('alerta_tiempo_maximo');
        }
        else{
            $("#a_mensaje").attr({'style': 'color: #FF0000; background-color:transparent; font-size: 14px; text-align: center; border: 0; font-weight:bold; font-family: verdana'});
            //$("#tiempo").removeClass('alerta_tiempo_maximo');
        }
        //}

        //$("#mensaje").val(resultado);
    }
    function comienza(){
        muestra_segundos();
        timerito_1 = setInterval('muestra_segundos();',1000);
    }
    function pausa(){
        clearInterval(timerito_1);
    }

    function detiene(){
        tiempo_total = 0;
        clearInterval(timerito_1);
        //document.getElementById('aaa').innerHTML = "-:--:--";
        $("#tiempo").val("-");
    }

</script>