<!--<script type='text/javascript' src='../../js/tablecloth.js'></script>-->
<div id='mainContent'>

    <?php    //View::renderPartial('toolbarform');
    //echo Tag::form('reportes/reporteTurnosAtendidosDias');
    ?>

    <fieldset class='ui-corner-all ui-widget-content'>
        <legend><b>Fecha</b></legend>
        <table id="tbl_menu" border="0" width="100%" class="empty">
            <tr>
                <td class="empty">
                    <p><label class='labelform' ><span for='desde'>Desde:</span></label><?php echo Tag::textField("desde", "size: 12", "maxlength: 12","class:  dateISO") ?></p>
                </td><td class="empty">
                    <p><label class='labelform' ><span for='hasta'>Hasta:</span></label><?php echo Tag::textField("hasta", "size: 12", "maxlength: 12","class:  dateISO") ?></p>
                </td>
            </tr>
        </table>
    </fieldset>

    <fieldset class="ui-corner-all ui-widget-content">
        <legend><b>Módulos</b></legend>
        <p><label class='labelform' ><span for='usuarios'>Seleccione la Caja:</span></label><?php echo Tag::selectStatic("cajas", $lista_cajas,"class:  required") ?></p>
    </fieldset>

    <input type="button" id="btn_vercuadro" name="btn_vercuadro" value="Procesar">
    <!--<input type="button" id="btn_graficar" name="btn_graficar" value="graficar">-->

    <!--<a href="<?php //echo $ruta1 ?>" style='text-decoration:none'>&nbsp;Nombre</a>-->

    <!--<a href="javascript:ventanaSecundaria('<?php //echo $ruta1 ?>?id=<?php //echo $id ?>')">Graficar</a>-->
    <?php //echo Tag::linkTo('reportes/verGrafico/?id='.$id,'hola'); ?>

    <div id="div_cuadro" align="center">
    </div>
    <?php //echo Tag::submitButton("Procesar");?>
    <?php echo Tag::endForm(); ?>

</div>


<script>
    $(function() {
        $("#desde").datepicker({ dateFormat: 'yy-mm-dd' });
    });
    $(function() {
        $("#hasta").datepicker({ dateFormat: 'yy-mm-dd' });
    });

    $("#btn_vercuadro").click(function(){ //muestra el cuadro con los resultador
        $.post("<?php echo Utils::getKumbiaUrl("reportes/verCuadroCajas")?>", {
            action: 'verCuadro',
            //id: $("#cajas").val()
            desde: $("#desde").val(),
            hasta: $("#hasta").val(),
            modulo: $("#cajas").val(),
            servicio: $("#servicios").val()
        }
        ,function(data){
            document.getElementById("div_cuadro").innerHTML = data;
        },'ajax');
    });

    function ventanaSecundaria (URL){
        //var Xpos=(screen.width/2)-400;
        //var Ypos=(screen.height/2)-400;
        var Xpos=0;
        var Ypos=0;
        window.open(URL,'ventana1','width=600,height=480,scrollbars=yes,resizable=yes,left='+Xpos+',top='+Ypos)
    }

    $('#desde').click(function(){
        document.getElementById("div_cuadro").innerHTML="";
    });
    $('#hasta').click(function(){
        document.getElementById("div_cuadro").innerHTML="";
    });
    $('#cajas').click(function(){
        document.getElementById("div_cuadro").innerHTML="";
    });
    $('#servicios').click(function(){
        document.getElementById("div_cuadro").innerHTML="";
    });

    /*function cargarPagina(url,tipo){
        if(tipo=='popup'){
            var Xpos=(screen.width/2)-285;
            var Ypos=(screen.height/2)-220;
            $("#content-center").html('');
            window.open(url,'popup','width=600,height=480,scrollbars=yes,left='+Xpos+',top='+Ypos);
        }else{
            $("#content-center").load(url,function(){
            });
        }
    }*/
</script>