<fieldset class='ui-corner-all ui-widget-content'>
    <legend><label style="color:red"><b>Ayuda</b></label></legend>
    <p><label><b>Dirección IP: </b>Sirve para que aparezca el nombre de usuario automáticamente en la PC con el monitor extendido.</label></p>
</fieldset>
<?php
$idPantalla = $id;
$listausuarios = array();
$condicion = "{#Pantalla}.id = $id";
$query = new ActiveRecordJoin(array(
    "entities" => array("Usuario", "Pantalla"),
    "fields" => array(
        "{#Usuario}.id",
        "{#Usuario}.nombres",
        "{#Pantalla}.tipo_pantalla"),
    "conditions" => $condicion
        ));
foreach ($query->getResultSet() as $result) {
    $listausuarios[$result->getId()] = $result->getNombres();
    $tp=$result->getTipoPantalla();
}
?>
<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Tipo de Pantalla</b></legend>
    <table border="0"  >
        <?php
        if ($modulo_atencion_con_ticket == 1) {
            echo "<tr>
                <td>" . Tag::radioField("radio_tipo_pantalla", array('A' => 'Pantalla para atención con tickets')) .
            "</td><td></td>
            </tr>";
        }
        if ($modulo_atencion_sin_ticket == 1) {
            echo "<tr>
                <td>" . Tag::radioField("radio_tipo_pantalla", array('B' => 'Pantalla para atención sin tickets')) . "</td>
                <td>
                <p><label class='labelform' ><span for='activar_difusion'><b>Llamado con tecla</b>:</span></label>". Tag::checkboxField("llamado_con_tecla") ."</p>
                </td>
            </tr>";
        }
         if ($moduloPublicidad == 1) {
            echo "<tr>
                <td>" . Tag::radioField("radio_tipo_pantalla", array('C' => 'Pantalla Publicidad')) .
            "</td><td></td>
            </tr>";
        }
        if (($modulo_atencion_con_ticket != 1) & ($modulo_atencion_sin_ticket != 1))
            echo "No tiene acceso a ningún módulo de pantalla. Consulte con el proveedor del sistema SmartQ";
        ?>
    </table>
</fieldset>


<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Pantalla</b></legend>
    <p><label class='labelform' ><span for='numero'>Número:</span></label><?php echo Tag::textField("numero", "size: 5", "maxlength: 2", "class: ") ?></p>
    <p><label class='labelform' ><span for='descripcion'>Descripción:</span></label><?php echo Tag::textField("descripcion", "size: 45", "maxlength: 45", "class: required") ?></p>
    <p><label class='labelform' ><span for='ip_equipo'>Dirección IP:</span></label><?php echo Tag::textField("ip_equipo", "size: 20", "maxlength: 15", "class: ") ?></p>
    <!--<p><label class='labelform' ><span for='plantilla'>Plantilla:</span></label><?php echo Tag::textField("plantilla", "size: 20", "maxlength: 150", "class: ") ?></p>-->

<?php if ($tp!='Pantalla Publicidad') {
    ?>

        <div id="colores" >
    <p><label class='labelform' ><span for='color_turnos'><b>Color Turnos</b>:</span></label><?php echo Tag::textField("color_turnos", "size: 10", "maxlength: 10", "class: color") ?></p>
    <p><label class='labelform' ><span for='color_noticias'><b>Color Noticias</b>:</span></label><?php echo Tag::textField("color_noticias", "size: 10", "maxlength: 10", "class: color") ?></p>
    <p><label class='labelform' ><span for='color_reloj'><b>Color Reloj</b>:</span></label><?php echo Tag::textField("color_reloj", "size: 10", "maxlength: 10", "class:  color") ?></p>
    </div>
</fieldset>
<?php

}
?>
<?php


$condicion = "{#Grupo}.id = 6";
$query = new ActiveRecordJoin(array(
    "entities" => array("Usuario", "Grupo", "Grupousuario"),
    "fields" => array(
        "{#Usuario}.id",
        "{#Usuario}.nombres"),
    "conditions" => $condicion
        ));
foreach ($query->getResultSet() as $result) {
    $listausuarios[$result->getId()] = $result->getNombres();
}

$condicion1 = "{#Grupo}.id = 8";
$query1 = new ActiveRecordJoin(array(
    "entities" => array("Usuario", "Grupo", "Grupousuario"),
    "fields" => array(
        "{#Usuario}.id",
        "{#Usuario}.nombres"),
    "conditions" => $condicion1
        ));
$listausuarios1 = array();
foreach ($query1->getResultSet() as $result1) {
    $listausuarios1[$result1->getId()] = $result1->getNombres();
}
?>

<?php if ($tp=='Pantalla Publicidad') {
    ?>
    <div id="usuarioP" >
<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Usuario</b></legend>
    <p><label class='labelform' ><span for='usuarios'>Asignar a Usuario:</span></label><?php echo Tag::selectStatic("usuariosP", $listausuarios1, "class:  required") ?></p>
</fieldset>
</div>
<?php
    # code...
} else { ?>
   <div id="usuario" >
<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Usuario</b></legend>
    <p><label class='labelform' ><span for='usuarios'>Asignar a Usuario:</span></label><?php echo Tag::selectStatic("usuarios", $listausuarios, "class:  required") ?></p>
</fieldset>
</div>
<?php
}
 ?>




<?php
//INICIO ubicacion de la pantalla
$listaubicacion = array();
$condicion = "{#Pantalla}.id = $id";
$query = new ActiveRecordJoin(array(
    "entities" => array("Ubicacion", "Pantalla"),
    "fields" => array(
        "{#Ubicacion}.id",
        "{#Ubicacion}.nombre_ubicacion"
    ),
    "conditions" => $condicion
        ));
foreach ($query->getResultSet() as $result) {
    $listaubicacion[$result->getId()] = $result->getNombreUbicacion();
}

$ubicacion = new Ubicacion();
$buscaUbicacion = $ubicacion->find();

foreach ($buscaUbicacion as $result) {
    $listaubicacion[$result->getId()] = $result->getNombreUbicacion();
}
?>

<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Ubicación de la Pantalla</b></legend>
    <p><label class='labelform' ><span for='ubicacion'>Ubicación:</span></label><?php echo Tag::selectStatic("ubicacion", $listaubicacion, "class:  required") ?></p>
</fieldset>


<?php
$tono = '';
$db = DbBase::rawConnect();
$result2 = $db->query("SELECT   tono    FROM pantalla WHERE id = $idPantalla");
while ($row = $db->fetchArray($result2)) {
    $tono = $row['tono'];
}
if ($tono == "")
    $tono = 0;$tono = $tono;
?>
<fieldset class="ui-corner-all ui-widget-content">
    <legend>Configuración del tono de llamado</legend>
    <p><label class='labelform' ><span for='RadioGroup0_0'><b>Timbre</b>:</span></label><input type="radio" name="rTono" id="rTono1" onclick="mostrar_datos_tono()" <?php if ($tono == 0) echo 'checked="checked"'; ?>/></p>
    <p><label class='labelform' ><span for='RadioGroup0_1'><b>Voz</b>:</span></label><input type="radio" name="rTono"  id="rTono2" onclick="mostrar_datos_tono()" <?php if ($tono == 1) echo 'checked="checked"'; ?> /></p>
    <div id="div_datos_tono" style="display: none">
        <input id="formato_voz" type="radio" value="caja-#" name="formato_voz" onclick="cambiar_valor()" class="">Caja #<br>
        <input id="formato_voz" type="radio" value="modulo-#" name="formato_voz" onclick="cambiar_valor()" class="">Módulo #<br>
        <input id="formato_voz" type="radio" value="ventanilla-#" name="formato_voz" onclick="cambiar_valor()" class="">Ventanilla #<br>
        <input id="formato_voz" type="radio" value="pase_a_la_caja-#" name="formato_voz" onclick="cambiar_valor()" class="">Pase a la Caja #<br>
        <input id="formato_voz" type="radio" value="pase_al_modulo-#" name="formato_voz" onclick="cambiar_valor()" class="">Pase al Módulo #<br>
        <input id="formato_voz" type="radio" value="pase_a_la_ventanilla-#" name="formato_voz" onclick="cambiar_valor()" class="">Pase a la Ventanilla #<br>
    </div>
    <p><label class='labelform'><span for='tiempo_tono'><b>Tiempo</b>:</span></label><?php echo Tag::numericField("tiempo_tono", "size: 10", "maxlength: 3", "class: required") ?></p>

    <?php echo Tag::hiddenField("tono", "size: 5", "maxlength: 5", "class: required", "value: $tono") ?>
</fieldset>

<fieldset class="ui-corner-all ui-widget-content">
    <legend>Tipo de voz</legend>
    <?php
    echo Tag::radioField("tipo_voz", array('M' => 'Masculino'));
    echo Tag::radioField("tipo_voz", array('F' => 'Femenino'));
    ?>
</fieldset>
<script>
    function cambiar_valor(){
        var v= $('input:radio[name=formato_voz]:checked').val();
        if(v=="caja-#")
            $("#tiempo_tono").val(5);
        else if(v=="modulo-#")
            $("#tiempo_tono").val(5);
        else if(v=="ventanilla-#")
            $("#tiempo_tono").val(5);
        else if(v=="pase_a_la_caja-#" | v=="pase_al_modulo-#")
            $("#tiempo_tono").val(5);
        else
            $("#tiempo_tono").val(6);
    }
    
    //$("#usuarios option[value=188]").attr("selected", true);
    //$('input:radio[name=rd_datos_tono][value=caja-#]').attr('checked', true);
    mostrar_datos_tono();
    function mostrar_datos_tono() {
        if ($('#rTono2').is(':checked') == true) {       //si selecciono voz
            $("#div_datos_tono").css('display', 'inline');
            $("#tiempo_tono").val(5);
        } else {
            $("#div_datos_tono").css('display', 'none');
            $("#tiempo_tono").val(5);
        }
       
    }


    $( document ).ready(function() {
         if ($('radio:contains("C")').is(':checked') == true) {       //si selecciono voz
            alert("hola");
        }
    });

    $("#rTono1").click(function() {
        document.getElementById('tono').value = 0;
    });
    $("#rTono2").click(function() {
        document.getElementById('tono').value = 1;
    });
</script>
