<fieldset class='ui-corner-all ui-widget-content'>
    <legend><label style="color:red"><b>Ayuda</b></label></legend>
    <p><label><b>Dirección IP: </b>Sirve para que aparezaca el nombre de usuario automáticamente en la PC con el monitor extendido.</label></p>
</fieldset>
<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Pantalla</b></legend>
    <p><label class='labelform' ><span for='descripcion'>Descripción:</span></label><?php echo Tag::textField("descripcion", "size: 45", "maxlength: 45","class: required") ?></p>
    <p><label class='labelform' ><span for='ip_equipo'>Dirección IP:</span></label><?php echo Tag::textField("ip_equipo", "size: 20", "maxlength: 15","class: ") ?></p>
    <!--
    <p><label class='labelform' ><span for='color_fondo'><b>Color del fondo</b>:</span></label><?php echo Tag::textField("color_fondo", "size: 10", "maxlength: 15","class: color") ?></p>
    <p><label class='labelform' ><span for='color_letra_turnoa'><b>Color letra de turno actual</b>:</span></label><?php echo Tag::textField("color_letra_turnoa", "size: 10", "maxlength: 10","class: color") ?></p>
    <p><label class='labelform' ><span for='tamanio_letra_turnoa'><b>Tamaño letra de turno actual</b>:</span></label><?php echo Tag::textField("tamanio_letra_turnoa", "size: 10", "maxlength: 10","class: required") ?></p>
    <p><label class='labelform' ><span for='color_letra_turno'><b>Color letra de turno anterior</b>:</span></label><?php echo Tag::textField("color_letra_turno", "size: 10", "maxlength: 10","class: color") ?></p>
    <p><label class='labelform' ><span for='tamanio_letra_turno'><b>Tamaño letra de turno anterior</b>:</span></label><?php echo Tag::textField("tamanio_letra_turno", "size: 10", "maxlength: 10","class: required") ?></p>
    -->
</fieldset>

<?php
$listausuarios=array();
$condicion = "{#Pantalla}.id = $id";
$query = new ActiveRecordJoin(array(
    "entities" => array("Usuario", "Pantalla", "Userpantalla"),
    "fields" => array(
    "{#Usuario}.id",
    "{#Usuario}.nombres"),
    "conditions" => $condicion
));
foreach($query->getResultSet() as $result) {
    $listausuarios[$result->getId()]=$result->getNombres();
}

$condicion = "{#Grupo}.id = 6";
$query = new ActiveRecordJoin(array(
    "entities" => array("Usuario", "Grupo", "Grupousuario"),
    "fields" => array(
    "{#Usuario}.id",
    "{#Usuario}.nombres"),
    "conditions" => $condicion
));
foreach($query->getResultSet() as $result) {
    $listausuarios[$result->getId()]=$result->getNombres();
}
?>
<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Usuario</b></legend>
    <p><label class='labelform' ><span for='usuarios'>Asignar a Usuario:</span></label><?php echo Tag::selectStatic("usuarios", $listausuarios,"class:  required") ?></p>
    <!--<p><label class='labelform' ><span for='usuarios'><b>Asignar a Usuario</b>:</span></label><?php //echo Tag::select("pantalla_id", $Pantalla->find("order: id"), "using: id,descripcion", "use_dummy: yes","dummyValue: ''","class: ") ?></p>-->
</fieldset>

<?php
//INICIO ubicacion de la pantalla
$listaubicacion=array();
$condicion = "{#Pantalla}.id = $id";
$query = new ActiveRecordJoin(array(
    "entities" => array("Ubicacion", "Pantalla"),
    "fields" => array(
    "{#Ubicacion}.id",
    "{#Ubicacion}.nombre_ubicacion"
    ),
    "conditions" => $condicion
));
foreach($query->getResultSet() as $result) {
    $listaubicacion[$result->getId()]=$result->getNombreUbicacion();
}

$ubicacion = new Ubicacion();
$buscaUbicacion = $ubicacion->find();

foreach($buscaUbicacion as $result) {
    $listaubicacion[$result->getId()]=$result->getNombreUbicacion();
}
?>

<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Ubicación de la Pantalla</b></legend>
    <p><label class='labelform' ><span for='ubicacion'>Ubicación:</span></label><?php echo Tag::selectStatic("ubicacion", $listaubicacion,"class:  required") ?></p>
</fieldset>

<fieldset class="ui-corner-all ui-widget-content">
    <legend><b>Tipo de Pantalla</b></legend>
    <table border="0px"  align="center">
        <tr>
            <td>
                <b><?php echo Tag::radioField("radio_tipo_pantalla",array ('A'=>'Pantalla para atención con tickets')) ?></b>
            </td>
        </tr>
        <tr>
            <td>
                <b><?php echo Tag::radioField("radio_tipo_pantalla",array ('B'=>'Pantalla para atención sin tickets')) ?></b>
            </td>
        </tr>
    </table>
</fieldset>