<?php echo Tag::javascriptBase() ?>
<!doctype html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        
        <!-- First, include the Webcam.js JavaScript Library -->
<!--        <script type="text/javascript" src="../webcam.js"></script>-->
<!--        <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js'></script>-->
        <script type="text/javascript" src="<?php echo Core::getInstancePath(); ?>public/js/webcam.js"></script>
        
        <script src="http://192.168.1.6:3000/socket.io/socket.io.js"></script>

        <title>WebcamJS Test Page</title>
        <style type="text/css">
            body { font-family: Helvetica, sans-serif; }
            h2, h3 { margin-top:0; }
            form { margin-top: 15px; }
            form > input { margin-right: 15px; }
            #results { float:right; margin:20px; padding:20px; border:1px solid; background:#ccc; }
        </style>
    </head>
    <body>
        <div id="results">Your captured image will appear here...</div>

        <h1>WebcamJS Test Page</h1>
        <h3>Demonstrates simple capture &amp; display</h3>

        <div id="my_camera" style="width:320px; height:240px;"></div>

        <input type="text" id="url" name="url" value="<?php echo Utils::getKumbiaUrl("calificador/ajax") ?>"/>


        <!-- Configure a few settings and attach camera -->
        <script language="JavaScript">
            Webcam.set({
                image_format: 'jpeg',
                jpeg_quality: 90
            });
            Webcam.attach('#my_camera');

            function take_snapshot() {
                // take snapshot and get image data
                var data_uri = Webcam.snap();

                // display results in page
                document.getElementById('results').innerHTML =
                        '<h2>Here is your image:</h2>' +
                        '<img src="' + data_uri + '"/>';

                prueba();
            }

            function prueba() {
                var data_uri = Webcam.snap();
                data = {
                    src: data_uri
                }
                $.ajax({
                    url: $("#url").val(),
                    data: data,
                    type: 'post',
                    success: function(respuesta) {
                        $('#fotoGuardada').attr('src', respuesta).show(500);
                    }
                });
            }
        </script>

        <!-- chat -->
        CHAT
        <div id="chat"></div>

        <!-- A button for taking snaps -->
        <form>
            <input type=button value="Take Snapshot" onClick="take_snapshot()">
            <input type=button value="Guardar" id="guardar" name="guardar" onclick="prueba()">
<!--            <span id="guardarFoto">Guardar Foto</span>-->
        </form>

        <div class="fotografia">
            <img id="fotoGuardada" src="" style="display:none" />
            <span class="marca">Foto Almacenada</span>
        </div>

        <!-- Code to handle taking the snapshot and displaying it locally -->
        <script language="JavaScript">

            //setInterval('verificar_array()', 300);  //verificar la cola de turnos
            jQuery(function($) {
                var socket = io.connect("http://192.168.1.6:3000");
                var $chat = $('#chat');
                socket.on('new message', function(data) {
                    //$chat.append(data + "<br/>");
                    $chat.text(data);   //envio a chat el msg
                    var ok = $("#chat").text();
                    if (ok == 'ok') {
                        take_snapshot();
                    }
                });
            });
        </script>
    </body>
</html>
